// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsLinkCategory = "cms_link_category"

// CmsLinkCategory mapped from table <cms_link_category>
type CmsLinkCategory struct {
	CategoryID     int64     `gorm:"column:category_id;type:bigint;primaryKey;autoIncrement:true" json:"category_id" form:"category_id"` // 主键
	ParentID       int64     `gorm:"column:parent_id;type:bigint" json:"parent_id" form:"parent_id"`                                     // 父节点
	SiteID         int64     `gorm:"column:site_id;type:bigint" json:"site_id" form:"site_id"`                                           // 所属站点
	ChannelID      int64     `gorm:"column:channel_id;type:bigint" json:"channel_id" form:"channel_id"`                                  // 所属频道
	Title          string    `gorm:"column:title;type:varchar(128)" json:"title" form:"title"`                                           // 类别标题
	CallIndex      string    `gorm:"column:call_index;type:varchar(64)" json:"call_index" form:"call_index"`                             // 调用别名
	LinkURL        string    `gorm:"column:link_url;type:varchar(256)" json:"link_url" form:"link_url"`                                  // 外部链接
	ImgUrl1        string    `gorm:"column:img_url1;type:varchar(256)" json:"img_url1" form:"img_url1"`                                  // 图片地址
	ImgUrl2        string    `gorm:"column:img_url2;type:varchar(256)" json:"img_url2" form:"img_url2"`                                  // 图片地址
	SeoTitle       string    `gorm:"column:seo_title;type:varchar(128)" json:"seo_title" form:"seo_title"`                               // SEO标题
	SeoKeyword     string    `gorm:"column:seo_keyword;type:varchar(128)" json:"seo_keyword" form:"seo_keyword"`                         // SEO关健字
	SeoDescription string    `gorm:"column:seo_description;type:varchar(128)" json:"seo_description" form:"seo_description"`             // SEO描述
	Content        string    `gorm:"column:content;type:text" json:"content" form:"content"`                                             // 详细内容
	SortID         int32     `gorm:"column:sort_id;type:int" json:"sort_id" form:"sort_id"`                                              // 排序
	Template       string    `gorm:"column:template;type:varchar(256)" json:"template" form:"template"`                                  // 模板路径
	BelongTo       string    `gorm:"column:belong_to;type:varchar(64)" json:"belong_to" form:"belong_to"`                                // 归属
	CreateID       int32     `gorm:"column:create_id;type:int" json:"create_id" form:"create_id"`                                        // 创建人ID
	CreateName     string    `gorm:"column:create_name;type:varchar(64)" json:"create_name" form:"create_name"`                          // 创建人姓名
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP" json:"create_time" form:"create_time"`   // 创建时间
	UpdateID       int32     `gorm:"column:update_id;type:int" json:"update_id" form:"update_id"`                                        // 更新人ID
	UpdateName     string    `gorm:"column:update_name;type:varchar(64)" json:"update_name" form:"update_name"`                          // 更新人姓名
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime" json:"update_time" form:"update_time"`                             // 修改时间
}

// TableName CmsLinkCategory's table name
func (*CmsLinkCategory) TableName() string {
	return TableNameCmsLinkCategory
}
