// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsSite = "cms_site"

// CmsSite mapped from table <cms_site>
type CmsSite struct {
	SiteID          int64     `gorm:"column:site_id;type:bigint;primaryKey;autoIncrement:true" json:"site_id" form:"site_id"`               // 主键
	ParentID        int64     `gorm:"column:parent_id;type:bigint;not null" json:"parent_id" form:"parent_id"`                              // 父级ID
	Name            string    `gorm:"column:name;type:varchar(128)" json:"name" form:"name"`                                                // 站点名称
	Title           string    `gorm:"column:title;type:varchar(128)" json:"title" form:"title"`                                             // 标题
	DirPath         string    `gorm:"column:dir_path;type:varchar(128)" json:"dir_path" form:"dir_path"`                                    // 模板目录名
	IsDefault       bool      `gorm:"column:is_default;type:tinyint(1)" json:"is_default" form:"is_default"`                                // 是否默认站
	IsMobile        bool      `gorm:"column:is_mobile;type:tinyint(1)" json:"is_mobile" form:"is_mobile"`                                   // 是否移动端
	Logo            string    `gorm:"column:logo;type:varchar(512)" json:"logo" form:"logo"`                                                // 网站LOGO
	Company         string    `gorm:"column:company;type:varchar(512)" json:"company" form:"company"`                                       // 公司名称
	Address         string    `gorm:"column:address;type:varchar(512)" json:"address" form:"address"`                                       // 通讯地址
	Telphone        string    `gorm:"column:telphone;type:varchar(64)" json:"telphone" form:"telphone"`                                     // 联系电话
	Fax             string    `gorm:"column:fax;type:varchar(64)" json:"fax" form:"fax"`                                                    // 传真
	Email           string    `gorm:"column:email;type:varchar(64)" json:"email" form:"email"`                                              // 邮箱
	Crod            string    `gorm:"column:crod;type:varchar(64)" json:"crod" form:"crod"`                                                 // 备案号
	Cache           int32     `gorm:"column:cache;type:int" json:"cache" form:"cache"`                                                      // 缓存时间
	MaxLength       int32     `gorm:"column:max_length;type:int;default:2048" json:"max_length" form:"max_length"`                          // 最大文件上传
	FileType        string    `gorm:"column:file_type;type:varchar(64);default:png|gif|jpg|jpeg|zip|rar" json:"file_type" form:"file_type"` // 上传文件类型
	HomeTitle       string    `gorm:"column:home_title;type:varchar(128)" json:"home_title" form:"home_title"`                              // 首页标题
	Copyright       string    `gorm:"column:copyright;type:varchar(128)" json:"copyright" form:"copyright"`                                 // 版权信息
	MetaKeyword     string    `gorm:"column:meta_keyword;type:varchar(512)" json:"meta_keyword" form:"meta_keyword"`                        // META关键词
	MetaDescription string    `gorm:"column:meta_description;type:varchar(128)" json:"meta_description" form:"meta_description"`            // META描述
	SortID          int32     `gorm:"column:sort_id;type:int" json:"sort_id" form:"sort_id"`                                                // 排序
	Status          int32     `gorm:"column:status;type:tinyint" json:"status" form:"status"`                                               // 状态0草稿1提交2审核通过3审核未通过4驳回
	IsDeleted       bool      `gorm:"column:is_deleted;type:tinyint(1)" json:"is_deleted" form:"is_deleted"`                                // 删除标识
	CreateID        int32     `gorm:"column:create_id;type:int" json:"create_id" form:"create_id"`                                          // 创建人ID
	CreateName      string    `gorm:"column:create_name;type:varchar(64)" json:"create_name" form:"create_name"`                            // 创建人姓名
	CreateTime      time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time" form:"create_time"`            // 创建时间
	UpdateID        int32     `gorm:"column:update_id;type:int" json:"update_id" form:"update_id"`                                          // 更新人ID
	UpdateName      string    `gorm:"column:update_name;type:varchar(64)" json:"update_name" form:"update_name"`                            // 更新人姓名
	UpdateTime      time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time" form:"update_time"`            // 修改时间
}

// TableName CmsSite's table name
func (*CmsSite) TableName() string {
	return TableNameCmsSite
}
