// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsTopic = "cms_topic"

// CmsTopic mapped from table <cms_topic>
type CmsTopic struct {
	TopicID        int64     `gorm:"column:topic_id;type:bigint;primaryKey;autoIncrement:true;comment:专题ID" json:"topic_id" form:"topic_id"`
	SiteID         int64     `gorm:"column:site_id;type:bigint;comment:所属站点" json:"site_id" form:"site_id"`
	ChannelID      int64     `gorm:"column:channel_id;type:bigint;comment:所属频道" json:"channel_id" form:"channel_id"`
	Name           string    `gorm:"column:name;type:varchar(64);comment:专题名称" json:"name" form:"name"`
	Title          string    `gorm:"column:title;type:varchar(128);comment:专题标题" json:"title" form:"title"`
	ImgUrl1        string    `gorm:"column:img_url1;type:varchar(256);comment:图片" json:"img_url1" form:"img_url1"`
	ImgUrl2        string    `gorm:"column:img_url2;type:varchar(256);comment:图片" json:"img_url2" form:"img_url2"`
	SeoTitle       string    `gorm:"column:seo_title;type:varchar(128);comment:SEO标题" json:"seo_title" form:"seo_title"`
	SeoKeyword     string    `gorm:"column:seo_keyword;type:varchar(128);comment:SEO关健字" json:"seo_keyword" form:"seo_keyword"`
	SeoDescription string    `gorm:"column:seo_description;type:varchar(128);comment:SEO描述" json:"seo_description" form:"seo_description"`
	Remark         string    `gorm:"column:remark;type:varchar(256);comment:备注" json:"remark" form:"remark"`
	SortID         int32     `gorm:"column:sort_id;type:int;comment:排序" json:"sort_id" form:"sort_id"`
	Click          int32     `gorm:"column:click;type:int;comment:浏览次数" json:"click" form:"click"`
	Status         int32     `gorm:"column:status;type:tinyint;comment:状态0草稿1提交2审核通过3审核未通过4驳回" json:"status" form:"status"`
	Template       string    `gorm:"column:template;type:varchar(256);comment:模板路径" json:"template" form:"template"`
	BelongTo       string    `gorm:"column:belong_to;type:varchar(64);comment:归属" json:"belong_to" form:"belong_to"`
	CreateID       int32     `gorm:"column:create_id;type:int;comment:创建人ID" json:"create_id" form:"create_id"`
	CreateName     string    `gorm:"column:create_name;type:varchar(64);comment:创建人姓名" json:"create_name" form:"create_name"`
	CreateTime     time.Time `gorm:"column:create_time;type:int unsigned;autoUpdateTime" json:"create_time" form:"create_time"`
	UpdateID       int32     `gorm:"column:update_id;type:int;comment:更新人ID" json:"update_id" form:"update_id"`
	UpdateName     string    `gorm:"column:update_name;type:varchar(64);comment:更新人姓名" json:"update_name" form:"update_name"`
	UpdateTime     time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time" form:"update_time"`
}

// TableName CmsTopic's table name
func (*CmsTopic) TableName() string {
	return TableNameCmsTopic
}
