// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCmsArticleCategoryRelation = "cms_article_category_relation"

// CmsArticleCategoryRelation mapped from table <cms_article_category_relation>
type CmsArticleCategoryRelation struct {
	RelationID int64 `gorm:"column:relation_id;type:bigint;primaryKey;autoIncrement:true" json:"relation_id" form:"relation_id"` // 主键
	CategoryID int64 `gorm:"column:category_id;type:bigint" json:"category_id" form:"category_id"`                               // 所属分类
	ArticleID  int64 `gorm:"column:article_id;type:bigint" json:"article_id" form:"article_id"`                                  // 所属文章
}

// TableName CmsArticleCategoryRelation's table name
func (*CmsArticleCategoryRelation) TableName() string {
	return TableNameCmsArticleCategoryRelation
}
