// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsSiteChannel = "cms_site_channel"

// CmsSiteChannel mapped from table <cms_site_channel>
type CmsSiteChannel struct {
	ChannelID  int64     `gorm:"column:channel_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"channel_id" form:"channel_id"`
	ParentID   int64     `gorm:"column:parent_id;type:bigint;not null;comment:父级ID" json:"parent_id" form:"parent_id"`
	SiteID     int64     `gorm:"column:site_id;type:bigint;comment:站点ID" json:"site_id" form:"site_id"`
	Name       string    `gorm:"column:name;type:varchar(128);comment:频道名称" json:"name" form:"name"`
	Title      string    `gorm:"column:title;type:varchar(128);comment:频道标题" json:"title" form:"title"`
	Kind       int32     `gorm:"column:kind;type:tinyint;comment:频道类型0文章1链接" json:"kind" form:"kind"`
	ClassLayer int32     `gorm:"column:class_layer;type:int;default:1;comment:类别深度" json:"class_layer" form:"class_layer"`
	LinkURL    string    `gorm:"column:link_url;type:varchar(256);comment:外部链接" json:"link_url" form:"link_url"`
	Target     string    `gorm:"column:target;type:varchar(16);default:_blank;comment:是否开启浏览器新窗口" json:"target" form:"target"`
	ImgUrl1    string    `gorm:"column:img_url1;type:varchar(256);comment:图片地址" json:"img_url1" form:"img_url1"`
	ImgUrl2    string    `gorm:"column:img_url2;type:varchar(256);comment:图片地址" json:"img_url2" form:"img_url2"`
	IsComment  int32     `gorm:"column:is_comment;type:tinyint;comment:是否开启评论" json:"is_comment" form:"is_comment"`
	IsAlbum    int32     `gorm:"column:is_album;type:tinyint;comment:是否开启相册功能" json:"is_album" form:"is_album"`
	IsAttach   int32     `gorm:"column:is_attach;type:tinyint;comment:是否开启附件功能" json:"is_attach" form:"is_attach"`
	IsSpec     int32     `gorm:"column:is_spec;type:tinyint;comment:是否开启规格" json:"is_spec" form:"is_spec"`
	SortID     int32     `gorm:"column:sort_id;type:int;comment:排序" json:"sort_id" form:"sort_id"`
	Status     int32     `gorm:"column:status;type:tinyint;comment:状态0草稿1提交2审核通过3审核未通过4驳回" json:"status" form:"status"`
	IsDeleted  bool      `gorm:"column:is_deleted;type:tinyint(1);comment:删除标识" json:"is_deleted" form:"is_deleted"`
	Template   string    `gorm:"column:template;type:varchar(256);comment:模板路径" json:"template" form:"template"`
	CreateID   int32     `gorm:"column:create_id;type:int;comment:创建人ID" json:"create_id" form:"create_id"`
	CreateName string    `gorm:"column:create_name;type:varchar(64);comment:创建人姓名" json:"create_name" form:"create_name"`
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoUpdateTime" json:"create_time" form:"create_time"`
	UpdateID   int32     `gorm:"column:update_id;type:int;comment:更新人ID" json:"update_id" form:"update_id"`
	UpdateName string    `gorm:"column:update_name;type:varchar(64);comment:更新人姓名" json:"update_name" form:"update_name"`
	UpdateTime time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time" form:"update_time"`
}

// TableName CmsSiteChannel's table name
func (*CmsSiteChannel) TableName() string {
	return TableNameCmsSiteChannel
}
