// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsAlbum = "cms_album"

// CmsAlbum mapped from table <cms_album>
type CmsAlbum struct {
	AlbumID      int64     `gorm:"column:album_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"album_id" form:"album_id"`
	TableName_   string    `gorm:"column:table_name;type:varchar(128);comment:关联表名" json:"table_name" form:"table_name"`
	RecordID     int64     `gorm:"column:record_id;type:bigint;comment:关联记录ID" json:"record_id" form:"record_id"`
	TypeID       int32     `gorm:"column:type_id;type:int;comment:分类" json:"type_id" form:"type_id"`
	Title        string    `gorm:"column:title;type:varchar(128);comment:标题" json:"title" form:"title"`
	ThumbPath    string    `gorm:"column:thumb_path;type:varchar(512);comment:缩略图地址" json:"thumb_path" form:"thumb_path"`
	OriginalPath string    `gorm:"column:original_path;type:varchar(512);comment:原图地址" json:"original_path" form:"original_path"`
	FilePath     string    `gorm:"column:file_path;type:varchar(512);comment:文件路径（带域名）" json:"file_path" form:"file_path"`
	FileSize     int64     `gorm:"column:file_size;type:bigint;comment:文件大小(字节)" json:"file_size" form:"file_size"`
	FileMime     string    `gorm:"column:file_mime;type:varchar(256);comment:Mime类型" json:"file_mime" form:"file_mime"`
	FileExt      string    `gorm:"column:file_ext;type:varchar(16);comment:文件扩展名" json:"file_ext" form:"file_ext"`
	LinkURL      string    `gorm:"column:link_url;type:varchar(256);comment:外部链接" json:"link_url" form:"link_url"`
	Click        int32     `gorm:"column:click;type:int;comment:点击次数" json:"click" form:"click"`
	SortID       int32     `gorm:"column:sort_id;type:int;comment:排序" json:"sort_id" form:"sort_id"`
	IsShow       int32     `gorm:"column:is_show;type:tinyint;comment:是否显示：1显示2隐藏" json:"is_show" form:"is_show"`
	Remark       string    `gorm:"column:remark;type:varchar(256);comment:图片描述" json:"remark" form:"remark"`
	CreateID     int32     `gorm:"column:create_id;type:int;comment:创建人ID" json:"create_id" form:"create_id"`
	CreateName   string    `gorm:"column:create_name;type:varchar(64);comment:创建人姓名" json:"create_name" form:"create_name"`
	CreateTime   time.Time `gorm:"column:create_time;type:int unsigned;autoUpdateTime" json:"create_time" form:"create_time"`
	UpdateID     int32     `gorm:"column:update_id;type:int;comment:更新人ID" json:"update_id" form:"update_id"`
	UpdateName   string    `gorm:"column:update_name;type:varchar(64);comment:更新人姓名" json:"update_name" form:"update_name"`
	UpdateTime   time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time" form:"update_time"`
}

// TableName CmsAlbum's table name
func (*CmsAlbum) TableName() string {
	return TableNameCmsAlbum
}
