// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCmsAdmin = "cms_admin"

// CmsAdmin mapped from table <cms_admin>
type CmsAdmin struct {
	UserID     int64     `gorm:"column:user_id;type:bigint;primaryKey;autoIncrement:true" json:"user_id" form:"user_id"`    // 主键
	UserName   string    `gorm:"column:user_name;type:varchar(128)" json:"user_name" form:"user_name"`                      // 账号
	Password   string    `gorm:"column:password;type:varchar(128)" json:"password" form:"password"`                         // 密码
	RealName   string    `gorm:"column:real_name;type:varchar(128)" json:"real_name" form:"real_name"`                      // 姓名
	Avatar     string    `gorm:"column:avatar;type:varchar(128)" json:"avatar" form:"avatar"`                               // 会员头像
	IsAudit    int32     `gorm:"column:is_audit;type:tinyint" json:"is_audit" form:"is_audit"`                              // 启用发布审核
	SortID     int32     `gorm:"column:sort_id;type:int" json:"sort_id" form:"sort_id"`                                     // 排序
	Remark     string    `gorm:"column:remark;type:varchar(512)" json:"remark" form:"remark"`                               // 备注说明
	LastIP     string    `gorm:"column:last_ip;type:varchar(64)" json:"last_ip" form:"last_ip"`                             // 最后登录IP
	LastTime   string    `gorm:"column:last_time;type:varchar(64)" json:"last_time" form:"last_time"`                       // 最后登录时间
	IsDeleted  bool      `gorm:"column:is_deleted;type:tinyint(1)" json:"is_deleted" form:"is_deleted"`                     // 删除标识
	CreateTime time.Time `gorm:"column:create_time;type:int unsigned;autoCreateTime" json:"create_time" form:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:int unsigned;autoUpdateTime" json:"update_time" form:"update_time"` // 修改时间
}

// TableName CmsAdmin's table name
func (*CmsAdmin) TableName() string {
	return TableNameCmsAdmin
}
