appname = cms
httpport = 8125
runmode = dev

copyrequestbody = true
sessionon = true
# 设置session保存到文件中
sessionprovider = "file"
# session数据保存目录
sessionproviderconfig = "./data/session"
# 站点名称
site.name = 毕业生网上签约与毕业去向登记平台

# cms数据库
cms.host = rm-2ze30c2e7p5bq264i.mysql.rds.aliyuncs.com
cms.user = root
cms.password = JY3x63qdfcfj*
cms.port = 3306
cms.db = cms
cms.prefix = cms_
cms.timezone = Asia/Shanghai

# 认证数据库
auth.host = rm-2ze30c2e7p5bq264i.mysql.rds.aliyuncs.com
auth.user = root
auth.password = JY3x63qdfcfj* 
auth.port = 3306
auth.db = un2co_yunzhipin
auth.prefix = un2co_
auth.timezone = Asia/Shanghai

# 配置参数
LOCAL_DOMAIN = http://cms.hnzhjypt.com

# cas配置
cas.enabled = true
cas.url = http://cas.hnzhjypt.com