appname = cms
httpport = 8125
runmode = dev
copyrequestbody = true

sessionon = true
# 设置session保存到文件中
sessionprovider = "file"
# session数据保存目录
sessionproviderconfig = "./logs/session"
# 站点名称
site.name = 内容管理

# cms数据库
cms.host = 172.18.0.2
cms.user = root
cms.password = hnQkx@1098uw
cms.port = 3306
cms.db = cms
cms.prefix = cms_
cms.timezone = Asia/Shanghai

# 认证数据库
auth.host = 172.18.0.2
auth.user = root
auth.password = hnQkx@1098uw
auth.port = 3306
auth.db = un2co_yunzhipin
auth.prefix = un2co_
auth.timezone = Asia/Shanghai

# 配置参数
LOCAL_DOMAIN = https://cms.haqkx.cn

# cas配置
cas.enabled = false
cas.url = http://cas.hnzhjypt.com