// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameCmsSiteChannel = "cms_site_channel"

// CmsSiteChannel mapped from table <cms_site_channel>
type CmsSiteChannel struct {
	ChannelID  int64     `gorm:"column:channel_id;type:bigint;primaryKey;autoIncrement:true" json:"channel_id" form:"channel_id"`  // 主键
	ParentID   int64     `gorm:"column:parent_id;type:bigint;not null" json:"parent_id" form:"parent_id"`                          // 父级ID
	SiteID     int64     `gorm:"column:site_id;type:bigint" json:"site_id" form:"site_id"`                                         // 站点ID
	Name       string    `gorm:"column:name;type:varchar(128)" json:"name" form:"name"`                                            // 频道名称
	Title      string    `gorm:"column:title;type:varchar(128)" json:"title" form:"title"`                                         // 频道标题
	Kind       int32     `gorm:"column:kind;type:tinyint" json:"kind" form:"kind"`                                                 // 频道类型0文章1链接
	ClassLayer int32     `gorm:"column:class_layer;type:int;default:1" json:"class_layer" form:"class_layer"`                      // 类别深度
	LinkURL    string    `gorm:"column:link_url;type:varchar(256)" json:"link_url" form:"link_url"`                                // 外部链接
	Target     string    `gorm:"column:target;type:varchar(16);default:_blank" json:"target" form:"target"`                        // 是否开启浏览器新窗口
	ImgUrl1    string    `gorm:"column:img_url1;type:varchar(256)" json:"img_url1" form:"img_url1"`                                // 图片地址
	ImgUrl2    string    `gorm:"column:img_url2;type:varchar(256)" json:"img_url2" form:"img_url2"`                                // 图片地址
	IsComment  int32     `gorm:"column:is_comment;type:tinyint" json:"is_comment" form:"is_comment"`                               // 是否开启评论
	IsAlbum    int32     `gorm:"column:is_album;type:tinyint" json:"is_album" form:"is_album"`                                     // 是否开启相册功能
	IsAttach   int32     `gorm:"column:is_attach;type:tinyint" json:"is_attach" form:"is_attach"`                                  // 是否开启附件功能
	IsSpec     int32     `gorm:"column:is_spec;type:tinyint" json:"is_spec" form:"is_spec"`                                        // 是否开启规格
	SortID     int32     `gorm:"column:sort_id;type:int" json:"sort_id" form:"sort_id"`                                            // 排序
	Status     int32     `gorm:"column:status;type:tinyint" json:"status" form:"status"`                                           // 状态0草稿1提交2审核通过3审核未通过4驳回
	IsDeleted  bool      `gorm:"column:is_deleted;type:tinyint(1)" json:"is_deleted" form:"is_deleted"`                            // 删除标识
	IsShow     bool      `gorm:"column:is_show;type:tinyint(1);default:1" json:"is_show" form:"is_show"`                           // 是否显示:1显示，0隐藏
	TmplChnl   string    `gorm:"column:tmpl_chnl;type:varchar(256)" json:"tmpl_chnl" form:"tmpl_chnl"`                             // 频道模板路径
	TmplCat    string    `gorm:"column:tmpl_cat;type:varchar(256)" json:"tmpl_cat" form:"tmpl_cat"`                                // 栏目模板路径
	TmplLst    string    `gorm:"column:tmpl_lst;type:varchar(256)" json:"tmpl_lst" form:"tmpl_lst"`                                // 列表模板路径
	TmplDtl    string    `gorm:"column:tmpl_dtl;type:varchar(256)" json:"tmpl_dtl" form:"tmpl_dtl"`                                // 明细模板路径
	CreateID   int32     `gorm:"column:create_id;type:int" json:"create_id" form:"create_id"`                                      // 创建人ID
	CreateName string    `gorm:"column:create_name;type:varchar(64)" json:"create_name" form:"create_name"`                        // 创建人姓名
	CreateTime time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP" json:"create_time" form:"create_time"` // 创建时间
	UpdateID   int32     `gorm:"column:update_id;type:int" json:"update_id" form:"update_id"`                                      // 更新人ID
	UpdateName string    `gorm:"column:update_name;type:varchar(64)" json:"update_name" form:"update_name"`                        // 更新人姓名
	UpdateTime time.Time `gorm:"column:update_time;type:datetime" json:"update_time" form:"update_time"`                           // 修改时间
}

// TableName CmsSiteChannel's table name
func (*CmsSiteChannel) TableName() string {
	return TableNameCmsSiteChannel
}
