// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameCmsArticleComment = "cms_article_comment"

// CmsArticleComment mapped from table <cms_article_comment>
type CmsArticleComment struct {
	CommentID    int64     `gorm:"column:comment_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"comment_id" form:"comment_id"`
	ParentID     int64     `gorm:"column:parent_id;type:bigint;comment:父评论ID" json:"parent_id" form:"parent_id"`
	ArticleID    int64     `gorm:"column:article_id;type:bigint;comment:所属文章" json:"article_id" form:"article_id"`
	SiteID       int64     `gorm:"column:site_id;type:bigint;comment:站点ID" json:"site_id" form:"site_id"`
	ChannelID    int64     `gorm:"column:channel_id;type:bigint;comment:频道ID" json:"channel_id" form:"channel_id"`
	UserID       int64     `gorm:"column:user_id;type:bigint;comment:用户ID" json:"user_id" form:"user_id"`
	UserName     string    `gorm:"column:user_name;type:varchar(64);comment:用户名" json:"user_name" form:"user_name"`
	UserIP       string    `gorm:"column:user_ip;type:varchar(64);comment:用户IP" json:"user_ip" form:"user_ip"`
	Content      string    `gorm:"column:content;type:varchar(512);comment:评论内容" json:"content" form:"content"`
	Status       int32     `gorm:"column:status;type:tinyint;comment:状态0草稿1提交2审核通过3审核未通过4驳回" json:"status" form:"status"`
	IsLock       bool      `gorm:"column:is_lock;type:tinyint(1);comment:是否锁定" json:"is_lock" form:"is_lock"`
	AddTime      time.Time `gorm:"column:add_time;type:datetime;default:CURRENT_TIMESTAMP;comment:发表时间" json:"add_time" form:"add_time"`
	IsReply      bool      `gorm:"column:is_reply;type:tinyint(1);comment:是否已答复" json:"is_reply" form:"is_reply"`
	ReplyUser    string    `gorm:"column:reply_user;type:varchar(64);comment:回复户名" json:"reply_user" form:"reply_user"`
	ReplyContent string    `gorm:"column:reply_content;type:varchar(512);comment:答复内容" json:"reply_content" form:"reply_content"`
	ReplyTime    time.Time `gorm:"column:reply_time;type:datetime;default:CURRENT_TIMESTAMP;comment:回复时间" json:"reply_time" form:"reply_time"`
}

// TableName CmsArticleComment's table name
func (*CmsArticleComment) TableName() string {
	return TableNameCmsArticleComment
}
