// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameCmsAdmin = "cms_admin"

// CmsAdmin mapped from table <cms_admin>
type CmsAdmin struct {
	UserID         int64     `gorm:"column:user_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"user_id" form:"user_id"`
	RoleID         int64     `gorm:"column:role_id;type:bigint;not null;comment:角色ID" json:"role_id" form:"role_id"`
	RoleType       string    `gorm:"column:role_type;type:varchar(64);not null;comment:角色类型supper超级用户,system系统用户" json:"role_type" form:"role_type"`
	RealName       string    `gorm:"column:real_name;type:varchar(128);comment:姓名" json:"real_name" form:"real_name"`
	NickName       string    `gorm:"column:nick_name;type:varchar(64);comment:昵称" json:"nick_name" form:"nick_name"`
	IDCard         string    `gorm:"column:id_card;type:varchar(32);comment:身份证号" json:"id_card" form:"id_card"`
	Sex            int32     `gorm:"column:sex;type:int;comment:性别（1男2女0未知）" json:"sex" form:"sex"`
	UserName       string    `gorm:"column:user_name;type:varchar(128);comment:用户名(登录名),保持系统唯一" json:"user_name" form:"user_name"`
	UserNumber     string    `gorm:"column:user_number;type:varchar(32);comment:其他唯一特征标识：如教职工的工号或学生的学号" json:"user_number" form:"user_number"`
	Password       string    `gorm:"column:password;type:varchar(64);comment:密码" json:"password" form:"password"`
	PasswordSalt   string    `gorm:"column:password_salt;type:varchar(64);comment:密码的Hash值" json:"password_salt" form:"password_salt"`
	PasswordFormat int32     `gorm:"column:password_format;type:int;default:1;comment:密码加密格式 0不加密 1默认加密 2MD5类型" json:"password_format" form:"password_format"`
	Email          string    `gorm:"column:email;type:varchar(256);comment:邮箱" json:"email" form:"email"`
	Telphone       string    `gorm:"column:telphone;type:varchar(16);comment:固话" json:"telphone" form:"telphone"`
	Mobile         string    `gorm:"column:mobile;type:varchar(16);comment:手机号码" json:"mobile" form:"mobile"`
	MobilePin      string    `gorm:"column:mobile_pin;type:varchar(32);comment:手机PIN码" json:"mobile_pin" form:"mobile_pin"`
	UserType       int32     `gorm:"column:user_type;type:int;comment:用户类别(0管理员），根据业务定义其他类型（如1学生2教职工；如1商家2卖家）" json:"user_type" form:"user_type"`
	Enabled        bool      `gorm:"column:enabled;type:tinyint(1);not null;default:1;comment:是否可用:1可用 0禁用" json:"enabled" form:"enabled"`
	Remark         string    `gorm:"column:remark;type:varchar(256);comment:描述" json:"remark" form:"remark"`
	Avatar         string    `gorm:"column:avatar;type:varchar(128);comment:会员头像" json:"avatar" form:"avatar"`
	IsAudit        int32     `gorm:"column:is_audit;type:tinyint;comment:启用发布审核" json:"is_audit" form:"is_audit"`
	SortID         int32     `gorm:"column:sort_id;type:int;comment:排序" json:"sort_id" form:"sort_id"`
	LastIP         string    `gorm:"column:last_ip;type:varchar(64);comment:最后登录IP" json:"last_ip" form:"last_ip"`
	LastTime       string    `gorm:"column:last_time;type:varchar(64);comment:最后登录时间" json:"last_time" form:"last_time"`
	IsDeleted      bool      `gorm:"column:is_deleted;type:tinyint(1);comment:删除标识" json:"is_deleted" form:"is_deleted"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time" form:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;comment:修改时间" json:"update_time" form:"update_time"`
}

// TableName CmsAdmin's table name
func (*CmsAdmin) TableName() string {
	return TableNameCmsAdmin
}
