// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

const TableNameCmsAdminRoleSite = "cms_admin_role_site"

// CmsAdminRoleSite mapped from table <cms_admin_role_site>
type CmsAdminRoleSite struct {
	ValueID int64 `gorm:"column:value_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"value_id" form:"value_id"`
	RoleID  int64 `gorm:"column:role_id;type:bigint;not null;comment:角色" json:"role_id" form:"role_id"`
	SiteID  int64 `gorm:"column:site_id;type:bigint;not null;comment:站点" json:"site_id" form:"site_id"`
}

// TableName CmsAdminRoleSite's table name
func (*CmsAdminRoleSite) TableName() string {
	return TableNameCmsAdminRoleSite
}
