// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameCmsAdminNav = "cms_admin_nav"

// CmsAdminNav mapped from table <cms_admin_nav>
type CmsAdminNav struct {
	NavID      int64     `gorm:"column:nav_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"nav_id" form:"nav_id"`
	ParentID   int64     `gorm:"column:parent_id;type:bigint;comment:父节点" json:"parent_id" form:"parent_id"`
	SiteID     int64     `gorm:"column:site_id;type:bigint;comment:站点ID" json:"site_id" form:"site_id"`
	ChannelID  int64     `gorm:"column:channel_id;type:bigint;comment:频道ID" json:"channel_id" form:"channel_id"`
	Type       string    `gorm:"column:type;type:varchar(32);default:System;comment:导航类别" json:"type" form:"type"`
	Name       string    `gorm:"column:name;type:varchar(128);comment:导航ID" json:"name" form:"name"`
	Title      string    `gorm:"column:title;type:varchar(128);comment:标题" json:"title" form:"title"`
	SubTitle   string    `gorm:"column:sub_title;type:varchar(128);comment:副标题" json:"sub_title" form:"sub_title"`
	IconURL    string    `gorm:"column:icon_url;type:varchar(128);comment:图标地址" json:"icon_url" form:"icon_url"`
	LinkURL    string    `gorm:"column:link_url;type:varchar(256);comment:链接地址" json:"link_url" form:"link_url"`
	IsHide     int32     `gorm:"column:is_hide;type:tinyint;comment:是否隐藏0显示1隐藏" json:"is_hide" form:"is_hide"`
	SortID     int32     `gorm:"column:sort_id;type:int;comment:排序" json:"sort_id" form:"sort_id"`
	Action     string    `gorm:"column:action;type:varchar(128);comment:权限资源" json:"action" form:"action"`
	IsSys      int32     `gorm:"column:is_sys;type:tinyint;comment:是否系统默认0否1是" json:"is_sys" form:"is_sys"`
	Remark     string    `gorm:"column:remark;type:varchar(256);comment:备注" json:"remark" form:"remark"`
	CreateID   int32     `gorm:"column:create_id;type:int;comment:创建人ID" json:"create_id" form:"create_id"`
	CreateName string    `gorm:"column:create_name;type:varchar(64);comment:创建人姓名" json:"create_name" form:"create_name"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time" form:"create_time"`
	UpdateID   int32     `gorm:"column:update_id;type:int;comment:更新人ID" json:"update_id" form:"update_id"`
	UpdateName string    `gorm:"column:update_name;type:varchar(64);comment:更新人姓名" json:"update_name" form:"update_name"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;comment:修改时间" json:"update_time" form:"update_time"`
}

// TableName CmsAdminNav's table name
func (*CmsAdminNav) TableName() string {
	return TableNameCmsAdminNav
}
