// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameCmsArticleCategory = "cms_article_category"

// CmsArticleCategory mapped from table <cms_article_category>
type CmsArticleCategory struct {
	CategoryID     int64     `gorm:"column:category_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"category_id" form:"category_id"`
	ParentID       int64     `gorm:"column:parent_id;type:bigint;comment:父节点" json:"parent_id" form:"parent_id"`
	SiteID         int64     `gorm:"column:site_id;type:bigint;comment:所属站点" json:"site_id" form:"site_id"`
	ChannelID      int64     `gorm:"column:channel_id;type:bigint;comment:所属频道" json:"channel_id" form:"channel_id"`
	Title          string    `gorm:"column:title;type:varchar(128);comment:类别标题" json:"title" form:"title"`
	CallIndex      string    `gorm:"column:call_index;type:varchar(64);comment:调用别名" json:"call_index" form:"call_index"`
	ClassLayer     int32     `gorm:"column:class_layer;type:int;default:1;comment:类别深度" json:"class_layer" form:"class_layer"`
	LinkURL        string    `gorm:"column:link_url;type:varchar(256);comment:外部链接" json:"link_url" form:"link_url"`
	Target         string    `gorm:"column:target;type:varchar(16);default:_blank;comment:是否开启浏览器新窗口" json:"target" form:"target"`
	ImgUrl1        string    `gorm:"column:img_url1;type:varchar(256);comment:图片地址" json:"img_url1" form:"img_url1"`
	ImgUrl2        string    `gorm:"column:img_url2;type:varchar(256);comment:图片地址" json:"img_url2" form:"img_url2"`
	SeoTitle       string    `gorm:"column:seo_title;type:varchar(128);comment:SEO标题" json:"seo_title" form:"seo_title"`
	SeoKeyword     string    `gorm:"column:seo_keyword;type:varchar(128);comment:SEO关健字" json:"seo_keyword" form:"seo_keyword"`
	SeoDescription string    `gorm:"column:seo_description;type:varchar(128);comment:SEO描述" json:"seo_description" form:"seo_description"`
	Content        string    `gorm:"column:content;type:text;comment:内容介绍" json:"content" form:"content"`
	SortID         int32     `gorm:"column:sort_id;type:int;comment:排序" json:"sort_id" form:"sort_id"`
	IsShow         bool      `gorm:"column:is_show;type:tinyint(1);default:1;comment:是否显示:1显示，0隐藏" json:"is_show" form:"is_show"`
	IsSearch       bool      `gorm:"column:is_search;type:tinyint(1);default:1;comment:允许检索:1允许，0禁止" json:"is_search" form:"is_search"`
	IsDeleted      bool      `gorm:"column:is_deleted;type:tinyint(1);comment:删除标识" json:"is_deleted" form:"is_deleted"`
	Status         int32     `gorm:"column:status;type:tinyint;comment:状态0草稿1提交2审核通过3审核未通过4驳回" json:"status" form:"status"`
	TmplCat        string    `gorm:"column:tmpl_cat;type:varchar(256);comment:栏目模板路径" json:"tmpl_cat" form:"tmpl_cat"`
	TmplLst        string    `gorm:"column:tmpl_lst;type:varchar(256);comment:列表模板路径" json:"tmpl_lst" form:"tmpl_lst"`
	TmplDtl        string    `gorm:"column:tmpl_dtl;type:varchar(256);comment:明细模板路径" json:"tmpl_dtl" form:"tmpl_dtl"`
	BelongTo       string    `gorm:"column:belong_to;type:varchar(64);comment:归属" json:"belong_to" form:"belong_to"`
	CreateID       int32     `gorm:"column:create_id;type:int;comment:创建人ID" json:"create_id" form:"create_id"`
	CreateName     string    `gorm:"column:create_name;type:varchar(64);comment:创建人姓名" json:"create_name" form:"create_name"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time" form:"create_time"`
	UpdateID       int32     `gorm:"column:update_id;type:int;comment:更新人ID" json:"update_id" form:"update_id"`
	UpdateName     string    `gorm:"column:update_name;type:varchar(64);comment:更新人姓名" json:"update_name" form:"update_name"`
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;comment:修改时间" json:"update_time" form:"update_time"`
}

// TableName CmsArticleCategory's table name
func (*CmsArticleCategory) TableName() string {
	return TableNameCmsArticleCategory
}
