// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package domain

import (
	"time"
)

const TableNameWeixinResponseContent = "weixin_response_content"

// WeixinResponseContent mapped from table <weixin_response_content>
type WeixinResponseContent struct {
	ContentID      int64     `gorm:"column:content_id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"content_id" form:"content_id"`
	AccountID      int64     `gorm:"column:account_id;type:bigint;not null;comment:归属公众号" json:"account_id" form:"account_id"`
	OpenID         string    `gorm:"column:open_id;type:varchar(128);comment:用户微信ID" json:"open_id" form:"open_id"`
	RequestType    string    `gorm:"column:request_type;type:varchar(32);comment:数据类型 文本消息：text 图片消息:image 地理位置消息:location 链接消息:link 事件:event" json:"request_type" form:"request_type"`
	RequestContent string    `gorm:"column:request_content;type:varchar(2048);comment:数据内容" json:"request_content" form:"request_content"`
	ResponseType   string    `gorm:"column:response_type;type:varchar(32);comment:回复的类型 文本消息：text 图片消息:image 地理位置消息:location 链接消息:link" json:"response_type" form:"response_type"`
	ReponseContent string    `gorm:"column:reponse_content;type:varchar(2048);comment:系统回复的内容" json:"reponse_content" form:"reponse_content"`
	MeidaHdURL     string    `gorm:"column:meida_hd_url;type:varchar(512);comment:高清语音或者视频地址" json:"meida_hd_url" form:"meida_hd_url"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time" form:"create_time"`
	XMLContent     string    `gorm:"column:xml_content;type:varchar(2048);comment:xml原始内容" json:"xml_content" form:"xml_content"`
	AddTime        time.Time `gorm:"column:add_time;type:datetime;default:CURRENT_TIMESTAMP;comment:录入系统的时间" json:"add_time" form:"add_time"`
	TenantID int64 `gorm:"column:tenant_id;type:bigint;not null;default:0;index;comment:租户ID(多租户隔离)" json:"tenant_id" form:"tenant_id"`
	Deleted bool `gorm:"column:deleted;type:tinyint(1);not null;default:0;index;comment:逻辑删除标识(0未删除1已删除)" json:"deleted" form:"deleted"`
}

// TableName WeixinResponseContent's table name
func (*WeixinResponseContent) TableName() string {
	return TableNameWeixinResponseContent
}
