// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newAdminNotice(db *gorm.DB, opts ...gen.DOOption) adminNotice {
	_adminNotice := adminNotice{}

	_adminNotice.adminNoticeDo.UseDB(db, opts...)
	_adminNotice.adminNoticeDo.UseModel(&model.AdminNotice{})

	tableName := _adminNotice.adminNoticeDo.TableName()
	_adminNotice.ALL = field.NewAsterisk(tableName)
	_adminNotice.NoticeID = field.NewInt64(tableName, "notice_id")
	_adminNotice.Title = field.NewString(tableName, "title")
	_adminNotice.SubTitle = field.NewString(tableName, "sub_title")
	_adminNotice.Content = field.NewString(tableName, "content")
	_adminNotice.SortID = field.NewInt32(tableName, "sort_id")
	_adminNotice.IsTop = field.NewInt32(tableName, "is_top")
	_adminNotice.Status = field.NewInt32(tableName, "status")
	_adminNotice.PublishTime = field.NewTime(tableName, "publish_time")
	_adminNotice.CreateID = field.NewInt32(tableName, "create_id")
	_adminNotice.CreateName = field.NewString(tableName, "create_name")
	_adminNotice.CreateTime = field.NewTime(tableName, "create_time")
	_adminNotice.UpdateID = field.NewInt32(tableName, "update_id")
	_adminNotice.UpdateName = field.NewString(tableName, "update_name")
	_adminNotice.UpdateTime = field.NewTime(tableName, "update_time")

	_adminNotice.fillFieldMap()

	return _adminNotice
}

type adminNotice struct {
	adminNoticeDo adminNoticeDo

	ALL         field.Asterisk
	NoticeID    field.Int64  // 主键
	Title       field.String // 内容标题
	SubTitle    field.String // 副标题
	Content     field.String // 详细内容
	SortID      field.Int32  // 排序
	IsTop       field.Int32  // 是否置顶
	Status      field.Int32  // 状态0草稿1提交2审核通过3审核未通过4驳回
	PublishTime field.Time   // 发布时间
	CreateID    field.Int32  // 创建人ID
	CreateName  field.String // 创建人姓名
	CreateTime  field.Time   // 创建时间
	UpdateID    field.Int32  // 更新人ID
	UpdateName  field.String // 更新人姓名
	UpdateTime  field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (a adminNotice) Table(newTableName string) *adminNotice {
	a.adminNoticeDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a adminNotice) As(alias string) *adminNotice {
	a.adminNoticeDo.DO = *(a.adminNoticeDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *adminNotice) updateTableName(table string) *adminNotice {
	a.ALL = field.NewAsterisk(table)
	a.NoticeID = field.NewInt64(table, "notice_id")
	a.Title = field.NewString(table, "title")
	a.SubTitle = field.NewString(table, "sub_title")
	a.Content = field.NewString(table, "content")
	a.SortID = field.NewInt32(table, "sort_id")
	a.IsTop = field.NewInt32(table, "is_top")
	a.Status = field.NewInt32(table, "status")
	a.PublishTime = field.NewTime(table, "publish_time")
	a.CreateID = field.NewInt32(table, "create_id")
	a.CreateName = field.NewString(table, "create_name")
	a.CreateTime = field.NewTime(table, "create_time")
	a.UpdateID = field.NewInt32(table, "update_id")
	a.UpdateName = field.NewString(table, "update_name")
	a.UpdateTime = field.NewTime(table, "update_time")

	a.fillFieldMap()

	return a
}

func (a *adminNotice) WithContext(ctx context.Context) *adminNoticeDo {
	return a.adminNoticeDo.WithContext(ctx)
}

func (a adminNotice) TableName() string { return a.adminNoticeDo.TableName() }

func (a adminNotice) Alias() string { return a.adminNoticeDo.Alias() }

func (a adminNotice) Columns(cols ...field.Expr) gen.Columns { return a.adminNoticeDo.Columns(cols...) }

func (a *adminNotice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *adminNotice) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 14)
	a.fieldMap["notice_id"] = a.NoticeID
	a.fieldMap["title"] = a.Title
	a.fieldMap["sub_title"] = a.SubTitle
	a.fieldMap["content"] = a.Content
	a.fieldMap["sort_id"] = a.SortID
	a.fieldMap["is_top"] = a.IsTop
	a.fieldMap["status"] = a.Status
	a.fieldMap["publish_time"] = a.PublishTime
	a.fieldMap["create_id"] = a.CreateID
	a.fieldMap["create_name"] = a.CreateName
	a.fieldMap["create_time"] = a.CreateTime
	a.fieldMap["update_id"] = a.UpdateID
	a.fieldMap["update_name"] = a.UpdateName
	a.fieldMap["update_time"] = a.UpdateTime
}

func (a adminNotice) clone(db *gorm.DB) adminNotice {
	a.adminNoticeDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a adminNotice) replaceDB(db *gorm.DB) adminNotice {
	a.adminNoticeDo.ReplaceDB(db)
	return a
}

type adminNoticeDo struct{ gen.DO }

func (a adminNoticeDo) Debug() *adminNoticeDo {
	return a.withDO(a.DO.Debug())
}

func (a adminNoticeDo) WithContext(ctx context.Context) *adminNoticeDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a adminNoticeDo) ReadDB() *adminNoticeDo {
	return a.Clauses(dbresolver.Read)
}

func (a adminNoticeDo) WriteDB() *adminNoticeDo {
	return a.Clauses(dbresolver.Write)
}

func (a adminNoticeDo) Session(config *gorm.Session) *adminNoticeDo {
	return a.withDO(a.DO.Session(config))
}

func (a adminNoticeDo) Clauses(conds ...clause.Expression) *adminNoticeDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a adminNoticeDo) Returning(value interface{}, columns ...string) *adminNoticeDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a adminNoticeDo) Not(conds ...gen.Condition) *adminNoticeDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a adminNoticeDo) Or(conds ...gen.Condition) *adminNoticeDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a adminNoticeDo) Select(conds ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a adminNoticeDo) Where(conds ...gen.Condition) *adminNoticeDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a adminNoticeDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *adminNoticeDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a adminNoticeDo) Order(conds ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a adminNoticeDo) Distinct(cols ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a adminNoticeDo) Omit(cols ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a adminNoticeDo) Join(table schema.Tabler, on ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a adminNoticeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a adminNoticeDo) RightJoin(table schema.Tabler, on ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a adminNoticeDo) Group(cols ...field.Expr) *adminNoticeDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a adminNoticeDo) Having(conds ...gen.Condition) *adminNoticeDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a adminNoticeDo) Limit(limit int) *adminNoticeDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a adminNoticeDo) Offset(offset int) *adminNoticeDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a adminNoticeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *adminNoticeDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a adminNoticeDo) Unscoped() *adminNoticeDo {
	return a.withDO(a.DO.Unscoped())
}

func (a adminNoticeDo) Create(values ...*model.AdminNotice) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a adminNoticeDo) CreateInBatches(values []*model.AdminNotice, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a adminNoticeDo) Save(values ...*model.AdminNotice) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a adminNoticeDo) First() (*model.AdminNotice, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminNotice), nil
	}
}

func (a adminNoticeDo) Take() (*model.AdminNotice, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminNotice), nil
	}
}

func (a adminNoticeDo) Last() (*model.AdminNotice, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminNotice), nil
	}
}

func (a adminNoticeDo) Find() ([]*model.AdminNotice, error) {
	result, err := a.DO.Find()
	return result.([]*model.AdminNotice), err
}

func (a adminNoticeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AdminNotice, err error) {
	buf := make([]*model.AdminNotice, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a adminNoticeDo) FindInBatches(result *[]*model.AdminNotice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a adminNoticeDo) Attrs(attrs ...field.AssignExpr) *adminNoticeDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a adminNoticeDo) Assign(attrs ...field.AssignExpr) *adminNoticeDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a adminNoticeDo) Joins(fields ...field.RelationField) *adminNoticeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a adminNoticeDo) Preload(fields ...field.RelationField) *adminNoticeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a adminNoticeDo) FirstOrInit() (*model.AdminNotice, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminNotice), nil
	}
}

func (a adminNoticeDo) FirstOrCreate() (*model.AdminNotice, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AdminNotice), nil
	}
}

func (a adminNoticeDo) FindByPage(offset int, limit int) (result []*model.AdminNotice, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a adminNoticeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a adminNoticeDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a adminNoticeDo) Delete(models ...*model.AdminNotice) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *adminNoticeDo) withDO(do gen.Dao) *adminNoticeDo {
	a.DO = *do.(*gen.DO)
	return a
}
