// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdCategoryRelation(db *gorm.DB, opts ...gen.DOOption) cmsAdCategoryRelation {
	_cmsAdCategoryRelation := cmsAdCategoryRelation{}

	_cmsAdCategoryRelation.cmsAdCategoryRelationDo.UseDB(db, opts...)
	_cmsAdCategoryRelation.cmsAdCategoryRelationDo.UseModel(&model.CmsAdCategoryRelation{})

	tableName := _cmsAdCategoryRelation.cmsAdCategoryRelationDo.TableName()
	_cmsAdCategoryRelation.ALL = field.NewAsterisk(tableName)
	_cmsAdCategoryRelation.RelationID = field.NewInt64(tableName, "relation_id")
	_cmsAdCategoryRelation.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsAdCategoryRelation.AdID = field.NewInt64(tableName, "ad_id")

	_cmsAdCategoryRelation.fillFieldMap()

	return _cmsAdCategoryRelation
}

type cmsAdCategoryRelation struct {
	cmsAdCategoryRelationDo cmsAdCategoryRelationDo

	ALL        field.Asterisk
	RelationID field.Int64 // 主键
	CategoryID field.Int64 // 所属分类
	AdID       field.Int64 // 所属广告

	fieldMap map[string]field.Expr
}

func (c cmsAdCategoryRelation) Table(newTableName string) *cmsAdCategoryRelation {
	c.cmsAdCategoryRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdCategoryRelation) As(alias string) *cmsAdCategoryRelation {
	c.cmsAdCategoryRelationDo.DO = *(c.cmsAdCategoryRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdCategoryRelation) updateTableName(table string) *cmsAdCategoryRelation {
	c.ALL = field.NewAsterisk(table)
	c.RelationID = field.NewInt64(table, "relation_id")
	c.CategoryID = field.NewInt64(table, "category_id")
	c.AdID = field.NewInt64(table, "ad_id")

	c.fillFieldMap()

	return c
}

func (c *cmsAdCategoryRelation) WithContext(ctx context.Context) *cmsAdCategoryRelationDo {
	return c.cmsAdCategoryRelationDo.WithContext(ctx)
}

func (c cmsAdCategoryRelation) TableName() string { return c.cmsAdCategoryRelationDo.TableName() }

func (c cmsAdCategoryRelation) Alias() string { return c.cmsAdCategoryRelationDo.Alias() }

func (c *cmsAdCategoryRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdCategoryRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["relation_id"] = c.RelationID
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["ad_id"] = c.AdID
}

func (c cmsAdCategoryRelation) clone(db *gorm.DB) cmsAdCategoryRelation {
	c.cmsAdCategoryRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdCategoryRelation) replaceDB(db *gorm.DB) cmsAdCategoryRelation {
	c.cmsAdCategoryRelationDo.ReplaceDB(db)
	return c
}

type cmsAdCategoryRelationDo struct{ gen.DO }

func (c cmsAdCategoryRelationDo) Debug() *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdCategoryRelationDo) WithContext(ctx context.Context) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdCategoryRelationDo) ReadDB() *cmsAdCategoryRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdCategoryRelationDo) WriteDB() *cmsAdCategoryRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdCategoryRelationDo) Session(config *gorm.Session) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdCategoryRelationDo) Clauses(conds ...clause.Expression) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdCategoryRelationDo) Returning(value interface{}, columns ...string) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdCategoryRelationDo) Not(conds ...gen.Condition) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdCategoryRelationDo) Or(conds ...gen.Condition) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdCategoryRelationDo) Select(conds ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdCategoryRelationDo) Where(conds ...gen.Condition) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdCategoryRelationDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdCategoryRelationDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdCategoryRelationDo) Order(conds ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdCategoryRelationDo) Distinct(cols ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdCategoryRelationDo) Omit(cols ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdCategoryRelationDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdCategoryRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdCategoryRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdCategoryRelationDo) Group(cols ...field.Expr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdCategoryRelationDo) Having(conds ...gen.Condition) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdCategoryRelationDo) Limit(limit int) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdCategoryRelationDo) Offset(offset int) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdCategoryRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdCategoryRelationDo) Unscoped() *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdCategoryRelationDo) Create(values ...*model.CmsAdCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdCategoryRelationDo) CreateInBatches(values []*model.CmsAdCategoryRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdCategoryRelationDo) Save(values ...*model.CmsAdCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdCategoryRelationDo) First() (*model.CmsAdCategoryRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategoryRelation), nil
	}
}

func (c cmsAdCategoryRelationDo) Take() (*model.CmsAdCategoryRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategoryRelation), nil
	}
}

func (c cmsAdCategoryRelationDo) Last() (*model.CmsAdCategoryRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategoryRelation), nil
	}
}

func (c cmsAdCategoryRelationDo) Find() ([]*model.CmsAdCategoryRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdCategoryRelation), err
}

func (c cmsAdCategoryRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdCategoryRelation, err error) {
	buf := make([]*model.CmsAdCategoryRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdCategoryRelationDo) FindInBatches(result *[]*model.CmsAdCategoryRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdCategoryRelationDo) Attrs(attrs ...field.AssignExpr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdCategoryRelationDo) Assign(attrs ...field.AssignExpr) *cmsAdCategoryRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdCategoryRelationDo) Joins(fields ...field.RelationField) *cmsAdCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdCategoryRelationDo) Preload(fields ...field.RelationField) *cmsAdCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdCategoryRelationDo) FirstOrInit() (*model.CmsAdCategoryRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategoryRelation), nil
	}
}

func (c cmsAdCategoryRelationDo) FirstOrCreate() (*model.CmsAdCategoryRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategoryRelation), nil
	}
}

func (c cmsAdCategoryRelationDo) FindByPage(offset int, limit int) (result []*model.CmsAdCategoryRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdCategoryRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdCategoryRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdCategoryRelationDo) Delete(models ...*model.CmsAdCategoryRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdCategoryRelationDo) withDO(do gen.Dao) *cmsAdCategoryRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
