// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsArticleCategory(db *gorm.DB, opts ...gen.DOOption) cmsArticleCategory {
	_cmsArticleCategory := cmsArticleCategory{}

	_cmsArticleCategory.cmsArticleCategoryDo.UseDB(db, opts...)
	_cmsArticleCategory.cmsArticleCategoryDo.UseModel(&model.CmsArticleCategory{})

	tableName := _cmsArticleCategory.cmsArticleCategoryDo.TableName()
	_cmsArticleCategory.ALL = field.NewAsterisk(tableName)
	_cmsArticleCategory.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsArticleCategory.ParentID = field.NewInt64(tableName, "parent_id")
	_cmsArticleCategory.SiteID = field.NewInt64(tableName, "site_id")
	_cmsArticleCategory.ChannelID = field.NewInt64(tableName, "channel_id")
	_cmsArticleCategory.Title = field.NewString(tableName, "title")
	_cmsArticleCategory.CallIndex = field.NewString(tableName, "call_index")
	_cmsArticleCategory.ClassLayer = field.NewInt32(tableName, "class_layer")
	_cmsArticleCategory.LinkURL = field.NewString(tableName, "link_url")
	_cmsArticleCategory.Target = field.NewString(tableName, "target")
	_cmsArticleCategory.ImgUrl1 = field.NewString(tableName, "img_url1")
	_cmsArticleCategory.ImgUrl2 = field.NewString(tableName, "img_url2")
	_cmsArticleCategory.SeoTitle = field.NewString(tableName, "seo_title")
	_cmsArticleCategory.SeoKeyword = field.NewString(tableName, "seo_keyword")
	_cmsArticleCategory.SeoDescription = field.NewString(tableName, "seo_description")
	_cmsArticleCategory.Content = field.NewString(tableName, "content")
	_cmsArticleCategory.SortID = field.NewInt32(tableName, "sort_id")
	_cmsArticleCategory.IsShow = field.NewBool(tableName, "is_show")
	_cmsArticleCategory.IsSearch = field.NewBool(tableName, "is_search")
	_cmsArticleCategory.IsDeleted = field.NewBool(tableName, "is_deleted")
	_cmsArticleCategory.Status = field.NewInt32(tableName, "status")
	_cmsArticleCategory.TmplCat = field.NewString(tableName, "tmpl_cat")
	_cmsArticleCategory.TmplLst = field.NewString(tableName, "tmpl_lst")
	_cmsArticleCategory.TmplDtl = field.NewString(tableName, "tmpl_dtl")
	_cmsArticleCategory.BelongTo = field.NewString(tableName, "belong_to")
	_cmsArticleCategory.CreateID = field.NewInt32(tableName, "create_id")
	_cmsArticleCategory.CreateName = field.NewString(tableName, "create_name")
	_cmsArticleCategory.CreateTime = field.NewTime(tableName, "create_time")
	_cmsArticleCategory.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsArticleCategory.UpdateName = field.NewString(tableName, "update_name")
	_cmsArticleCategory.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsArticleCategory.fillFieldMap()

	return _cmsArticleCategory
}

type cmsArticleCategory struct {
	cmsArticleCategoryDo cmsArticleCategoryDo

	ALL            field.Asterisk
	CategoryID     field.Int64  // 主键
	ParentID       field.Int64  // 父节点
	SiteID         field.Int64  // 所属站点
	ChannelID      field.Int64  // 所属频道
	Title          field.String // 类别标题
	CallIndex      field.String // 调用别名
	ClassLayer     field.Int32  // 类别深度
	LinkURL        field.String // 外部链接
	Target         field.String // 是否开启浏览器新窗口
	ImgUrl1        field.String // 图片地址
	ImgUrl2        field.String // 图片地址
	SeoTitle       field.String // SEO标题
	SeoKeyword     field.String // SEO关健字
	SeoDescription field.String // SEO描述
	Content        field.String // 内容介绍
	SortID         field.Int32  // 排序
	IsShow         field.Bool   // 是否显示:1显示，0隐藏
	IsSearch       field.Bool   // 允许检索:1允许，0禁止
	IsDeleted      field.Bool   // 删除标识
	Status         field.Int32  // 状态0草稿1提交2审核通过3审核未通过4驳回
	TmplCat        field.String // 栏目模板路径
	TmplLst        field.String // 列表模板路径
	TmplDtl        field.String // 明细模板路径
	BelongTo       field.String // 归属
	CreateID       field.Int32  // 创建人ID
	CreateName     field.String // 创建人姓名
	CreateTime     field.Time   // 创建时间
	UpdateID       field.Int32  // 更新人ID
	UpdateName     field.String // 更新人姓名
	UpdateTime     field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsArticleCategory) Table(newTableName string) *cmsArticleCategory {
	c.cmsArticleCategoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsArticleCategory) As(alias string) *cmsArticleCategory {
	c.cmsArticleCategoryDo.DO = *(c.cmsArticleCategoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsArticleCategory) updateTableName(table string) *cmsArticleCategory {
	c.ALL = field.NewAsterisk(table)
	c.CategoryID = field.NewInt64(table, "category_id")
	c.ParentID = field.NewInt64(table, "parent_id")
	c.SiteID = field.NewInt64(table, "site_id")
	c.ChannelID = field.NewInt64(table, "channel_id")
	c.Title = field.NewString(table, "title")
	c.CallIndex = field.NewString(table, "call_index")
	c.ClassLayer = field.NewInt32(table, "class_layer")
	c.LinkURL = field.NewString(table, "link_url")
	c.Target = field.NewString(table, "target")
	c.ImgUrl1 = field.NewString(table, "img_url1")
	c.ImgUrl2 = field.NewString(table, "img_url2")
	c.SeoTitle = field.NewString(table, "seo_title")
	c.SeoKeyword = field.NewString(table, "seo_keyword")
	c.SeoDescription = field.NewString(table, "seo_description")
	c.Content = field.NewString(table, "content")
	c.SortID = field.NewInt32(table, "sort_id")
	c.IsShow = field.NewBool(table, "is_show")
	c.IsSearch = field.NewBool(table, "is_search")
	c.IsDeleted = field.NewBool(table, "is_deleted")
	c.Status = field.NewInt32(table, "status")
	c.TmplCat = field.NewString(table, "tmpl_cat")
	c.TmplLst = field.NewString(table, "tmpl_lst")
	c.TmplDtl = field.NewString(table, "tmpl_dtl")
	c.BelongTo = field.NewString(table, "belong_to")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsArticleCategory) WithContext(ctx context.Context) *cmsArticleCategoryDo {
	return c.cmsArticleCategoryDo.WithContext(ctx)
}

func (c cmsArticleCategory) TableName() string { return c.cmsArticleCategoryDo.TableName() }

func (c cmsArticleCategory) Alias() string { return c.cmsArticleCategoryDo.Alias() }

func (c cmsArticleCategory) Columns(cols ...field.Expr) gen.Columns {
	return c.cmsArticleCategoryDo.Columns(cols...)
}

func (c *cmsArticleCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsArticleCategory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 30)
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["site_id"] = c.SiteID
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["title"] = c.Title
	c.fieldMap["call_index"] = c.CallIndex
	c.fieldMap["class_layer"] = c.ClassLayer
	c.fieldMap["link_url"] = c.LinkURL
	c.fieldMap["target"] = c.Target
	c.fieldMap["img_url1"] = c.ImgUrl1
	c.fieldMap["img_url2"] = c.ImgUrl2
	c.fieldMap["seo_title"] = c.SeoTitle
	c.fieldMap["seo_keyword"] = c.SeoKeyword
	c.fieldMap["seo_description"] = c.SeoDescription
	c.fieldMap["content"] = c.Content
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["is_show"] = c.IsShow
	c.fieldMap["is_search"] = c.IsSearch
	c.fieldMap["is_deleted"] = c.IsDeleted
	c.fieldMap["status"] = c.Status
	c.fieldMap["tmpl_cat"] = c.TmplCat
	c.fieldMap["tmpl_lst"] = c.TmplLst
	c.fieldMap["tmpl_dtl"] = c.TmplDtl
	c.fieldMap["belong_to"] = c.BelongTo
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsArticleCategory) clone(db *gorm.DB) cmsArticleCategory {
	c.cmsArticleCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsArticleCategory) replaceDB(db *gorm.DB) cmsArticleCategory {
	c.cmsArticleCategoryDo.ReplaceDB(db)
	return c
}

type cmsArticleCategoryDo struct{ gen.DO }

func (c cmsArticleCategoryDo) Debug() *cmsArticleCategoryDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsArticleCategoryDo) WithContext(ctx context.Context) *cmsArticleCategoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsArticleCategoryDo) ReadDB() *cmsArticleCategoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsArticleCategoryDo) WriteDB() *cmsArticleCategoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsArticleCategoryDo) Session(config *gorm.Session) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsArticleCategoryDo) Clauses(conds ...clause.Expression) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsArticleCategoryDo) Returning(value interface{}, columns ...string) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsArticleCategoryDo) Not(conds ...gen.Condition) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsArticleCategoryDo) Or(conds ...gen.Condition) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsArticleCategoryDo) Select(conds ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsArticleCategoryDo) Where(conds ...gen.Condition) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsArticleCategoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsArticleCategoryDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsArticleCategoryDo) Order(conds ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsArticleCategoryDo) Distinct(cols ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsArticleCategoryDo) Omit(cols ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsArticleCategoryDo) Join(table schema.Tabler, on ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsArticleCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsArticleCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsArticleCategoryDo) Group(cols ...field.Expr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsArticleCategoryDo) Having(conds ...gen.Condition) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsArticleCategoryDo) Limit(limit int) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsArticleCategoryDo) Offset(offset int) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsArticleCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsArticleCategoryDo) Unscoped() *cmsArticleCategoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsArticleCategoryDo) Create(values ...*model.CmsArticleCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsArticleCategoryDo) CreateInBatches(values []*model.CmsArticleCategory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsArticleCategoryDo) Save(values ...*model.CmsArticleCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsArticleCategoryDo) First() (*model.CmsArticleCategory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategory), nil
	}
}

func (c cmsArticleCategoryDo) Take() (*model.CmsArticleCategory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategory), nil
	}
}

func (c cmsArticleCategoryDo) Last() (*model.CmsArticleCategory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategory), nil
	}
}

func (c cmsArticleCategoryDo) Find() ([]*model.CmsArticleCategory, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsArticleCategory), err
}

func (c cmsArticleCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsArticleCategory, err error) {
	buf := make([]*model.CmsArticleCategory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsArticleCategoryDo) FindInBatches(result *[]*model.CmsArticleCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsArticleCategoryDo) Attrs(attrs ...field.AssignExpr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsArticleCategoryDo) Assign(attrs ...field.AssignExpr) *cmsArticleCategoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsArticleCategoryDo) Joins(fields ...field.RelationField) *cmsArticleCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsArticleCategoryDo) Preload(fields ...field.RelationField) *cmsArticleCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsArticleCategoryDo) FirstOrInit() (*model.CmsArticleCategory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategory), nil
	}
}

func (c cmsArticleCategoryDo) FirstOrCreate() (*model.CmsArticleCategory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategory), nil
	}
}

func (c cmsArticleCategoryDo) FindByPage(offset int, limit int) (result []*model.CmsArticleCategory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsArticleCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsArticleCategoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsArticleCategoryDo) Delete(models ...*model.CmsArticleCategory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsArticleCategoryDo) withDO(do gen.Dao) *cmsArticleCategoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
