// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdmin(db *gorm.DB, opts ...gen.DOOption) cmsAdmin {
	_cmsAdmin := cmsAdmin{}

	_cmsAdmin.cmsAdminDo.UseDB(db, opts...)
	_cmsAdmin.cmsAdminDo.UseModel(&model.CmsAdmin{})

	tableName := _cmsAdmin.cmsAdminDo.TableName()
	_cmsAdmin.ALL = field.NewAsterisk(tableName)
	_cmsAdmin.UserID = field.NewInt64(tableName, "user_id")
	_cmsAdmin.RealName = field.NewString(tableName, "real_name")
	_cmsAdmin.NickName = field.NewString(tableName, "nick_name")
	_cmsAdmin.IDCard = field.NewString(tableName, "id_card")
	_cmsAdmin.Sex = field.NewInt32(tableName, "sex")
	_cmsAdmin.UserName = field.NewString(tableName, "user_name")
	_cmsAdmin.UserNumber = field.NewString(tableName, "user_number")
	_cmsAdmin.Password = field.NewString(tableName, "password")
	_cmsAdmin.PasswordSalt = field.NewString(tableName, "password_salt")
	_cmsAdmin.PasswordFormat = field.NewInt32(tableName, "password_format")
	_cmsAdmin.Email = field.NewString(tableName, "email")
	_cmsAdmin.Telphone = field.NewString(tableName, "telphone")
	_cmsAdmin.Mobile = field.NewString(tableName, "mobile")
	_cmsAdmin.MobilePin = field.NewString(tableName, "mobile_pin")
	_cmsAdmin.UserType = field.NewInt32(tableName, "user_type")
	_cmsAdmin.Enabled = field.NewBool(tableName, "enabled")
	_cmsAdmin.Remark = field.NewString(tableName, "remark")
	_cmsAdmin.Avatar = field.NewString(tableName, "avatar")
	_cmsAdmin.IsAudit = field.NewInt32(tableName, "is_audit")
	_cmsAdmin.SortID = field.NewInt32(tableName, "sort_id")
	_cmsAdmin.LastIP = field.NewString(tableName, "last_ip")
	_cmsAdmin.LastTime = field.NewString(tableName, "last_time")
	_cmsAdmin.IsDeleted = field.NewBool(tableName, "is_deleted")
	_cmsAdmin.CreateTime = field.NewTime(tableName, "create_time")
	_cmsAdmin.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsAdmin.fillFieldMap()

	return _cmsAdmin
}

type cmsAdmin struct {
	cmsAdminDo cmsAdminDo

	ALL            field.Asterisk
	UserID         field.Int64  // 主键
	RealName       field.String // 姓名
	NickName       field.String // 昵称
	IDCard         field.String // 身份证号
	Sex            field.Int32  // 性别（0 男 1 女）
	UserName       field.String // 用户名(登录名),保持系统唯一
	UserNumber     field.String // 其他唯一特征标识：如教职工的工号或学生的学号
	Password       field.String // 密码
	PasswordSalt   field.String // 密码的Hash值
	PasswordFormat field.Int32  // 密码加密格式 0不加密 1默认加密 2MD5类型
	Email          field.String // 邮箱
	Telphone       field.String // 固话
	Mobile         field.String // 手机号码
	MobilePin      field.String // 手机PIN码
	UserType       field.Int32  // 用户类别(0管理员），根据业务定义其他类型（如1学生2教职工；如1商家2卖家）
	Enabled        field.Bool   // 是否可用:1可用 0禁用
	Remark         field.String // 描述
	Avatar         field.String // 会员头像
	IsAudit        field.Int32  // 启用发布审核
	SortID         field.Int32  // 排序
	LastIP         field.String // 最后登录IP
	LastTime       field.String // 最后登录时间
	IsDeleted      field.Bool   // 删除标识
	CreateTime     field.Time   // 创建时间
	UpdateTime     field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsAdmin) Table(newTableName string) *cmsAdmin {
	c.cmsAdminDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdmin) As(alias string) *cmsAdmin {
	c.cmsAdminDo.DO = *(c.cmsAdminDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdmin) updateTableName(table string) *cmsAdmin {
	c.ALL = field.NewAsterisk(table)
	c.UserID = field.NewInt64(table, "user_id")
	c.RealName = field.NewString(table, "real_name")
	c.NickName = field.NewString(table, "nick_name")
	c.IDCard = field.NewString(table, "id_card")
	c.Sex = field.NewInt32(table, "sex")
	c.UserName = field.NewString(table, "user_name")
	c.UserNumber = field.NewString(table, "user_number")
	c.Password = field.NewString(table, "password")
	c.PasswordSalt = field.NewString(table, "password_salt")
	c.PasswordFormat = field.NewInt32(table, "password_format")
	c.Email = field.NewString(table, "email")
	c.Telphone = field.NewString(table, "telphone")
	c.Mobile = field.NewString(table, "mobile")
	c.MobilePin = field.NewString(table, "mobile_pin")
	c.UserType = field.NewInt32(table, "user_type")
	c.Enabled = field.NewBool(table, "enabled")
	c.Remark = field.NewString(table, "remark")
	c.Avatar = field.NewString(table, "avatar")
	c.IsAudit = field.NewInt32(table, "is_audit")
	c.SortID = field.NewInt32(table, "sort_id")
	c.LastIP = field.NewString(table, "last_ip")
	c.LastTime = field.NewString(table, "last_time")
	c.IsDeleted = field.NewBool(table, "is_deleted")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsAdmin) WithContext(ctx context.Context) *cmsAdminDo { return c.cmsAdminDo.WithContext(ctx) }

func (c cmsAdmin) TableName() string { return c.cmsAdminDo.TableName() }

func (c cmsAdmin) Alias() string { return c.cmsAdminDo.Alias() }

func (c *cmsAdmin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdmin) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 25)
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["real_name"] = c.RealName
	c.fieldMap["nick_name"] = c.NickName
	c.fieldMap["id_card"] = c.IDCard
	c.fieldMap["sex"] = c.Sex
	c.fieldMap["user_name"] = c.UserName
	c.fieldMap["user_number"] = c.UserNumber
	c.fieldMap["password"] = c.Password
	c.fieldMap["password_salt"] = c.PasswordSalt
	c.fieldMap["password_format"] = c.PasswordFormat
	c.fieldMap["email"] = c.Email
	c.fieldMap["telphone"] = c.Telphone
	c.fieldMap["mobile"] = c.Mobile
	c.fieldMap["mobile_pin"] = c.MobilePin
	c.fieldMap["user_type"] = c.UserType
	c.fieldMap["enabled"] = c.Enabled
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["avatar"] = c.Avatar
	c.fieldMap["is_audit"] = c.IsAudit
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["last_ip"] = c.LastIP
	c.fieldMap["last_time"] = c.LastTime
	c.fieldMap["is_deleted"] = c.IsDeleted
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsAdmin) clone(db *gorm.DB) cmsAdmin {
	c.cmsAdminDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdmin) replaceDB(db *gorm.DB) cmsAdmin {
	c.cmsAdminDo.ReplaceDB(db)
	return c
}

type cmsAdminDo struct{ gen.DO }

func (c cmsAdminDo) Debug() *cmsAdminDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdminDo) WithContext(ctx context.Context) *cmsAdminDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdminDo) ReadDB() *cmsAdminDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdminDo) WriteDB() *cmsAdminDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdminDo) Session(config *gorm.Session) *cmsAdminDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdminDo) Clauses(conds ...clause.Expression) *cmsAdminDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdminDo) Returning(value interface{}, columns ...string) *cmsAdminDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdminDo) Not(conds ...gen.Condition) *cmsAdminDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdminDo) Or(conds ...gen.Condition) *cmsAdminDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdminDo) Select(conds ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdminDo) Where(conds ...gen.Condition) *cmsAdminDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdminDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdminDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdminDo) Order(conds ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdminDo) Distinct(cols ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdminDo) Omit(cols ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdminDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdminDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdminDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdminDo) Group(cols ...field.Expr) *cmsAdminDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdminDo) Having(conds ...gen.Condition) *cmsAdminDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdminDo) Limit(limit int) *cmsAdminDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdminDo) Offset(offset int) *cmsAdminDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdminDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdminDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdminDo) Unscoped() *cmsAdminDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdminDo) Create(values ...*model.CmsAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdminDo) CreateInBatches(values []*model.CmsAdmin, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdminDo) Save(values ...*model.CmsAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdminDo) First() (*model.CmsAdmin, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdmin), nil
	}
}

func (c cmsAdminDo) Take() (*model.CmsAdmin, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdmin), nil
	}
}

func (c cmsAdminDo) Last() (*model.CmsAdmin, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdmin), nil
	}
}

func (c cmsAdminDo) Find() ([]*model.CmsAdmin, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdmin), err
}

func (c cmsAdminDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdmin, err error) {
	buf := make([]*model.CmsAdmin, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdminDo) FindInBatches(result *[]*model.CmsAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdminDo) Attrs(attrs ...field.AssignExpr) *cmsAdminDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdminDo) Assign(attrs ...field.AssignExpr) *cmsAdminDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdminDo) Joins(fields ...field.RelationField) *cmsAdminDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdminDo) Preload(fields ...field.RelationField) *cmsAdminDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdminDo) FirstOrInit() (*model.CmsAdmin, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdmin), nil
	}
}

func (c cmsAdminDo) FirstOrCreate() (*model.CmsAdmin, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdmin), nil
	}
}

func (c cmsAdminDo) FindByPage(offset int, limit int) (result []*model.CmsAdmin, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdminDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdminDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdminDo) Delete(models ...*model.CmsAdmin) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdminDo) withDO(do gen.Dao) *cmsAdminDo {
	c.DO = *do.(*gen.DO)
	return c
}
