// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsArticleLabelRelation(db *gorm.DB, opts ...gen.DOOption) cmsArticleLabelRelation {
	_cmsArticleLabelRelation := cmsArticleLabelRelation{}

	_cmsArticleLabelRelation.cmsArticleLabelRelationDo.UseDB(db, opts...)
	_cmsArticleLabelRelation.cmsArticleLabelRelationDo.UseModel(&model.CmsArticleLabelRelation{})

	tableName := _cmsArticleLabelRelation.cmsArticleLabelRelationDo.TableName()
	_cmsArticleLabelRelation.ALL = field.NewAsterisk(tableName)
	_cmsArticleLabelRelation.RelationID = field.NewInt64(tableName, "relation_id")
	_cmsArticleLabelRelation.LabelID = field.NewInt64(tableName, "label_id")
	_cmsArticleLabelRelation.ArticleID = field.NewInt64(tableName, "article_id")

	_cmsArticleLabelRelation.fillFieldMap()

	return _cmsArticleLabelRelation
}

type cmsArticleLabelRelation struct {
	cmsArticleLabelRelationDo cmsArticleLabelRelationDo

	ALL        field.Asterisk
	RelationID field.Int64 // 主键
	LabelID    field.Int64 // 所属标签
	ArticleID  field.Int64 // 所属文章

	fieldMap map[string]field.Expr
}

func (c cmsArticleLabelRelation) Table(newTableName string) *cmsArticleLabelRelation {
	c.cmsArticleLabelRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsArticleLabelRelation) As(alias string) *cmsArticleLabelRelation {
	c.cmsArticleLabelRelationDo.DO = *(c.cmsArticleLabelRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsArticleLabelRelation) updateTableName(table string) *cmsArticleLabelRelation {
	c.ALL = field.NewAsterisk(table)
	c.RelationID = field.NewInt64(table, "relation_id")
	c.LabelID = field.NewInt64(table, "label_id")
	c.ArticleID = field.NewInt64(table, "article_id")

	c.fillFieldMap()

	return c
}

func (c *cmsArticleLabelRelation) WithContext(ctx context.Context) *cmsArticleLabelRelationDo {
	return c.cmsArticleLabelRelationDo.WithContext(ctx)
}

func (c cmsArticleLabelRelation) TableName() string { return c.cmsArticleLabelRelationDo.TableName() }

func (c cmsArticleLabelRelation) Alias() string { return c.cmsArticleLabelRelationDo.Alias() }

func (c cmsArticleLabelRelation) Columns(cols ...field.Expr) gen.Columns {
	return c.cmsArticleLabelRelationDo.Columns(cols...)
}

func (c *cmsArticleLabelRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsArticleLabelRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["relation_id"] = c.RelationID
	c.fieldMap["label_id"] = c.LabelID
	c.fieldMap["article_id"] = c.ArticleID
}

func (c cmsArticleLabelRelation) clone(db *gorm.DB) cmsArticleLabelRelation {
	c.cmsArticleLabelRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsArticleLabelRelation) replaceDB(db *gorm.DB) cmsArticleLabelRelation {
	c.cmsArticleLabelRelationDo.ReplaceDB(db)
	return c
}

type cmsArticleLabelRelationDo struct{ gen.DO }

func (c cmsArticleLabelRelationDo) Debug() *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsArticleLabelRelationDo) WithContext(ctx context.Context) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsArticleLabelRelationDo) ReadDB() *cmsArticleLabelRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsArticleLabelRelationDo) WriteDB() *cmsArticleLabelRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsArticleLabelRelationDo) Session(config *gorm.Session) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsArticleLabelRelationDo) Clauses(conds ...clause.Expression) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsArticleLabelRelationDo) Returning(value interface{}, columns ...string) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsArticleLabelRelationDo) Not(conds ...gen.Condition) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsArticleLabelRelationDo) Or(conds ...gen.Condition) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsArticleLabelRelationDo) Select(conds ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsArticleLabelRelationDo) Where(conds ...gen.Condition) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsArticleLabelRelationDo) Order(conds ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsArticleLabelRelationDo) Distinct(cols ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsArticleLabelRelationDo) Omit(cols ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsArticleLabelRelationDo) Join(table schema.Tabler, on ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsArticleLabelRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsArticleLabelRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsArticleLabelRelationDo) Group(cols ...field.Expr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsArticleLabelRelationDo) Having(conds ...gen.Condition) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsArticleLabelRelationDo) Limit(limit int) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsArticleLabelRelationDo) Offset(offset int) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsArticleLabelRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsArticleLabelRelationDo) Unscoped() *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsArticleLabelRelationDo) Create(values ...*model.CmsArticleLabelRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsArticleLabelRelationDo) CreateInBatches(values []*model.CmsArticleLabelRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsArticleLabelRelationDo) Save(values ...*model.CmsArticleLabelRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsArticleLabelRelationDo) First() (*model.CmsArticleLabelRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleLabelRelation), nil
	}
}

func (c cmsArticleLabelRelationDo) Take() (*model.CmsArticleLabelRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleLabelRelation), nil
	}
}

func (c cmsArticleLabelRelationDo) Last() (*model.CmsArticleLabelRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleLabelRelation), nil
	}
}

func (c cmsArticleLabelRelationDo) Find() ([]*model.CmsArticleLabelRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsArticleLabelRelation), err
}

func (c cmsArticleLabelRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsArticleLabelRelation, err error) {
	buf := make([]*model.CmsArticleLabelRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsArticleLabelRelationDo) FindInBatches(result *[]*model.CmsArticleLabelRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsArticleLabelRelationDo) Attrs(attrs ...field.AssignExpr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsArticleLabelRelationDo) Assign(attrs ...field.AssignExpr) *cmsArticleLabelRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsArticleLabelRelationDo) Joins(fields ...field.RelationField) *cmsArticleLabelRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsArticleLabelRelationDo) Preload(fields ...field.RelationField) *cmsArticleLabelRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsArticleLabelRelationDo) FirstOrInit() (*model.CmsArticleLabelRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleLabelRelation), nil
	}
}

func (c cmsArticleLabelRelationDo) FirstOrCreate() (*model.CmsArticleLabelRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleLabelRelation), nil
	}
}

func (c cmsArticleLabelRelationDo) FindByPage(offset int, limit int) (result []*model.CmsArticleLabelRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsArticleLabelRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsArticleLabelRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsArticleLabelRelationDo) Delete(models ...*model.CmsArticleLabelRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsArticleLabelRelationDo) withDO(do gen.Dao) *cmsArticleLabelRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
