// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsArticleAttach(db *gorm.DB, opts ...gen.DOOption) cmsArticleAttach {
	_cmsArticleAttach := cmsArticleAttach{}

	_cmsArticleAttach.cmsArticleAttachDo.UseDB(db, opts...)
	_cmsArticleAttach.cmsArticleAttachDo.UseModel(&model.CmsArticleAttach{})

	tableName := _cmsArticleAttach.cmsArticleAttachDo.TableName()
	_cmsArticleAttach.ALL = field.NewAsterisk(tableName)
	_cmsArticleAttach.AttachID = field.NewInt64(tableName, "attach_id")
	_cmsArticleAttach.ArticleID = field.NewInt64(tableName, "article_id")
	_cmsArticleAttach.FileName = field.NewString(tableName, "file_name")
	_cmsArticleAttach.FilePath = field.NewString(tableName, "file_path")
	_cmsArticleAttach.FileSize = field.NewInt32(tableName, "file_size")
	_cmsArticleAttach.FileExt = field.NewString(tableName, "file_ext")
	_cmsArticleAttach.Point = field.NewInt32(tableName, "point")
	_cmsArticleAttach.DownCount = field.NewInt32(tableName, "down_count")
	_cmsArticleAttach.SortID = field.NewInt32(tableName, "sort_id")
	_cmsArticleAttach.Remark = field.NewString(tableName, "remark")
	_cmsArticleAttach.CreateTime = field.NewTime(tableName, "create_time")

	_cmsArticleAttach.fillFieldMap()

	return _cmsArticleAttach
}

type cmsArticleAttach struct {
	cmsArticleAttachDo cmsArticleAttachDo

	ALL        field.Asterisk
	AttachID   field.Int64  // 主键
	ArticleID  field.Int64  // 文章ID
	FileName   field.String // 文件名
	FilePath   field.String // 文件路径
	FileSize   field.Int32  // 文件大小(字节)
	FileExt    field.String // 文件扩展名
	Point      field.Int32  // 下载所需积分
	DownCount  field.Int32  // 下载次数
	SortID     field.Int32  // 排序
	Remark     field.String // 附件描述
	CreateTime field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (c cmsArticleAttach) Table(newTableName string) *cmsArticleAttach {
	c.cmsArticleAttachDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsArticleAttach) As(alias string) *cmsArticleAttach {
	c.cmsArticleAttachDo.DO = *(c.cmsArticleAttachDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsArticleAttach) updateTableName(table string) *cmsArticleAttach {
	c.ALL = field.NewAsterisk(table)
	c.AttachID = field.NewInt64(table, "attach_id")
	c.ArticleID = field.NewInt64(table, "article_id")
	c.FileName = field.NewString(table, "file_name")
	c.FilePath = field.NewString(table, "file_path")
	c.FileSize = field.NewInt32(table, "file_size")
	c.FileExt = field.NewString(table, "file_ext")
	c.Point = field.NewInt32(table, "point")
	c.DownCount = field.NewInt32(table, "down_count")
	c.SortID = field.NewInt32(table, "sort_id")
	c.Remark = field.NewString(table, "remark")
	c.CreateTime = field.NewTime(table, "create_time")

	c.fillFieldMap()

	return c
}

func (c *cmsArticleAttach) WithContext(ctx context.Context) *cmsArticleAttachDo {
	return c.cmsArticleAttachDo.WithContext(ctx)
}

func (c cmsArticleAttach) TableName() string { return c.cmsArticleAttachDo.TableName() }

func (c cmsArticleAttach) Alias() string { return c.cmsArticleAttachDo.Alias() }

func (c *cmsArticleAttach) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsArticleAttach) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 11)
	c.fieldMap["attach_id"] = c.AttachID
	c.fieldMap["article_id"] = c.ArticleID
	c.fieldMap["file_name"] = c.FileName
	c.fieldMap["file_path"] = c.FilePath
	c.fieldMap["file_size"] = c.FileSize
	c.fieldMap["file_ext"] = c.FileExt
	c.fieldMap["point"] = c.Point
	c.fieldMap["down_count"] = c.DownCount
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["create_time"] = c.CreateTime
}

func (c cmsArticleAttach) clone(db *gorm.DB) cmsArticleAttach {
	c.cmsArticleAttachDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsArticleAttach) replaceDB(db *gorm.DB) cmsArticleAttach {
	c.cmsArticleAttachDo.ReplaceDB(db)
	return c
}

type cmsArticleAttachDo struct{ gen.DO }

func (c cmsArticleAttachDo) Debug() *cmsArticleAttachDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsArticleAttachDo) WithContext(ctx context.Context) *cmsArticleAttachDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsArticleAttachDo) ReadDB() *cmsArticleAttachDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsArticleAttachDo) WriteDB() *cmsArticleAttachDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsArticleAttachDo) Session(config *gorm.Session) *cmsArticleAttachDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsArticleAttachDo) Clauses(conds ...clause.Expression) *cmsArticleAttachDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsArticleAttachDo) Returning(value interface{}, columns ...string) *cmsArticleAttachDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsArticleAttachDo) Not(conds ...gen.Condition) *cmsArticleAttachDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsArticleAttachDo) Or(conds ...gen.Condition) *cmsArticleAttachDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsArticleAttachDo) Select(conds ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsArticleAttachDo) Where(conds ...gen.Condition) *cmsArticleAttachDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsArticleAttachDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsArticleAttachDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsArticleAttachDo) Order(conds ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsArticleAttachDo) Distinct(cols ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsArticleAttachDo) Omit(cols ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsArticleAttachDo) Join(table schema.Tabler, on ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsArticleAttachDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsArticleAttachDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsArticleAttachDo) Group(cols ...field.Expr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsArticleAttachDo) Having(conds ...gen.Condition) *cmsArticleAttachDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsArticleAttachDo) Limit(limit int) *cmsArticleAttachDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsArticleAttachDo) Offset(offset int) *cmsArticleAttachDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsArticleAttachDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsArticleAttachDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsArticleAttachDo) Unscoped() *cmsArticleAttachDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsArticleAttachDo) Create(values ...*model.CmsArticleAttach) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsArticleAttachDo) CreateInBatches(values []*model.CmsArticleAttach, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsArticleAttachDo) Save(values ...*model.CmsArticleAttach) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsArticleAttachDo) First() (*model.CmsArticleAttach, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAttach), nil
	}
}

func (c cmsArticleAttachDo) Take() (*model.CmsArticleAttach, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAttach), nil
	}
}

func (c cmsArticleAttachDo) Last() (*model.CmsArticleAttach, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAttach), nil
	}
}

func (c cmsArticleAttachDo) Find() ([]*model.CmsArticleAttach, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsArticleAttach), err
}

func (c cmsArticleAttachDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsArticleAttach, err error) {
	buf := make([]*model.CmsArticleAttach, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsArticleAttachDo) FindInBatches(result *[]*model.CmsArticleAttach, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsArticleAttachDo) Attrs(attrs ...field.AssignExpr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsArticleAttachDo) Assign(attrs ...field.AssignExpr) *cmsArticleAttachDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsArticleAttachDo) Joins(fields ...field.RelationField) *cmsArticleAttachDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsArticleAttachDo) Preload(fields ...field.RelationField) *cmsArticleAttachDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsArticleAttachDo) FirstOrInit() (*model.CmsArticleAttach, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAttach), nil
	}
}

func (c cmsArticleAttachDo) FirstOrCreate() (*model.CmsArticleAttach, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAttach), nil
	}
}

func (c cmsArticleAttachDo) FindByPage(offset int, limit int) (result []*model.CmsArticleAttach, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsArticleAttachDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsArticleAttachDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsArticleAttachDo) Delete(models ...*model.CmsArticleAttach) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsArticleAttachDo) withDO(do gen.Dao) *cmsArticleAttachDo {
	c.DO = *do.(*gen.DO)
	return c
}
