// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsLinkCategoryRelation(db *gorm.DB, opts ...gen.DOOption) cmsLinkCategoryRelation {
	_cmsLinkCategoryRelation := cmsLinkCategoryRelation{}

	_cmsLinkCategoryRelation.cmsLinkCategoryRelationDo.UseDB(db, opts...)
	_cmsLinkCategoryRelation.cmsLinkCategoryRelationDo.UseModel(&model.CmsLinkCategoryRelation{})

	tableName := _cmsLinkCategoryRelation.cmsLinkCategoryRelationDo.TableName()
	_cmsLinkCategoryRelation.ALL = field.NewAsterisk(tableName)
	_cmsLinkCategoryRelation.RelationID = field.NewInt64(tableName, "relation_id")
	_cmsLinkCategoryRelation.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsLinkCategoryRelation.LinkID = field.NewInt64(tableName, "link_id")

	_cmsLinkCategoryRelation.fillFieldMap()

	return _cmsLinkCategoryRelation
}

type cmsLinkCategoryRelation struct {
	cmsLinkCategoryRelationDo cmsLinkCategoryRelationDo

	ALL        field.Asterisk
	RelationID field.Int64 // 主键
	CategoryID field.Int64 // 所属分类
	LinkID     field.Int64 // 所属链接

	fieldMap map[string]field.Expr
}

func (c cmsLinkCategoryRelation) Table(newTableName string) *cmsLinkCategoryRelation {
	c.cmsLinkCategoryRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsLinkCategoryRelation) As(alias string) *cmsLinkCategoryRelation {
	c.cmsLinkCategoryRelationDo.DO = *(c.cmsLinkCategoryRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsLinkCategoryRelation) updateTableName(table string) *cmsLinkCategoryRelation {
	c.ALL = field.NewAsterisk(table)
	c.RelationID = field.NewInt64(table, "relation_id")
	c.CategoryID = field.NewInt64(table, "category_id")
	c.LinkID = field.NewInt64(table, "link_id")

	c.fillFieldMap()

	return c
}

func (c *cmsLinkCategoryRelation) WithContext(ctx context.Context) *cmsLinkCategoryRelationDo {
	return c.cmsLinkCategoryRelationDo.WithContext(ctx)
}

func (c cmsLinkCategoryRelation) TableName() string { return c.cmsLinkCategoryRelationDo.TableName() }

func (c cmsLinkCategoryRelation) Alias() string { return c.cmsLinkCategoryRelationDo.Alias() }

func (c cmsLinkCategoryRelation) Columns(cols ...field.Expr) gen.Columns {
	return c.cmsLinkCategoryRelationDo.Columns(cols...)
}

func (c *cmsLinkCategoryRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsLinkCategoryRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["relation_id"] = c.RelationID
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["link_id"] = c.LinkID
}

func (c cmsLinkCategoryRelation) clone(db *gorm.DB) cmsLinkCategoryRelation {
	c.cmsLinkCategoryRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsLinkCategoryRelation) replaceDB(db *gorm.DB) cmsLinkCategoryRelation {
	c.cmsLinkCategoryRelationDo.ReplaceDB(db)
	return c
}

type cmsLinkCategoryRelationDo struct{ gen.DO }

func (c cmsLinkCategoryRelationDo) Debug() *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsLinkCategoryRelationDo) WithContext(ctx context.Context) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsLinkCategoryRelationDo) ReadDB() *cmsLinkCategoryRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsLinkCategoryRelationDo) WriteDB() *cmsLinkCategoryRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsLinkCategoryRelationDo) Session(config *gorm.Session) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsLinkCategoryRelationDo) Clauses(conds ...clause.Expression) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsLinkCategoryRelationDo) Returning(value interface{}, columns ...string) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsLinkCategoryRelationDo) Not(conds ...gen.Condition) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsLinkCategoryRelationDo) Or(conds ...gen.Condition) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsLinkCategoryRelationDo) Select(conds ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsLinkCategoryRelationDo) Where(conds ...gen.Condition) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsLinkCategoryRelationDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsLinkCategoryRelationDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsLinkCategoryRelationDo) Order(conds ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsLinkCategoryRelationDo) Distinct(cols ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsLinkCategoryRelationDo) Omit(cols ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsLinkCategoryRelationDo) Join(table schema.Tabler, on ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsLinkCategoryRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsLinkCategoryRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsLinkCategoryRelationDo) Group(cols ...field.Expr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsLinkCategoryRelationDo) Having(conds ...gen.Condition) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsLinkCategoryRelationDo) Limit(limit int) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsLinkCategoryRelationDo) Offset(offset int) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsLinkCategoryRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsLinkCategoryRelationDo) Unscoped() *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsLinkCategoryRelationDo) Create(values ...*model.CmsLinkCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsLinkCategoryRelationDo) CreateInBatches(values []*model.CmsLinkCategoryRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsLinkCategoryRelationDo) Save(values ...*model.CmsLinkCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsLinkCategoryRelationDo) First() (*model.CmsLinkCategoryRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsLinkCategoryRelation), nil
	}
}

func (c cmsLinkCategoryRelationDo) Take() (*model.CmsLinkCategoryRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsLinkCategoryRelation), nil
	}
}

func (c cmsLinkCategoryRelationDo) Last() (*model.CmsLinkCategoryRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsLinkCategoryRelation), nil
	}
}

func (c cmsLinkCategoryRelationDo) Find() ([]*model.CmsLinkCategoryRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsLinkCategoryRelation), err
}

func (c cmsLinkCategoryRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsLinkCategoryRelation, err error) {
	buf := make([]*model.CmsLinkCategoryRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsLinkCategoryRelationDo) FindInBatches(result *[]*model.CmsLinkCategoryRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsLinkCategoryRelationDo) Attrs(attrs ...field.AssignExpr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsLinkCategoryRelationDo) Assign(attrs ...field.AssignExpr) *cmsLinkCategoryRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsLinkCategoryRelationDo) Joins(fields ...field.RelationField) *cmsLinkCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsLinkCategoryRelationDo) Preload(fields ...field.RelationField) *cmsLinkCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsLinkCategoryRelationDo) FirstOrInit() (*model.CmsLinkCategoryRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsLinkCategoryRelation), nil
	}
}

func (c cmsLinkCategoryRelationDo) FirstOrCreate() (*model.CmsLinkCategoryRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsLinkCategoryRelation), nil
	}
}

func (c cmsLinkCategoryRelationDo) FindByPage(offset int, limit int) (result []*model.CmsLinkCategoryRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsLinkCategoryRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsLinkCategoryRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsLinkCategoryRelationDo) Delete(models ...*model.CmsLinkCategoryRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsLinkCategoryRelationDo) withDO(do gen.Dao) *cmsLinkCategoryRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
