// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdsCategory(db *gorm.DB, opts ...gen.DOOption) cmsAdsCategory {
	_cmsAdsCategory := cmsAdsCategory{}

	_cmsAdsCategory.cmsAdsCategoryDo.UseDB(db, opts...)
	_cmsAdsCategory.cmsAdsCategoryDo.UseModel(&model.CmsAdsCategory{})

	tableName := _cmsAdsCategory.cmsAdsCategoryDo.TableName()
	_cmsAdsCategory.ALL = field.NewAsterisk(tableName)
	_cmsAdsCategory.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsAdsCategory.ParentID = field.NewInt64(tableName, "parent_id")
	_cmsAdsCategory.SiteID = field.NewInt64(tableName, "site_id")
	_cmsAdsCategory.ChannelID = field.NewInt64(tableName, "channel_id")
	_cmsAdsCategory.Title = field.NewString(tableName, "title")
	_cmsAdsCategory.CallIndex = field.NewString(tableName, "call_index")
	_cmsAdsCategory.Remark = field.NewString(tableName, "remark")
	_cmsAdsCategory.SortID = field.NewInt32(tableName, "sort_id")
	_cmsAdsCategory.Template = field.NewString(tableName, "template")
	_cmsAdsCategory.BelongTo = field.NewString(tableName, "belong_to")
	_cmsAdsCategory.CreateID = field.NewInt32(tableName, "create_id")
	_cmsAdsCategory.CreateName = field.NewString(tableName, "create_name")
	_cmsAdsCategory.CreateTime = field.NewTime(tableName, "create_time")
	_cmsAdsCategory.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsAdsCategory.UpdateName = field.NewString(tableName, "update_name")
	_cmsAdsCategory.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsAdsCategory.fillFieldMap()

	return _cmsAdsCategory
}

type cmsAdsCategory struct {
	cmsAdsCategoryDo cmsAdsCategoryDo

	ALL        field.Asterisk
	CategoryID field.Int64  // 主键
	ParentID   field.Int64  // 父节点
	SiteID     field.Int64  // 所属站点
	ChannelID  field.Int64  // 所属频道
	Title      field.String // 类别标题
	CallIndex  field.String // 调用别名
	Remark     field.String // 描述
	SortID     field.Int32  // 排序
	Template   field.String // 模板路径
	BelongTo   field.String // 归属
	CreateID   field.Int32  // 创建人ID
	CreateName field.String // 创建人姓名
	CreateTime field.Time   // 创建时间
	UpdateID   field.Int32  // 更新人ID
	UpdateName field.String // 更新人姓名
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsAdsCategory) Table(newTableName string) *cmsAdsCategory {
	c.cmsAdsCategoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdsCategory) As(alias string) *cmsAdsCategory {
	c.cmsAdsCategoryDo.DO = *(c.cmsAdsCategoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdsCategory) updateTableName(table string) *cmsAdsCategory {
	c.ALL = field.NewAsterisk(table)
	c.CategoryID = field.NewInt64(table, "category_id")
	c.ParentID = field.NewInt64(table, "parent_id")
	c.SiteID = field.NewInt64(table, "site_id")
	c.ChannelID = field.NewInt64(table, "channel_id")
	c.Title = field.NewString(table, "title")
	c.CallIndex = field.NewString(table, "call_index")
	c.Remark = field.NewString(table, "remark")
	c.SortID = field.NewInt32(table, "sort_id")
	c.Template = field.NewString(table, "template")
	c.BelongTo = field.NewString(table, "belong_to")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsAdsCategory) WithContext(ctx context.Context) *cmsAdsCategoryDo {
	return c.cmsAdsCategoryDo.WithContext(ctx)
}

func (c cmsAdsCategory) TableName() string { return c.cmsAdsCategoryDo.TableName() }

func (c cmsAdsCategory) Alias() string { return c.cmsAdsCategoryDo.Alias() }

func (c cmsAdsCategory) Columns(cols ...field.Expr) gen.Columns {
	return c.cmsAdsCategoryDo.Columns(cols...)
}

func (c *cmsAdsCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdsCategory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 16)
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["site_id"] = c.SiteID
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["title"] = c.Title
	c.fieldMap["call_index"] = c.CallIndex
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["template"] = c.Template
	c.fieldMap["belong_to"] = c.BelongTo
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsAdsCategory) clone(db *gorm.DB) cmsAdsCategory {
	c.cmsAdsCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdsCategory) replaceDB(db *gorm.DB) cmsAdsCategory {
	c.cmsAdsCategoryDo.ReplaceDB(db)
	return c
}

type cmsAdsCategoryDo struct{ gen.DO }

func (c cmsAdsCategoryDo) Debug() *cmsAdsCategoryDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdsCategoryDo) WithContext(ctx context.Context) *cmsAdsCategoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdsCategoryDo) ReadDB() *cmsAdsCategoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdsCategoryDo) WriteDB() *cmsAdsCategoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdsCategoryDo) Session(config *gorm.Session) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdsCategoryDo) Clauses(conds ...clause.Expression) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdsCategoryDo) Returning(value interface{}, columns ...string) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdsCategoryDo) Not(conds ...gen.Condition) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdsCategoryDo) Or(conds ...gen.Condition) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdsCategoryDo) Select(conds ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdsCategoryDo) Where(conds ...gen.Condition) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdsCategoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdsCategoryDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdsCategoryDo) Order(conds ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdsCategoryDo) Distinct(cols ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdsCategoryDo) Omit(cols ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdsCategoryDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdsCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdsCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdsCategoryDo) Group(cols ...field.Expr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdsCategoryDo) Having(conds ...gen.Condition) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdsCategoryDo) Limit(limit int) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdsCategoryDo) Offset(offset int) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdsCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdsCategoryDo) Unscoped() *cmsAdsCategoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdsCategoryDo) Create(values ...*model.CmsAdsCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdsCategoryDo) CreateInBatches(values []*model.CmsAdsCategory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdsCategoryDo) Save(values ...*model.CmsAdsCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdsCategoryDo) First() (*model.CmsAdsCategory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategory), nil
	}
}

func (c cmsAdsCategoryDo) Take() (*model.CmsAdsCategory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategory), nil
	}
}

func (c cmsAdsCategoryDo) Last() (*model.CmsAdsCategory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategory), nil
	}
}

func (c cmsAdsCategoryDo) Find() ([]*model.CmsAdsCategory, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdsCategory), err
}

func (c cmsAdsCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdsCategory, err error) {
	buf := make([]*model.CmsAdsCategory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdsCategoryDo) FindInBatches(result *[]*model.CmsAdsCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdsCategoryDo) Attrs(attrs ...field.AssignExpr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdsCategoryDo) Assign(attrs ...field.AssignExpr) *cmsAdsCategoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdsCategoryDo) Joins(fields ...field.RelationField) *cmsAdsCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdsCategoryDo) Preload(fields ...field.RelationField) *cmsAdsCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdsCategoryDo) FirstOrInit() (*model.CmsAdsCategory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategory), nil
	}
}

func (c cmsAdsCategoryDo) FirstOrCreate() (*model.CmsAdsCategory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategory), nil
	}
}

func (c cmsAdsCategoryDo) FindByPage(offset int, limit int) (result []*model.CmsAdsCategory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdsCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdsCategoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdsCategoryDo) Delete(models ...*model.CmsAdsCategory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdsCategoryDo) withDO(do gen.Dao) *cmsAdsCategoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
