// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdminLog(db *gorm.DB, opts ...gen.DOOption) cmsAdminLog {
	_cmsAdminLog := cmsAdminLog{}

	_cmsAdminLog.cmsAdminLogDo.UseDB(db, opts...)
	_cmsAdminLog.cmsAdminLogDo.UseModel(&model.CmsAdminLog{})

	tableName := _cmsAdminLog.cmsAdminLogDo.TableName()
	_cmsAdminLog.ALL = field.NewAsterisk(tableName)
	_cmsAdminLog.LogID = field.NewInt64(tableName, "log_id")
	_cmsAdminLog.UserID = field.NewInt64(tableName, "user_id")
	_cmsAdminLog.UserName = field.NewString(tableName, "user_name")
	_cmsAdminLog.Method = field.NewString(tableName, "method")
	_cmsAdminLog.Path = field.NewString(tableName, "path")
	_cmsAdminLog.Query = field.NewString(tableName, "query")
	_cmsAdminLog.StatusCode = field.NewString(tableName, "status_code")
	_cmsAdminLog.CreateTime = field.NewTime(tableName, "create_time")

	_cmsAdminLog.fillFieldMap()

	return _cmsAdminLog
}

type cmsAdminLog struct {
	cmsAdminLogDo cmsAdminLogDo

	ALL        field.Asterisk
	LogID      field.Int64  // 主键
	UserID     field.Int64  // 用户id
	UserName   field.String // 账号
	Method     field.String // 请求方法
	Path       field.String // 请求路径
	Query      field.String // 请求参数
	StatusCode field.String // 响应状态码
	CreateTime field.Time   // 记录时间

	fieldMap map[string]field.Expr
}

func (c cmsAdminLog) Table(newTableName string) *cmsAdminLog {
	c.cmsAdminLogDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdminLog) As(alias string) *cmsAdminLog {
	c.cmsAdminLogDo.DO = *(c.cmsAdminLogDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdminLog) updateTableName(table string) *cmsAdminLog {
	c.ALL = field.NewAsterisk(table)
	c.LogID = field.NewInt64(table, "log_id")
	c.UserID = field.NewInt64(table, "user_id")
	c.UserName = field.NewString(table, "user_name")
	c.Method = field.NewString(table, "method")
	c.Path = field.NewString(table, "path")
	c.Query = field.NewString(table, "query")
	c.StatusCode = field.NewString(table, "status_code")
	c.CreateTime = field.NewTime(table, "create_time")

	c.fillFieldMap()

	return c
}

func (c *cmsAdminLog) WithContext(ctx context.Context) *cmsAdminLogDo {
	return c.cmsAdminLogDo.WithContext(ctx)
}

func (c cmsAdminLog) TableName() string { return c.cmsAdminLogDo.TableName() }

func (c cmsAdminLog) Alias() string { return c.cmsAdminLogDo.Alias() }

func (c *cmsAdminLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdminLog) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["log_id"] = c.LogID
	c.fieldMap["user_id"] = c.UserID
	c.fieldMap["user_name"] = c.UserName
	c.fieldMap["method"] = c.Method
	c.fieldMap["path"] = c.Path
	c.fieldMap["query"] = c.Query
	c.fieldMap["status_code"] = c.StatusCode
	c.fieldMap["create_time"] = c.CreateTime
}

func (c cmsAdminLog) clone(db *gorm.DB) cmsAdminLog {
	c.cmsAdminLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdminLog) replaceDB(db *gorm.DB) cmsAdminLog {
	c.cmsAdminLogDo.ReplaceDB(db)
	return c
}

type cmsAdminLogDo struct{ gen.DO }

func (c cmsAdminLogDo) Debug() *cmsAdminLogDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdminLogDo) WithContext(ctx context.Context) *cmsAdminLogDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdminLogDo) ReadDB() *cmsAdminLogDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdminLogDo) WriteDB() *cmsAdminLogDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdminLogDo) Session(config *gorm.Session) *cmsAdminLogDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdminLogDo) Clauses(conds ...clause.Expression) *cmsAdminLogDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdminLogDo) Returning(value interface{}, columns ...string) *cmsAdminLogDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdminLogDo) Not(conds ...gen.Condition) *cmsAdminLogDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdminLogDo) Or(conds ...gen.Condition) *cmsAdminLogDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdminLogDo) Select(conds ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdminLogDo) Where(conds ...gen.Condition) *cmsAdminLogDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdminLogDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdminLogDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdminLogDo) Order(conds ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdminLogDo) Distinct(cols ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdminLogDo) Omit(cols ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdminLogDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdminLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdminLogDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdminLogDo) Group(cols ...field.Expr) *cmsAdminLogDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdminLogDo) Having(conds ...gen.Condition) *cmsAdminLogDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdminLogDo) Limit(limit int) *cmsAdminLogDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdminLogDo) Offset(offset int) *cmsAdminLogDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdminLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdminLogDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdminLogDo) Unscoped() *cmsAdminLogDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdminLogDo) Create(values ...*model.CmsAdminLog) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdminLogDo) CreateInBatches(values []*model.CmsAdminLog, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdminLogDo) Save(values ...*model.CmsAdminLog) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdminLogDo) First() (*model.CmsAdminLog, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminLog), nil
	}
}

func (c cmsAdminLogDo) Take() (*model.CmsAdminLog, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminLog), nil
	}
}

func (c cmsAdminLogDo) Last() (*model.CmsAdminLog, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminLog), nil
	}
}

func (c cmsAdminLogDo) Find() ([]*model.CmsAdminLog, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdminLog), err
}

func (c cmsAdminLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdminLog, err error) {
	buf := make([]*model.CmsAdminLog, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdminLogDo) FindInBatches(result *[]*model.CmsAdminLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdminLogDo) Attrs(attrs ...field.AssignExpr) *cmsAdminLogDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdminLogDo) Assign(attrs ...field.AssignExpr) *cmsAdminLogDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdminLogDo) Joins(fields ...field.RelationField) *cmsAdminLogDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdminLogDo) Preload(fields ...field.RelationField) *cmsAdminLogDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdminLogDo) FirstOrInit() (*model.CmsAdminLog, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminLog), nil
	}
}

func (c cmsAdminLogDo) FirstOrCreate() (*model.CmsAdminLog, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminLog), nil
	}
}

func (c cmsAdminLogDo) FindByPage(offset int, limit int) (result []*model.CmsAdminLog, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdminLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdminLogDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdminLogDo) Delete(models ...*model.CmsAdminLog) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdminLogDo) withDO(do gen.Dao) *cmsAdminLogDo {
	c.DO = *do.(*gen.DO)
	return c
}
