// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdminRoleSite(db *gorm.DB, opts ...gen.DOOption) cmsAdminRoleSite {
	_cmsAdminRoleSite := cmsAdminRoleSite{}

	_cmsAdminRoleSite.cmsAdminRoleSiteDo.UseDB(db, opts...)
	_cmsAdminRoleSite.cmsAdminRoleSiteDo.UseModel(&model.CmsAdminRoleSite{})

	tableName := _cmsAdminRoleSite.cmsAdminRoleSiteDo.TableName()
	_cmsAdminRoleSite.ALL = field.NewAsterisk(tableName)
	_cmsAdminRoleSite.ValueID = field.NewInt64(tableName, "value_id")
	_cmsAdminRoleSite.RoleID = field.NewInt64(tableName, "role_id")
	_cmsAdminRoleSite.SiteID = field.NewInt64(tableName, "site_id")

	_cmsAdminRoleSite.fillFieldMap()

	return _cmsAdminRoleSite
}

type cmsAdminRoleSite struct {
	cmsAdminRoleSiteDo cmsAdminRoleSiteDo

	ALL     field.Asterisk
	ValueID field.Int64 // 主键
	RoleID  field.Int64 // 角色
	SiteID  field.Int64 // 站点

	fieldMap map[string]field.Expr
}

func (c cmsAdminRoleSite) Table(newTableName string) *cmsAdminRoleSite {
	c.cmsAdminRoleSiteDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdminRoleSite) As(alias string) *cmsAdminRoleSite {
	c.cmsAdminRoleSiteDo.DO = *(c.cmsAdminRoleSiteDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdminRoleSite) updateTableName(table string) *cmsAdminRoleSite {
	c.ALL = field.NewAsterisk(table)
	c.ValueID = field.NewInt64(table, "value_id")
	c.RoleID = field.NewInt64(table, "role_id")
	c.SiteID = field.NewInt64(table, "site_id")

	c.fillFieldMap()

	return c
}

func (c *cmsAdminRoleSite) WithContext(ctx context.Context) *cmsAdminRoleSiteDo {
	return c.cmsAdminRoleSiteDo.WithContext(ctx)
}

func (c cmsAdminRoleSite) TableName() string { return c.cmsAdminRoleSiteDo.TableName() }

func (c cmsAdminRoleSite) Alias() string { return c.cmsAdminRoleSiteDo.Alias() }

func (c cmsAdminRoleSite) Columns(cols ...field.Expr) gen.Columns {
	return c.cmsAdminRoleSiteDo.Columns(cols...)
}

func (c *cmsAdminRoleSite) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdminRoleSite) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["value_id"] = c.ValueID
	c.fieldMap["role_id"] = c.RoleID
	c.fieldMap["site_id"] = c.SiteID
}

func (c cmsAdminRoleSite) clone(db *gorm.DB) cmsAdminRoleSite {
	c.cmsAdminRoleSiteDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdminRoleSite) replaceDB(db *gorm.DB) cmsAdminRoleSite {
	c.cmsAdminRoleSiteDo.ReplaceDB(db)
	return c
}

type cmsAdminRoleSiteDo struct{ gen.DO }

func (c cmsAdminRoleSiteDo) Debug() *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdminRoleSiteDo) WithContext(ctx context.Context) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdminRoleSiteDo) ReadDB() *cmsAdminRoleSiteDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdminRoleSiteDo) WriteDB() *cmsAdminRoleSiteDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdminRoleSiteDo) Session(config *gorm.Session) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdminRoleSiteDo) Clauses(conds ...clause.Expression) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdminRoleSiteDo) Returning(value interface{}, columns ...string) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdminRoleSiteDo) Not(conds ...gen.Condition) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdminRoleSiteDo) Or(conds ...gen.Condition) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdminRoleSiteDo) Select(conds ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdminRoleSiteDo) Where(conds ...gen.Condition) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdminRoleSiteDo) Order(conds ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdminRoleSiteDo) Distinct(cols ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdminRoleSiteDo) Omit(cols ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdminRoleSiteDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdminRoleSiteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdminRoleSiteDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdminRoleSiteDo) Group(cols ...field.Expr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdminRoleSiteDo) Having(conds ...gen.Condition) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdminRoleSiteDo) Limit(limit int) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdminRoleSiteDo) Offset(offset int) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdminRoleSiteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdminRoleSiteDo) Unscoped() *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdminRoleSiteDo) Create(values ...*model.CmsAdminRoleSite) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdminRoleSiteDo) CreateInBatches(values []*model.CmsAdminRoleSite, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdminRoleSiteDo) Save(values ...*model.CmsAdminRoleSite) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdminRoleSiteDo) First() (*model.CmsAdminRoleSite, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminRoleSite), nil
	}
}

func (c cmsAdminRoleSiteDo) Take() (*model.CmsAdminRoleSite, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminRoleSite), nil
	}
}

func (c cmsAdminRoleSiteDo) Last() (*model.CmsAdminRoleSite, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminRoleSite), nil
	}
}

func (c cmsAdminRoleSiteDo) Find() ([]*model.CmsAdminRoleSite, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdminRoleSite), err
}

func (c cmsAdminRoleSiteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdminRoleSite, err error) {
	buf := make([]*model.CmsAdminRoleSite, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdminRoleSiteDo) FindInBatches(result *[]*model.CmsAdminRoleSite, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdminRoleSiteDo) Attrs(attrs ...field.AssignExpr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdminRoleSiteDo) Assign(attrs ...field.AssignExpr) *cmsAdminRoleSiteDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdminRoleSiteDo) Joins(fields ...field.RelationField) *cmsAdminRoleSiteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdminRoleSiteDo) Preload(fields ...field.RelationField) *cmsAdminRoleSiteDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdminRoleSiteDo) FirstOrInit() (*model.CmsAdminRoleSite, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminRoleSite), nil
	}
}

func (c cmsAdminRoleSiteDo) FirstOrCreate() (*model.CmsAdminRoleSite, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdminRoleSite), nil
	}
}

func (c cmsAdminRoleSiteDo) FindByPage(offset int, limit int) (result []*model.CmsAdminRoleSite, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdminRoleSiteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdminRoleSiteDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdminRoleSiteDo) Delete(models ...*model.CmsAdminRoleSite) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdminRoleSiteDo) withDO(do gen.Dao) *cmsAdminRoleSiteDo {
	c.DO = *do.(*gen.DO)
	return c
}
