// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsArticleAlbum(db *gorm.DB, opts ...gen.DOOption) cmsArticleAlbum {
	_cmsArticleAlbum := cmsArticleAlbum{}

	_cmsArticleAlbum.cmsArticleAlbumDo.UseDB(db, opts...)
	_cmsArticleAlbum.cmsArticleAlbumDo.UseModel(&model.CmsArticleAlbum{})

	tableName := _cmsArticleAlbum.cmsArticleAlbumDo.TableName()
	_cmsArticleAlbum.ALL = field.NewAsterisk(tableName)
	_cmsArticleAlbum.AlbumID = field.NewInt64(tableName, "album_id")
	_cmsArticleAlbum.ArticleID = field.NewInt64(tableName, "article_id")
	_cmsArticleAlbum.Title = field.NewString(tableName, "title")
	_cmsArticleAlbum.ThumbPath = field.NewString(tableName, "thumb_path")
	_cmsArticleAlbum.OriginalPath = field.NewString(tableName, "original_path")
	_cmsArticleAlbum.FileSize = field.NewInt64(tableName, "file_size")
	_cmsArticleAlbum.FileExt = field.NewString(tableName, "file_ext")
	_cmsArticleAlbum.LinkURL = field.NewString(tableName, "link_url")
	_cmsArticleAlbum.Click = field.NewInt32(tableName, "click")
	_cmsArticleAlbum.SortID = field.NewInt32(tableName, "sort_id")
	_cmsArticleAlbum.IsShow = field.NewInt32(tableName, "is_show")
	_cmsArticleAlbum.Remark = field.NewString(tableName, "remark")
	_cmsArticleAlbum.CreateID = field.NewInt32(tableName, "create_id")
	_cmsArticleAlbum.CreateName = field.NewString(tableName, "create_name")
	_cmsArticleAlbum.CreateTime = field.NewTime(tableName, "create_time")
	_cmsArticleAlbum.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsArticleAlbum.UpdateName = field.NewString(tableName, "update_name")
	_cmsArticleAlbum.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsArticleAlbum.fillFieldMap()

	return _cmsArticleAlbum
}

type cmsArticleAlbum struct {
	cmsArticleAlbumDo cmsArticleAlbumDo

	ALL          field.Asterisk
	AlbumID      field.Int64  // 主键
	ArticleID    field.Int64  // 文章ID
	Title        field.String // 标题
	ThumbPath    field.String // 缩略图地址
	OriginalPath field.String // 原图地址
	FileSize     field.Int64  // 文件大小(字节)
	FileExt      field.String // 文件扩展名
	LinkURL      field.String // 外部链接
	Click        field.Int32  // 点击次数
	SortID       field.Int32  // 排序
	IsShow       field.Int32  // 是否显示：1显示2隐藏
	Remark       field.String // 图片描述
	CreateID     field.Int32  // 创建人ID
	CreateName   field.String // 创建人姓名
	CreateTime   field.Time   // 创建时间
	UpdateID     field.Int32  // 更新人ID
	UpdateName   field.String // 更新人姓名
	UpdateTime   field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsArticleAlbum) Table(newTableName string) *cmsArticleAlbum {
	c.cmsArticleAlbumDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsArticleAlbum) As(alias string) *cmsArticleAlbum {
	c.cmsArticleAlbumDo.DO = *(c.cmsArticleAlbumDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsArticleAlbum) updateTableName(table string) *cmsArticleAlbum {
	c.ALL = field.NewAsterisk(table)
	c.AlbumID = field.NewInt64(table, "album_id")
	c.ArticleID = field.NewInt64(table, "article_id")
	c.Title = field.NewString(table, "title")
	c.ThumbPath = field.NewString(table, "thumb_path")
	c.OriginalPath = field.NewString(table, "original_path")
	c.FileSize = field.NewInt64(table, "file_size")
	c.FileExt = field.NewString(table, "file_ext")
	c.LinkURL = field.NewString(table, "link_url")
	c.Click = field.NewInt32(table, "click")
	c.SortID = field.NewInt32(table, "sort_id")
	c.IsShow = field.NewInt32(table, "is_show")
	c.Remark = field.NewString(table, "remark")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsArticleAlbum) WithContext(ctx context.Context) *cmsArticleAlbumDo {
	return c.cmsArticleAlbumDo.WithContext(ctx)
}

func (c cmsArticleAlbum) TableName() string { return c.cmsArticleAlbumDo.TableName() }

func (c cmsArticleAlbum) Alias() string { return c.cmsArticleAlbumDo.Alias() }

func (c *cmsArticleAlbum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsArticleAlbum) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 18)
	c.fieldMap["album_id"] = c.AlbumID
	c.fieldMap["article_id"] = c.ArticleID
	c.fieldMap["title"] = c.Title
	c.fieldMap["thumb_path"] = c.ThumbPath
	c.fieldMap["original_path"] = c.OriginalPath
	c.fieldMap["file_size"] = c.FileSize
	c.fieldMap["file_ext"] = c.FileExt
	c.fieldMap["link_url"] = c.LinkURL
	c.fieldMap["click"] = c.Click
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["is_show"] = c.IsShow
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsArticleAlbum) clone(db *gorm.DB) cmsArticleAlbum {
	c.cmsArticleAlbumDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsArticleAlbum) replaceDB(db *gorm.DB) cmsArticleAlbum {
	c.cmsArticleAlbumDo.ReplaceDB(db)
	return c
}

type cmsArticleAlbumDo struct{ gen.DO }

func (c cmsArticleAlbumDo) Debug() *cmsArticleAlbumDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsArticleAlbumDo) WithContext(ctx context.Context) *cmsArticleAlbumDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsArticleAlbumDo) ReadDB() *cmsArticleAlbumDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsArticleAlbumDo) WriteDB() *cmsArticleAlbumDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsArticleAlbumDo) Session(config *gorm.Session) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsArticleAlbumDo) Clauses(conds ...clause.Expression) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsArticleAlbumDo) Returning(value interface{}, columns ...string) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsArticleAlbumDo) Not(conds ...gen.Condition) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsArticleAlbumDo) Or(conds ...gen.Condition) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsArticleAlbumDo) Select(conds ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsArticleAlbumDo) Where(conds ...gen.Condition) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsArticleAlbumDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsArticleAlbumDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsArticleAlbumDo) Order(conds ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsArticleAlbumDo) Distinct(cols ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsArticleAlbumDo) Omit(cols ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsArticleAlbumDo) Join(table schema.Tabler, on ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsArticleAlbumDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsArticleAlbumDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsArticleAlbumDo) Group(cols ...field.Expr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsArticleAlbumDo) Having(conds ...gen.Condition) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsArticleAlbumDo) Limit(limit int) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsArticleAlbumDo) Offset(offset int) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsArticleAlbumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsArticleAlbumDo) Unscoped() *cmsArticleAlbumDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsArticleAlbumDo) Create(values ...*model.CmsArticleAlbum) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsArticleAlbumDo) CreateInBatches(values []*model.CmsArticleAlbum, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsArticleAlbumDo) Save(values ...*model.CmsArticleAlbum) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsArticleAlbumDo) First() (*model.CmsArticleAlbum, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAlbum), nil
	}
}

func (c cmsArticleAlbumDo) Take() (*model.CmsArticleAlbum, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAlbum), nil
	}
}

func (c cmsArticleAlbumDo) Last() (*model.CmsArticleAlbum, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAlbum), nil
	}
}

func (c cmsArticleAlbumDo) Find() ([]*model.CmsArticleAlbum, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsArticleAlbum), err
}

func (c cmsArticleAlbumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsArticleAlbum, err error) {
	buf := make([]*model.CmsArticleAlbum, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsArticleAlbumDo) FindInBatches(result *[]*model.CmsArticleAlbum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsArticleAlbumDo) Attrs(attrs ...field.AssignExpr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsArticleAlbumDo) Assign(attrs ...field.AssignExpr) *cmsArticleAlbumDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsArticleAlbumDo) Joins(fields ...field.RelationField) *cmsArticleAlbumDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsArticleAlbumDo) Preload(fields ...field.RelationField) *cmsArticleAlbumDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsArticleAlbumDo) FirstOrInit() (*model.CmsArticleAlbum, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAlbum), nil
	}
}

func (c cmsArticleAlbumDo) FirstOrCreate() (*model.CmsArticleAlbum, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleAlbum), nil
	}
}

func (c cmsArticleAlbumDo) FindByPage(offset int, limit int) (result []*model.CmsArticleAlbum, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsArticleAlbumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsArticleAlbumDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsArticleAlbumDo) Delete(models ...*model.CmsArticleAlbum) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsArticleAlbumDo) withDO(do gen.Dao) *cmsArticleAlbumDo {
	c.DO = *do.(*gen.DO)
	return c
}
