// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsArticleCategoryRelation(db *gorm.DB, opts ...gen.DOOption) cmsArticleCategoryRelation {
	_cmsArticleCategoryRelation := cmsArticleCategoryRelation{}

	_cmsArticleCategoryRelation.cmsArticleCategoryRelationDo.UseDB(db, opts...)
	_cmsArticleCategoryRelation.cmsArticleCategoryRelationDo.UseModel(&model.CmsArticleCategoryRelation{})

	tableName := _cmsArticleCategoryRelation.cmsArticleCategoryRelationDo.TableName()
	_cmsArticleCategoryRelation.ALL = field.NewAsterisk(tableName)
	_cmsArticleCategoryRelation.RelationID = field.NewInt64(tableName, "relation_id")
	_cmsArticleCategoryRelation.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsArticleCategoryRelation.ArticleID = field.NewInt64(tableName, "article_id")

	_cmsArticleCategoryRelation.fillFieldMap()

	return _cmsArticleCategoryRelation
}

type cmsArticleCategoryRelation struct {
	cmsArticleCategoryRelationDo cmsArticleCategoryRelationDo

	ALL        field.Asterisk
	RelationID field.Int64 // 主键
	CategoryID field.Int64 // 所属分类
	ArticleID  field.Int64 // 所属文章

	fieldMap map[string]field.Expr
}

func (c cmsArticleCategoryRelation) Table(newTableName string) *cmsArticleCategoryRelation {
	c.cmsArticleCategoryRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsArticleCategoryRelation) As(alias string) *cmsArticleCategoryRelation {
	c.cmsArticleCategoryRelationDo.DO = *(c.cmsArticleCategoryRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsArticleCategoryRelation) updateTableName(table string) *cmsArticleCategoryRelation {
	c.ALL = field.NewAsterisk(table)
	c.RelationID = field.NewInt64(table, "relation_id")
	c.CategoryID = field.NewInt64(table, "category_id")
	c.ArticleID = field.NewInt64(table, "article_id")

	c.fillFieldMap()

	return c
}

func (c *cmsArticleCategoryRelation) WithContext(ctx context.Context) *cmsArticleCategoryRelationDo {
	return c.cmsArticleCategoryRelationDo.WithContext(ctx)
}

func (c cmsArticleCategoryRelation) TableName() string {
	return c.cmsArticleCategoryRelationDo.TableName()
}

func (c cmsArticleCategoryRelation) Alias() string { return c.cmsArticleCategoryRelationDo.Alias() }

func (c *cmsArticleCategoryRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsArticleCategoryRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["relation_id"] = c.RelationID
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["article_id"] = c.ArticleID
}

func (c cmsArticleCategoryRelation) clone(db *gorm.DB) cmsArticleCategoryRelation {
	c.cmsArticleCategoryRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsArticleCategoryRelation) replaceDB(db *gorm.DB) cmsArticleCategoryRelation {
	c.cmsArticleCategoryRelationDo.ReplaceDB(db)
	return c
}

type cmsArticleCategoryRelationDo struct{ gen.DO }

func (c cmsArticleCategoryRelationDo) Debug() *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsArticleCategoryRelationDo) WithContext(ctx context.Context) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsArticleCategoryRelationDo) ReadDB() *cmsArticleCategoryRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsArticleCategoryRelationDo) WriteDB() *cmsArticleCategoryRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsArticleCategoryRelationDo) Session(config *gorm.Session) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsArticleCategoryRelationDo) Clauses(conds ...clause.Expression) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsArticleCategoryRelationDo) Returning(value interface{}, columns ...string) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsArticleCategoryRelationDo) Not(conds ...gen.Condition) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsArticleCategoryRelationDo) Or(conds ...gen.Condition) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsArticleCategoryRelationDo) Select(conds ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsArticleCategoryRelationDo) Where(conds ...gen.Condition) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsArticleCategoryRelationDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsArticleCategoryRelationDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsArticleCategoryRelationDo) Order(conds ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsArticleCategoryRelationDo) Distinct(cols ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsArticleCategoryRelationDo) Omit(cols ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsArticleCategoryRelationDo) Join(table schema.Tabler, on ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsArticleCategoryRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsArticleCategoryRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsArticleCategoryRelationDo) Group(cols ...field.Expr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsArticleCategoryRelationDo) Having(conds ...gen.Condition) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsArticleCategoryRelationDo) Limit(limit int) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsArticleCategoryRelationDo) Offset(offset int) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsArticleCategoryRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsArticleCategoryRelationDo) Unscoped() *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsArticleCategoryRelationDo) Create(values ...*model.CmsArticleCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsArticleCategoryRelationDo) CreateInBatches(values []*model.CmsArticleCategoryRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsArticleCategoryRelationDo) Save(values ...*model.CmsArticleCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsArticleCategoryRelationDo) First() (*model.CmsArticleCategoryRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategoryRelation), nil
	}
}

func (c cmsArticleCategoryRelationDo) Take() (*model.CmsArticleCategoryRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategoryRelation), nil
	}
}

func (c cmsArticleCategoryRelationDo) Last() (*model.CmsArticleCategoryRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategoryRelation), nil
	}
}

func (c cmsArticleCategoryRelationDo) Find() ([]*model.CmsArticleCategoryRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsArticleCategoryRelation), err
}

func (c cmsArticleCategoryRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsArticleCategoryRelation, err error) {
	buf := make([]*model.CmsArticleCategoryRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsArticleCategoryRelationDo) FindInBatches(result *[]*model.CmsArticleCategoryRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsArticleCategoryRelationDo) Attrs(attrs ...field.AssignExpr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsArticleCategoryRelationDo) Assign(attrs ...field.AssignExpr) *cmsArticleCategoryRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsArticleCategoryRelationDo) Joins(fields ...field.RelationField) *cmsArticleCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsArticleCategoryRelationDo) Preload(fields ...field.RelationField) *cmsArticleCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsArticleCategoryRelationDo) FirstOrInit() (*model.CmsArticleCategoryRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategoryRelation), nil
	}
}

func (c cmsArticleCategoryRelationDo) FirstOrCreate() (*model.CmsArticleCategoryRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsArticleCategoryRelation), nil
	}
}

func (c cmsArticleCategoryRelationDo) FindByPage(offset int, limit int) (result []*model.CmsArticleCategoryRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsArticleCategoryRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsArticleCategoryRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsArticleCategoryRelationDo) Delete(models ...*model.CmsArticleCategoryRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsArticleCategoryRelationDo) withDO(do gen.Dao) *cmsArticleCategoryRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
