// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdCategory(db *gorm.DB, opts ...gen.DOOption) cmsAdCategory {
	_cmsAdCategory := cmsAdCategory{}

	_cmsAdCategory.cmsAdCategoryDo.UseDB(db, opts...)
	_cmsAdCategory.cmsAdCategoryDo.UseModel(&model.CmsAdCategory{})

	tableName := _cmsAdCategory.cmsAdCategoryDo.TableName()
	_cmsAdCategory.ALL = field.NewAsterisk(tableName)
	_cmsAdCategory.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsAdCategory.ParentID = field.NewInt64(tableName, "parent_id")
	_cmsAdCategory.SiteID = field.NewInt64(tableName, "site_id")
	_cmsAdCategory.ChannelID = field.NewInt64(tableName, "channel_id")
	_cmsAdCategory.Title = field.NewString(tableName, "title")
	_cmsAdCategory.CallIndex = field.NewString(tableName, "call_index")
	_cmsAdCategory.Remark = field.NewString(tableName, "remark")
	_cmsAdCategory.SortID = field.NewInt32(tableName, "sort_id")
	_cmsAdCategory.BelongTo = field.NewString(tableName, "belong_to")
	_cmsAdCategory.CreateID = field.NewInt32(tableName, "create_id")
	_cmsAdCategory.CreateName = field.NewString(tableName, "create_name")
	_cmsAdCategory.CreateTime = field.NewTime(tableName, "create_time")
	_cmsAdCategory.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsAdCategory.UpdateName = field.NewString(tableName, "update_name")
	_cmsAdCategory.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsAdCategory.fillFieldMap()

	return _cmsAdCategory
}

type cmsAdCategory struct {
	cmsAdCategoryDo cmsAdCategoryDo

	ALL        field.Asterisk
	CategoryID field.Int64  // 主键
	ParentID   field.Int64  // 父节点
	SiteID     field.Int64  // 所属站点
	ChannelID  field.Int64  // 所属频道
	Title      field.String // 类别标题
	CallIndex  field.String // 调用别名
	Remark     field.String // 描述
	SortID     field.Int32  // 排序
	BelongTo   field.String // 归属
	CreateID   field.Int32  // 创建人ID
	CreateName field.String // 创建人姓名
	CreateTime field.Time   // 创建时间
	UpdateID   field.Int32  // 更新人ID
	UpdateName field.String // 更新人姓名
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsAdCategory) Table(newTableName string) *cmsAdCategory {
	c.cmsAdCategoryDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdCategory) As(alias string) *cmsAdCategory {
	c.cmsAdCategoryDo.DO = *(c.cmsAdCategoryDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdCategory) updateTableName(table string) *cmsAdCategory {
	c.ALL = field.NewAsterisk(table)
	c.CategoryID = field.NewInt64(table, "category_id")
	c.ParentID = field.NewInt64(table, "parent_id")
	c.SiteID = field.NewInt64(table, "site_id")
	c.ChannelID = field.NewInt64(table, "channel_id")
	c.Title = field.NewString(table, "title")
	c.CallIndex = field.NewString(table, "call_index")
	c.Remark = field.NewString(table, "remark")
	c.SortID = field.NewInt32(table, "sort_id")
	c.BelongTo = field.NewString(table, "belong_to")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsAdCategory) WithContext(ctx context.Context) *cmsAdCategoryDo {
	return c.cmsAdCategoryDo.WithContext(ctx)
}

func (c cmsAdCategory) TableName() string { return c.cmsAdCategoryDo.TableName() }

func (c cmsAdCategory) Alias() string { return c.cmsAdCategoryDo.Alias() }

func (c *cmsAdCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdCategory) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["site_id"] = c.SiteID
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["title"] = c.Title
	c.fieldMap["call_index"] = c.CallIndex
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["belong_to"] = c.BelongTo
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsAdCategory) clone(db *gorm.DB) cmsAdCategory {
	c.cmsAdCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdCategory) replaceDB(db *gorm.DB) cmsAdCategory {
	c.cmsAdCategoryDo.ReplaceDB(db)
	return c
}

type cmsAdCategoryDo struct{ gen.DO }

func (c cmsAdCategoryDo) Debug() *cmsAdCategoryDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdCategoryDo) WithContext(ctx context.Context) *cmsAdCategoryDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdCategoryDo) ReadDB() *cmsAdCategoryDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdCategoryDo) WriteDB() *cmsAdCategoryDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdCategoryDo) Session(config *gorm.Session) *cmsAdCategoryDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdCategoryDo) Clauses(conds ...clause.Expression) *cmsAdCategoryDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdCategoryDo) Returning(value interface{}, columns ...string) *cmsAdCategoryDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdCategoryDo) Not(conds ...gen.Condition) *cmsAdCategoryDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdCategoryDo) Or(conds ...gen.Condition) *cmsAdCategoryDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdCategoryDo) Select(conds ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdCategoryDo) Where(conds ...gen.Condition) *cmsAdCategoryDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdCategoryDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdCategoryDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdCategoryDo) Order(conds ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdCategoryDo) Distinct(cols ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdCategoryDo) Omit(cols ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdCategoryDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdCategoryDo) Group(cols ...field.Expr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdCategoryDo) Having(conds ...gen.Condition) *cmsAdCategoryDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdCategoryDo) Limit(limit int) *cmsAdCategoryDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdCategoryDo) Offset(offset int) *cmsAdCategoryDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdCategoryDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdCategoryDo) Unscoped() *cmsAdCategoryDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdCategoryDo) Create(values ...*model.CmsAdCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdCategoryDo) CreateInBatches(values []*model.CmsAdCategory, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdCategoryDo) Save(values ...*model.CmsAdCategory) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdCategoryDo) First() (*model.CmsAdCategory, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategory), nil
	}
}

func (c cmsAdCategoryDo) Take() (*model.CmsAdCategory, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategory), nil
	}
}

func (c cmsAdCategoryDo) Last() (*model.CmsAdCategory, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategory), nil
	}
}

func (c cmsAdCategoryDo) Find() ([]*model.CmsAdCategory, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdCategory), err
}

func (c cmsAdCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdCategory, err error) {
	buf := make([]*model.CmsAdCategory, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdCategoryDo) FindInBatches(result *[]*model.CmsAdCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdCategoryDo) Attrs(attrs ...field.AssignExpr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdCategoryDo) Assign(attrs ...field.AssignExpr) *cmsAdCategoryDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdCategoryDo) Joins(fields ...field.RelationField) *cmsAdCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdCategoryDo) Preload(fields ...field.RelationField) *cmsAdCategoryDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdCategoryDo) FirstOrInit() (*model.CmsAdCategory, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategory), nil
	}
}

func (c cmsAdCategoryDo) FirstOrCreate() (*model.CmsAdCategory, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdCategory), nil
	}
}

func (c cmsAdCategoryDo) FindByPage(offset int, limit int) (result []*model.CmsAdCategory, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdCategoryDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdCategoryDo) Delete(models ...*model.CmsAdCategory) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdCategoryDo) withDO(do gen.Dao) *cmsAdCategoryDo {
	c.DO = *do.(*gen.DO)
	return c
}
