// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAds(db *gorm.DB, opts ...gen.DOOption) cmsAds {
	_cmsAds := cmsAds{}

	_cmsAds.cmsAdsDo.UseDB(db, opts...)
	_cmsAds.cmsAdsDo.UseModel(&model.CmsAds{})

	tableName := _cmsAds.cmsAdsDo.TableName()
	_cmsAds.ALL = field.NewAsterisk(tableName)
	_cmsAds.AdsID = field.NewInt64(tableName, "ads_id")
	_cmsAds.SiteID = field.NewInt64(tableName, "site_id")
	_cmsAds.ChannelID = field.NewInt64(tableName, "channel_id")
	_cmsAds.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsAds.Title = field.NewString(tableName, "title")
	_cmsAds.CallIndex = field.NewString(tableName, "call_index")
	_cmsAds.LinkURL = field.NewString(tableName, "link_url")
	_cmsAds.Target = field.NewString(tableName, "target")
	_cmsAds.ImgUrl1 = field.NewString(tableName, "img_url1")
	_cmsAds.ImgUrl2 = field.NewString(tableName, "img_url2")
	_cmsAds.Remark = field.NewString(tableName, "remark")
	_cmsAds.SortID = field.NewInt32(tableName, "sort_id")
	_cmsAds.Click = field.NewInt32(tableName, "click")
	_cmsAds.Status = field.NewInt32(tableName, "status")
	_cmsAds.IsLock = field.NewInt32(tableName, "is_lock")
	_cmsAds.IsTop = field.NewInt32(tableName, "is_top")
	_cmsAds.IsRed = field.NewInt32(tableName, "is_red")
	_cmsAds.IsHot = field.NewInt32(tableName, "is_hot")
	_cmsAds.IsSlide = field.NewInt32(tableName, "is_slide")
	_cmsAds.BeginTime = field.NewTime(tableName, "begin_time")
	_cmsAds.EndTime = field.NewTime(tableName, "end_time")
	_cmsAds.BelongTo = field.NewString(tableName, "belong_to")
	_cmsAds.CreateID = field.NewInt32(tableName, "create_id")
	_cmsAds.CreateName = field.NewString(tableName, "create_name")
	_cmsAds.CreateTime = field.NewTime(tableName, "create_time")
	_cmsAds.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsAds.UpdateName = field.NewString(tableName, "update_name")
	_cmsAds.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsAds.fillFieldMap()

	return _cmsAds
}

type cmsAds struct {
	cmsAdsDo cmsAdsDo

	ALL        field.Asterisk
	AdsID      field.Int64  // 主键
	SiteID     field.Int64  // 所属站点
	ChannelID  field.Int64  // 所属频道
	CategoryID field.Int64  // 类别ID
	Title      field.String // 标题
	CallIndex  field.String // 调用别名
	LinkURL    field.String // 外部链接
	Target     field.String // 是否开启浏览器新窗口
	ImgUrl1    field.String // 图片地址
	ImgUrl2    field.String // 图片地址
	Remark     field.String // 备注
	SortID     field.Int32  // 排序
	Click      field.Int32  // 浏览次数
	Status     field.Int32  // 状态0草稿1提交2审核通过3审核未通过4驳回
	IsLock     field.Int32  // 是否锁定（不允许编辑）
	IsTop      field.Int32  // 是否置顶
	IsRed      field.Int32  // 是否推荐
	IsHot      field.Int32  // 是否热门
	IsSlide    field.Int32  // 是否幻灯片
	BeginTime  field.Time   // 开始时间
	EndTime    field.Time   // 结束时间
	BelongTo   field.String // 归属
	CreateID   field.Int32  // 创建人ID
	CreateName field.String // 创建人姓名
	CreateTime field.Time   // 创建时间
	UpdateID   field.Int32  // 更新人ID
	UpdateName field.String // 更新人姓名
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsAds) Table(newTableName string) *cmsAds {
	c.cmsAdsDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAds) As(alias string) *cmsAds {
	c.cmsAdsDo.DO = *(c.cmsAdsDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAds) updateTableName(table string) *cmsAds {
	c.ALL = field.NewAsterisk(table)
	c.AdsID = field.NewInt64(table, "ads_id")
	c.SiteID = field.NewInt64(table, "site_id")
	c.ChannelID = field.NewInt64(table, "channel_id")
	c.CategoryID = field.NewInt64(table, "category_id")
	c.Title = field.NewString(table, "title")
	c.CallIndex = field.NewString(table, "call_index")
	c.LinkURL = field.NewString(table, "link_url")
	c.Target = field.NewString(table, "target")
	c.ImgUrl1 = field.NewString(table, "img_url1")
	c.ImgUrl2 = field.NewString(table, "img_url2")
	c.Remark = field.NewString(table, "remark")
	c.SortID = field.NewInt32(table, "sort_id")
	c.Click = field.NewInt32(table, "click")
	c.Status = field.NewInt32(table, "status")
	c.IsLock = field.NewInt32(table, "is_lock")
	c.IsTop = field.NewInt32(table, "is_top")
	c.IsRed = field.NewInt32(table, "is_red")
	c.IsHot = field.NewInt32(table, "is_hot")
	c.IsSlide = field.NewInt32(table, "is_slide")
	c.BeginTime = field.NewTime(table, "begin_time")
	c.EndTime = field.NewTime(table, "end_time")
	c.BelongTo = field.NewString(table, "belong_to")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsAds) WithContext(ctx context.Context) *cmsAdsDo { return c.cmsAdsDo.WithContext(ctx) }

func (c cmsAds) TableName() string { return c.cmsAdsDo.TableName() }

func (c cmsAds) Alias() string { return c.cmsAdsDo.Alias() }

func (c cmsAds) Columns(cols ...field.Expr) gen.Columns { return c.cmsAdsDo.Columns(cols...) }

func (c *cmsAds) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAds) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 28)
	c.fieldMap["ads_id"] = c.AdsID
	c.fieldMap["site_id"] = c.SiteID
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["title"] = c.Title
	c.fieldMap["call_index"] = c.CallIndex
	c.fieldMap["link_url"] = c.LinkURL
	c.fieldMap["target"] = c.Target
	c.fieldMap["img_url1"] = c.ImgUrl1
	c.fieldMap["img_url2"] = c.ImgUrl2
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["click"] = c.Click
	c.fieldMap["status"] = c.Status
	c.fieldMap["is_lock"] = c.IsLock
	c.fieldMap["is_top"] = c.IsTop
	c.fieldMap["is_red"] = c.IsRed
	c.fieldMap["is_hot"] = c.IsHot
	c.fieldMap["is_slide"] = c.IsSlide
	c.fieldMap["begin_time"] = c.BeginTime
	c.fieldMap["end_time"] = c.EndTime
	c.fieldMap["belong_to"] = c.BelongTo
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsAds) clone(db *gorm.DB) cmsAds {
	c.cmsAdsDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAds) replaceDB(db *gorm.DB) cmsAds {
	c.cmsAdsDo.ReplaceDB(db)
	return c
}

type cmsAdsDo struct{ gen.DO }

func (c cmsAdsDo) Debug() *cmsAdsDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdsDo) WithContext(ctx context.Context) *cmsAdsDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdsDo) ReadDB() *cmsAdsDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdsDo) WriteDB() *cmsAdsDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdsDo) Session(config *gorm.Session) *cmsAdsDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdsDo) Clauses(conds ...clause.Expression) *cmsAdsDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdsDo) Returning(value interface{}, columns ...string) *cmsAdsDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdsDo) Not(conds ...gen.Condition) *cmsAdsDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdsDo) Or(conds ...gen.Condition) *cmsAdsDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdsDo) Select(conds ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdsDo) Where(conds ...gen.Condition) *cmsAdsDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdsDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdsDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdsDo) Order(conds ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdsDo) Distinct(cols ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdsDo) Omit(cols ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdsDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdsDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdsDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdsDo) Group(cols ...field.Expr) *cmsAdsDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdsDo) Having(conds ...gen.Condition) *cmsAdsDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdsDo) Limit(limit int) *cmsAdsDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdsDo) Offset(offset int) *cmsAdsDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdsDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdsDo) Unscoped() *cmsAdsDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdsDo) Create(values ...*model.CmsAds) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdsDo) CreateInBatches(values []*model.CmsAds, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdsDo) Save(values ...*model.CmsAds) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdsDo) First() (*model.CmsAds, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAds), nil
	}
}

func (c cmsAdsDo) Take() (*model.CmsAds, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAds), nil
	}
}

func (c cmsAdsDo) Last() (*model.CmsAds, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAds), nil
	}
}

func (c cmsAdsDo) Find() ([]*model.CmsAds, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAds), err
}

func (c cmsAdsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAds, err error) {
	buf := make([]*model.CmsAds, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdsDo) FindInBatches(result *[]*model.CmsAds, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdsDo) Attrs(attrs ...field.AssignExpr) *cmsAdsDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdsDo) Assign(attrs ...field.AssignExpr) *cmsAdsDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdsDo) Joins(fields ...field.RelationField) *cmsAdsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdsDo) Preload(fields ...field.RelationField) *cmsAdsDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdsDo) FirstOrInit() (*model.CmsAds, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAds), nil
	}
}

func (c cmsAdsDo) FirstOrCreate() (*model.CmsAds, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAds), nil
	}
}

func (c cmsAdsDo) FindByPage(offset int, limit int) (result []*model.CmsAds, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdsDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdsDo) Delete(models ...*model.CmsAds) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdsDo) withDO(do gen.Dao) *cmsAdsDo {
	c.DO = *do.(*gen.DO)
	return c
}
