// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsSiteChannel(db *gorm.DB, opts ...gen.DOOption) cmsSiteChannel {
	_cmsSiteChannel := cmsSiteChannel{}

	_cmsSiteChannel.cmsSiteChannelDo.UseDB(db, opts...)
	_cmsSiteChannel.cmsSiteChannelDo.UseModel(&model.CmsSiteChannel{})

	tableName := _cmsSiteChannel.cmsSiteChannelDo.TableName()
	_cmsSiteChannel.ALL = field.NewAsterisk(tableName)
	_cmsSiteChannel.ChannelID = field.NewInt64(tableName, "channel_id")
	_cmsSiteChannel.ParentID = field.NewInt64(tableName, "parent_id")
	_cmsSiteChannel.SiteID = field.NewInt64(tableName, "site_id")
	_cmsSiteChannel.Name = field.NewString(tableName, "name")
	_cmsSiteChannel.Title = field.NewString(tableName, "title")
	_cmsSiteChannel.Kind = field.NewInt32(tableName, "kind")
	_cmsSiteChannel.ClassLayer = field.NewInt32(tableName, "class_layer")
	_cmsSiteChannel.LinkURL = field.NewString(tableName, "link_url")
	_cmsSiteChannel.Target = field.NewString(tableName, "target")
	_cmsSiteChannel.ImgUrl1 = field.NewString(tableName, "img_url1")
	_cmsSiteChannel.ImgUrl2 = field.NewString(tableName, "img_url2")
	_cmsSiteChannel.IsComment = field.NewInt32(tableName, "is_comment")
	_cmsSiteChannel.IsAlbum = field.NewInt32(tableName, "is_album")
	_cmsSiteChannel.IsAttach = field.NewInt32(tableName, "is_attach")
	_cmsSiteChannel.IsSpec = field.NewInt32(tableName, "is_spec")
	_cmsSiteChannel.SortID = field.NewInt32(tableName, "sort_id")
	_cmsSiteChannel.Status = field.NewInt32(tableName, "status")
	_cmsSiteChannel.IsDeleted = field.NewBool(tableName, "is_deleted")
	_cmsSiteChannel.IsShow = field.NewBool(tableName, "is_show")
	_cmsSiteChannel.TmplChnl = field.NewString(tableName, "tmpl_chnl")
	_cmsSiteChannel.TmplCat = field.NewString(tableName, "tmpl_cat")
	_cmsSiteChannel.TmplLst = field.NewString(tableName, "tmpl_lst")
	_cmsSiteChannel.TmplDtl = field.NewString(tableName, "tmpl_dtl")
	_cmsSiteChannel.CreateID = field.NewInt32(tableName, "create_id")
	_cmsSiteChannel.CreateName = field.NewString(tableName, "create_name")
	_cmsSiteChannel.CreateTime = field.NewTime(tableName, "create_time")
	_cmsSiteChannel.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsSiteChannel.UpdateName = field.NewString(tableName, "update_name")
	_cmsSiteChannel.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsSiteChannel.fillFieldMap()

	return _cmsSiteChannel
}

type cmsSiteChannel struct {
	cmsSiteChannelDo cmsSiteChannelDo

	ALL        field.Asterisk
	ChannelID  field.Int64  // 主键
	ParentID   field.Int64  // 父级ID
	SiteID     field.Int64  // 站点ID
	Name       field.String // 频道名称
	Title      field.String // 频道标题
	Kind       field.Int32  // 频道类型0文章1链接
	ClassLayer field.Int32  // 类别深度
	LinkURL    field.String // 外部链接
	Target     field.String // 是否开启浏览器新窗口
	ImgUrl1    field.String // 图片地址
	ImgUrl2    field.String // 图片地址
	IsComment  field.Int32  // 是否开启评论
	IsAlbum    field.Int32  // 是否开启相册功能
	IsAttach   field.Int32  // 是否开启附件功能
	IsSpec     field.Int32  // 是否开启规格
	SortID     field.Int32  // 排序
	Status     field.Int32  // 状态0草稿1提交2审核通过3审核未通过4驳回
	IsDeleted  field.Bool   // 删除标识
	IsShow     field.Bool   // 是否显示:1显示，0隐藏
	TmplChnl   field.String // 频道模板路径
	TmplCat    field.String // 栏目模板路径
	TmplLst    field.String // 列表模板路径
	TmplDtl    field.String // 明细模板路径
	CreateID   field.Int32  // 创建人ID
	CreateName field.String // 创建人姓名
	CreateTime field.Time   // 创建时间
	UpdateID   field.Int32  // 更新人ID
	UpdateName field.String // 更新人姓名
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsSiteChannel) Table(newTableName string) *cmsSiteChannel {
	c.cmsSiteChannelDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsSiteChannel) As(alias string) *cmsSiteChannel {
	c.cmsSiteChannelDo.DO = *(c.cmsSiteChannelDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsSiteChannel) updateTableName(table string) *cmsSiteChannel {
	c.ALL = field.NewAsterisk(table)
	c.ChannelID = field.NewInt64(table, "channel_id")
	c.ParentID = field.NewInt64(table, "parent_id")
	c.SiteID = field.NewInt64(table, "site_id")
	c.Name = field.NewString(table, "name")
	c.Title = field.NewString(table, "title")
	c.Kind = field.NewInt32(table, "kind")
	c.ClassLayer = field.NewInt32(table, "class_layer")
	c.LinkURL = field.NewString(table, "link_url")
	c.Target = field.NewString(table, "target")
	c.ImgUrl1 = field.NewString(table, "img_url1")
	c.ImgUrl2 = field.NewString(table, "img_url2")
	c.IsComment = field.NewInt32(table, "is_comment")
	c.IsAlbum = field.NewInt32(table, "is_album")
	c.IsAttach = field.NewInt32(table, "is_attach")
	c.IsSpec = field.NewInt32(table, "is_spec")
	c.SortID = field.NewInt32(table, "sort_id")
	c.Status = field.NewInt32(table, "status")
	c.IsDeleted = field.NewBool(table, "is_deleted")
	c.IsShow = field.NewBool(table, "is_show")
	c.TmplChnl = field.NewString(table, "tmpl_chnl")
	c.TmplCat = field.NewString(table, "tmpl_cat")
	c.TmplLst = field.NewString(table, "tmpl_lst")
	c.TmplDtl = field.NewString(table, "tmpl_dtl")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsSiteChannel) WithContext(ctx context.Context) *cmsSiteChannelDo {
	return c.cmsSiteChannelDo.WithContext(ctx)
}

func (c cmsSiteChannel) TableName() string { return c.cmsSiteChannelDo.TableName() }

func (c cmsSiteChannel) Alias() string { return c.cmsSiteChannelDo.Alias() }

func (c *cmsSiteChannel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsSiteChannel) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 29)
	c.fieldMap["channel_id"] = c.ChannelID
	c.fieldMap["parent_id"] = c.ParentID
	c.fieldMap["site_id"] = c.SiteID
	c.fieldMap["name"] = c.Name
	c.fieldMap["title"] = c.Title
	c.fieldMap["kind"] = c.Kind
	c.fieldMap["class_layer"] = c.ClassLayer
	c.fieldMap["link_url"] = c.LinkURL
	c.fieldMap["target"] = c.Target
	c.fieldMap["img_url1"] = c.ImgUrl1
	c.fieldMap["img_url2"] = c.ImgUrl2
	c.fieldMap["is_comment"] = c.IsComment
	c.fieldMap["is_album"] = c.IsAlbum
	c.fieldMap["is_attach"] = c.IsAttach
	c.fieldMap["is_spec"] = c.IsSpec
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["status"] = c.Status
	c.fieldMap["is_deleted"] = c.IsDeleted
	c.fieldMap["is_show"] = c.IsShow
	c.fieldMap["tmpl_chnl"] = c.TmplChnl
	c.fieldMap["tmpl_cat"] = c.TmplCat
	c.fieldMap["tmpl_lst"] = c.TmplLst
	c.fieldMap["tmpl_dtl"] = c.TmplDtl
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsSiteChannel) clone(db *gorm.DB) cmsSiteChannel {
	c.cmsSiteChannelDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsSiteChannel) replaceDB(db *gorm.DB) cmsSiteChannel {
	c.cmsSiteChannelDo.ReplaceDB(db)
	return c
}

type cmsSiteChannelDo struct{ gen.DO }

func (c cmsSiteChannelDo) Debug() *cmsSiteChannelDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsSiteChannelDo) WithContext(ctx context.Context) *cmsSiteChannelDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsSiteChannelDo) ReadDB() *cmsSiteChannelDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsSiteChannelDo) WriteDB() *cmsSiteChannelDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsSiteChannelDo) Session(config *gorm.Session) *cmsSiteChannelDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsSiteChannelDo) Clauses(conds ...clause.Expression) *cmsSiteChannelDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsSiteChannelDo) Returning(value interface{}, columns ...string) *cmsSiteChannelDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsSiteChannelDo) Not(conds ...gen.Condition) *cmsSiteChannelDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsSiteChannelDo) Or(conds ...gen.Condition) *cmsSiteChannelDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsSiteChannelDo) Select(conds ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsSiteChannelDo) Where(conds ...gen.Condition) *cmsSiteChannelDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsSiteChannelDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsSiteChannelDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsSiteChannelDo) Order(conds ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsSiteChannelDo) Distinct(cols ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsSiteChannelDo) Omit(cols ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsSiteChannelDo) Join(table schema.Tabler, on ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsSiteChannelDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsSiteChannelDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsSiteChannelDo) Group(cols ...field.Expr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsSiteChannelDo) Having(conds ...gen.Condition) *cmsSiteChannelDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsSiteChannelDo) Limit(limit int) *cmsSiteChannelDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsSiteChannelDo) Offset(offset int) *cmsSiteChannelDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsSiteChannelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsSiteChannelDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsSiteChannelDo) Unscoped() *cmsSiteChannelDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsSiteChannelDo) Create(values ...*model.CmsSiteChannel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsSiteChannelDo) CreateInBatches(values []*model.CmsSiteChannel, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsSiteChannelDo) Save(values ...*model.CmsSiteChannel) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsSiteChannelDo) First() (*model.CmsSiteChannel, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsSiteChannel), nil
	}
}

func (c cmsSiteChannelDo) Take() (*model.CmsSiteChannel, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsSiteChannel), nil
	}
}

func (c cmsSiteChannelDo) Last() (*model.CmsSiteChannel, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsSiteChannel), nil
	}
}

func (c cmsSiteChannelDo) Find() ([]*model.CmsSiteChannel, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsSiteChannel), err
}

func (c cmsSiteChannelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsSiteChannel, err error) {
	buf := make([]*model.CmsSiteChannel, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsSiteChannelDo) FindInBatches(result *[]*model.CmsSiteChannel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsSiteChannelDo) Attrs(attrs ...field.AssignExpr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsSiteChannelDo) Assign(attrs ...field.AssignExpr) *cmsSiteChannelDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsSiteChannelDo) Joins(fields ...field.RelationField) *cmsSiteChannelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsSiteChannelDo) Preload(fields ...field.RelationField) *cmsSiteChannelDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsSiteChannelDo) FirstOrInit() (*model.CmsSiteChannel, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsSiteChannel), nil
	}
}

func (c cmsSiteChannelDo) FirstOrCreate() (*model.CmsSiteChannel, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsSiteChannel), nil
	}
}

func (c cmsSiteChannelDo) FindByPage(offset int, limit int) (result []*model.CmsSiteChannel, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsSiteChannelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsSiteChannelDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsSiteChannelDo) Delete(models ...*model.CmsSiteChannel) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsSiteChannelDo) withDO(do gen.Dao) *cmsSiteChannelDo {
	c.DO = *do.(*gen.DO)
	return c
}
