// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newCmsAdsCategoryRelation(db *gorm.DB, opts ...gen.DOOption) cmsAdsCategoryRelation {
	_cmsAdsCategoryRelation := cmsAdsCategoryRelation{}

	_cmsAdsCategoryRelation.cmsAdsCategoryRelationDo.UseDB(db, opts...)
	_cmsAdsCategoryRelation.cmsAdsCategoryRelationDo.UseModel(&model.CmsAdsCategoryRelation{})

	tableName := _cmsAdsCategoryRelation.cmsAdsCategoryRelationDo.TableName()
	_cmsAdsCategoryRelation.ALL = field.NewAsterisk(tableName)
	_cmsAdsCategoryRelation.RelationID = field.NewInt64(tableName, "relation_id")
	_cmsAdsCategoryRelation.CategoryID = field.NewInt64(tableName, "category_id")
	_cmsAdsCategoryRelation.AdsID = field.NewInt64(tableName, "ads_id")

	_cmsAdsCategoryRelation.fillFieldMap()

	return _cmsAdsCategoryRelation
}

type cmsAdsCategoryRelation struct {
	cmsAdsCategoryRelationDo cmsAdsCategoryRelationDo

	ALL        field.Asterisk
	RelationID field.Int64 // 主键
	CategoryID field.Int64 // 所属分类
	AdsID      field.Int64 // 所属广告

	fieldMap map[string]field.Expr
}

func (c cmsAdsCategoryRelation) Table(newTableName string) *cmsAdsCategoryRelation {
	c.cmsAdsCategoryRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdsCategoryRelation) As(alias string) *cmsAdsCategoryRelation {
	c.cmsAdsCategoryRelationDo.DO = *(c.cmsAdsCategoryRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdsCategoryRelation) updateTableName(table string) *cmsAdsCategoryRelation {
	c.ALL = field.NewAsterisk(table)
	c.RelationID = field.NewInt64(table, "relation_id")
	c.CategoryID = field.NewInt64(table, "category_id")
	c.AdsID = field.NewInt64(table, "ads_id")

	c.fillFieldMap()

	return c
}

func (c *cmsAdsCategoryRelation) WithContext(ctx context.Context) *cmsAdsCategoryRelationDo {
	return c.cmsAdsCategoryRelationDo.WithContext(ctx)
}

func (c cmsAdsCategoryRelation) TableName() string { return c.cmsAdsCategoryRelationDo.TableName() }

func (c cmsAdsCategoryRelation) Alias() string { return c.cmsAdsCategoryRelationDo.Alias() }

func (c cmsAdsCategoryRelation) Columns(cols ...field.Expr) gen.Columns {
	return c.cmsAdsCategoryRelationDo.Columns(cols...)
}

func (c *cmsAdsCategoryRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdsCategoryRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["relation_id"] = c.RelationID
	c.fieldMap["category_id"] = c.CategoryID
	c.fieldMap["ads_id"] = c.AdsID
}

func (c cmsAdsCategoryRelation) clone(db *gorm.DB) cmsAdsCategoryRelation {
	c.cmsAdsCategoryRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdsCategoryRelation) replaceDB(db *gorm.DB) cmsAdsCategoryRelation {
	c.cmsAdsCategoryRelationDo.ReplaceDB(db)
	return c
}

type cmsAdsCategoryRelationDo struct{ gen.DO }

func (c cmsAdsCategoryRelationDo) Debug() *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdsCategoryRelationDo) WithContext(ctx context.Context) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdsCategoryRelationDo) ReadDB() *cmsAdsCategoryRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsAdsCategoryRelationDo) WriteDB() *cmsAdsCategoryRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsAdsCategoryRelationDo) Session(config *gorm.Session) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdsCategoryRelationDo) Clauses(conds ...clause.Expression) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdsCategoryRelationDo) Returning(value interface{}, columns ...string) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdsCategoryRelationDo) Not(conds ...gen.Condition) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdsCategoryRelationDo) Or(conds ...gen.Condition) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdsCategoryRelationDo) Select(conds ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdsCategoryRelationDo) Where(conds ...gen.Condition) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdsCategoryRelationDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *cmsAdsCategoryRelationDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c cmsAdsCategoryRelationDo) Order(conds ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdsCategoryRelationDo) Distinct(cols ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdsCategoryRelationDo) Omit(cols ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdsCategoryRelationDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdsCategoryRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdsCategoryRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdsCategoryRelationDo) Group(cols ...field.Expr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdsCategoryRelationDo) Having(conds ...gen.Condition) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdsCategoryRelationDo) Limit(limit int) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdsCategoryRelationDo) Offset(offset int) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdsCategoryRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdsCategoryRelationDo) Unscoped() *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdsCategoryRelationDo) Create(values ...*model.CmsAdsCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdsCategoryRelationDo) CreateInBatches(values []*model.CmsAdsCategoryRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdsCategoryRelationDo) Save(values ...*model.CmsAdsCategoryRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdsCategoryRelationDo) First() (*model.CmsAdsCategoryRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategoryRelation), nil
	}
}

func (c cmsAdsCategoryRelationDo) Take() (*model.CmsAdsCategoryRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategoryRelation), nil
	}
}

func (c cmsAdsCategoryRelationDo) Last() (*model.CmsAdsCategoryRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategoryRelation), nil
	}
}

func (c cmsAdsCategoryRelationDo) Find() ([]*model.CmsAdsCategoryRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CmsAdsCategoryRelation), err
}

func (c cmsAdsCategoryRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CmsAdsCategoryRelation, err error) {
	buf := make([]*model.CmsAdsCategoryRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdsCategoryRelationDo) FindInBatches(result *[]*model.CmsAdsCategoryRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdsCategoryRelationDo) Attrs(attrs ...field.AssignExpr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdsCategoryRelationDo) Assign(attrs ...field.AssignExpr) *cmsAdsCategoryRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdsCategoryRelationDo) Joins(fields ...field.RelationField) *cmsAdsCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdsCategoryRelationDo) Preload(fields ...field.RelationField) *cmsAdsCategoryRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdsCategoryRelationDo) FirstOrInit() (*model.CmsAdsCategoryRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategoryRelation), nil
	}
}

func (c cmsAdsCategoryRelationDo) FirstOrCreate() (*model.CmsAdsCategoryRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CmsAdsCategoryRelation), nil
	}
}

func (c cmsAdsCategoryRelationDo) FindByPage(offset int, limit int) (result []*model.CmsAdsCategoryRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdsCategoryRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdsCategoryRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdsCategoryRelationDo) Delete(models ...*model.CmsAdsCategoryRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdsCategoryRelationDo) withDO(do gen.Dao) *cmsAdsCategoryRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
