// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newPlgOnlineRegister(db *gorm.DB, opts ...gen.DOOption) plgOnlineRegister {
	_plgOnlineRegister := plgOnlineRegister{}

	_plgOnlineRegister.plgOnlineRegisterDo.UseDB(db, opts...)
	_plgOnlineRegister.plgOnlineRegisterDo.UseModel(&model.PlgOnlineRegister{})

	tableName := _plgOnlineRegister.plgOnlineRegisterDo.TableName()
	_plgOnlineRegister.ALL = field.NewAsterisk(tableName)
	_plgOnlineRegister.RegisterID = field.NewInt64(tableName, "register_id")
	_plgOnlineRegister.RealName = field.NewString(tableName, "real_name")
	_plgOnlineRegister.Sex = field.NewString(tableName, "sex")
	_plgOnlineRegister.Year = field.NewString(tableName, "year")
	_plgOnlineRegister.Special = field.NewString(tableName, "special")
	_plgOnlineRegister.Degree = field.NewString(tableName, "degree")
	_plgOnlineRegister.Mobile = field.NewString(tableName, "mobile")
	_plgOnlineRegister.Email = field.NewString(tableName, "email")
	_plgOnlineRegister.Wechat = field.NewString(tableName, "wechat")
	_plgOnlineRegister.Address = field.NewString(tableName, "address")
	_plgOnlineRegister.Content = field.NewString(tableName, "content")
	_plgOnlineRegister.IP = field.NewString(tableName, "ip")
	_plgOnlineRegister.IsRead = field.NewInt32(tableName, "is_read")
	_plgOnlineRegister.Tags = field.NewString(tableName, "tags")
	_plgOnlineRegister.Remark = field.NewString(tableName, "remark")
	_plgOnlineRegister.IsDeleted = field.NewBool(tableName, "is_deleted")
	_plgOnlineRegister.CreateID = field.NewInt32(tableName, "create_id")
	_plgOnlineRegister.CreateName = field.NewString(tableName, "create_name")
	_plgOnlineRegister.CreateTime = field.NewTime(tableName, "create_time")
	_plgOnlineRegister.UpdateID = field.NewInt32(tableName, "update_id")
	_plgOnlineRegister.UpdateName = field.NewString(tableName, "update_name")
	_plgOnlineRegister.UpdateTime = field.NewTime(tableName, "update_time")

	_plgOnlineRegister.fillFieldMap()

	return _plgOnlineRegister
}

type plgOnlineRegister struct {
	plgOnlineRegisterDo plgOnlineRegisterDo

	ALL        field.Asterisk
	RegisterID field.Int64  // 主键
	RealName   field.String // 姓名
	Sex        field.String // 性别
	Year       field.String // 年龄
	Special    field.String // 意向专业
	Degree     field.String // 学历
	Mobile     field.String // 联系电话
	Email      field.String // 电子邮箱
	Wechat     field.String // 微信号
	Address    field.String // 家庭地址
	Content    field.String // 留言内容
	IP         field.String // IP地址
	IsRead     field.Int32  // 是否已读
	Tags       field.String // 标签
	Remark     field.String // 备注
	IsDeleted  field.Bool   // 删除标识
	CreateID   field.Int32  // 创建人ID
	CreateName field.String // 创建人姓名
	CreateTime field.Time   // 创建时间
	UpdateID   field.Int32  // 更新人ID
	UpdateName field.String // 更新人姓名
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (p plgOnlineRegister) Table(newTableName string) *plgOnlineRegister {
	p.plgOnlineRegisterDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p plgOnlineRegister) As(alias string) *plgOnlineRegister {
	p.plgOnlineRegisterDo.DO = *(p.plgOnlineRegisterDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *plgOnlineRegister) updateTableName(table string) *plgOnlineRegister {
	p.ALL = field.NewAsterisk(table)
	p.RegisterID = field.NewInt64(table, "register_id")
	p.RealName = field.NewString(table, "real_name")
	p.Sex = field.NewString(table, "sex")
	p.Year = field.NewString(table, "year")
	p.Special = field.NewString(table, "special")
	p.Degree = field.NewString(table, "degree")
	p.Mobile = field.NewString(table, "mobile")
	p.Email = field.NewString(table, "email")
	p.Wechat = field.NewString(table, "wechat")
	p.Address = field.NewString(table, "address")
	p.Content = field.NewString(table, "content")
	p.IP = field.NewString(table, "ip")
	p.IsRead = field.NewInt32(table, "is_read")
	p.Tags = field.NewString(table, "tags")
	p.Remark = field.NewString(table, "remark")
	p.IsDeleted = field.NewBool(table, "is_deleted")
	p.CreateID = field.NewInt32(table, "create_id")
	p.CreateName = field.NewString(table, "create_name")
	p.CreateTime = field.NewTime(table, "create_time")
	p.UpdateID = field.NewInt32(table, "update_id")
	p.UpdateName = field.NewString(table, "update_name")
	p.UpdateTime = field.NewTime(table, "update_time")

	p.fillFieldMap()

	return p
}

func (p *plgOnlineRegister) WithContext(ctx context.Context) *plgOnlineRegisterDo {
	return p.plgOnlineRegisterDo.WithContext(ctx)
}

func (p plgOnlineRegister) TableName() string { return p.plgOnlineRegisterDo.TableName() }

func (p plgOnlineRegister) Alias() string { return p.plgOnlineRegisterDo.Alias() }

func (p *plgOnlineRegister) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *plgOnlineRegister) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 22)
	p.fieldMap["register_id"] = p.RegisterID
	p.fieldMap["real_name"] = p.RealName
	p.fieldMap["sex"] = p.Sex
	p.fieldMap["year"] = p.Year
	p.fieldMap["special"] = p.Special
	p.fieldMap["degree"] = p.Degree
	p.fieldMap["mobile"] = p.Mobile
	p.fieldMap["email"] = p.Email
	p.fieldMap["wechat"] = p.Wechat
	p.fieldMap["address"] = p.Address
	p.fieldMap["content"] = p.Content
	p.fieldMap["ip"] = p.IP
	p.fieldMap["is_read"] = p.IsRead
	p.fieldMap["tags"] = p.Tags
	p.fieldMap["remark"] = p.Remark
	p.fieldMap["is_deleted"] = p.IsDeleted
	p.fieldMap["create_id"] = p.CreateID
	p.fieldMap["create_name"] = p.CreateName
	p.fieldMap["create_time"] = p.CreateTime
	p.fieldMap["update_id"] = p.UpdateID
	p.fieldMap["update_name"] = p.UpdateName
	p.fieldMap["update_time"] = p.UpdateTime
}

func (p plgOnlineRegister) clone(db *gorm.DB) plgOnlineRegister {
	p.plgOnlineRegisterDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p plgOnlineRegister) replaceDB(db *gorm.DB) plgOnlineRegister {
	p.plgOnlineRegisterDo.ReplaceDB(db)
	return p
}

type plgOnlineRegisterDo struct{ gen.DO }

func (p plgOnlineRegisterDo) Debug() *plgOnlineRegisterDo {
	return p.withDO(p.DO.Debug())
}

func (p plgOnlineRegisterDo) WithContext(ctx context.Context) *plgOnlineRegisterDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p plgOnlineRegisterDo) ReadDB() *plgOnlineRegisterDo {
	return p.Clauses(dbresolver.Read)
}

func (p plgOnlineRegisterDo) WriteDB() *plgOnlineRegisterDo {
	return p.Clauses(dbresolver.Write)
}

func (p plgOnlineRegisterDo) Session(config *gorm.Session) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Session(config))
}

func (p plgOnlineRegisterDo) Clauses(conds ...clause.Expression) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p plgOnlineRegisterDo) Returning(value interface{}, columns ...string) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p plgOnlineRegisterDo) Not(conds ...gen.Condition) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p plgOnlineRegisterDo) Or(conds ...gen.Condition) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p plgOnlineRegisterDo) Select(conds ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p plgOnlineRegisterDo) Where(conds ...gen.Condition) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p plgOnlineRegisterDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *plgOnlineRegisterDo {
	return p.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (p plgOnlineRegisterDo) Order(conds ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p plgOnlineRegisterDo) Distinct(cols ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p plgOnlineRegisterDo) Omit(cols ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p plgOnlineRegisterDo) Join(table schema.Tabler, on ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p plgOnlineRegisterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p plgOnlineRegisterDo) RightJoin(table schema.Tabler, on ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p plgOnlineRegisterDo) Group(cols ...field.Expr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p plgOnlineRegisterDo) Having(conds ...gen.Condition) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p plgOnlineRegisterDo) Limit(limit int) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p plgOnlineRegisterDo) Offset(offset int) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p plgOnlineRegisterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p plgOnlineRegisterDo) Unscoped() *plgOnlineRegisterDo {
	return p.withDO(p.DO.Unscoped())
}

func (p plgOnlineRegisterDo) Create(values ...*model.PlgOnlineRegister) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p plgOnlineRegisterDo) CreateInBatches(values []*model.PlgOnlineRegister, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p plgOnlineRegisterDo) Save(values ...*model.PlgOnlineRegister) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p plgOnlineRegisterDo) First() (*model.PlgOnlineRegister, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlgOnlineRegister), nil
	}
}

func (p plgOnlineRegisterDo) Take() (*model.PlgOnlineRegister, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlgOnlineRegister), nil
	}
}

func (p plgOnlineRegisterDo) Last() (*model.PlgOnlineRegister, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlgOnlineRegister), nil
	}
}

func (p plgOnlineRegisterDo) Find() ([]*model.PlgOnlineRegister, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlgOnlineRegister), err
}

func (p plgOnlineRegisterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlgOnlineRegister, err error) {
	buf := make([]*model.PlgOnlineRegister, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p plgOnlineRegisterDo) FindInBatches(result *[]*model.PlgOnlineRegister, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p plgOnlineRegisterDo) Attrs(attrs ...field.AssignExpr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p plgOnlineRegisterDo) Assign(attrs ...field.AssignExpr) *plgOnlineRegisterDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p plgOnlineRegisterDo) Joins(fields ...field.RelationField) *plgOnlineRegisterDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p plgOnlineRegisterDo) Preload(fields ...field.RelationField) *plgOnlineRegisterDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p plgOnlineRegisterDo) FirstOrInit() (*model.PlgOnlineRegister, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlgOnlineRegister), nil
	}
}

func (p plgOnlineRegisterDo) FirstOrCreate() (*model.PlgOnlineRegister, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlgOnlineRegister), nil
	}
}

func (p plgOnlineRegisterDo) FindByPage(offset int, limit int) (result []*model.PlgOnlineRegister, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p plgOnlineRegisterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p plgOnlineRegisterDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p plgOnlineRegisterDo) Delete(models ...*model.PlgOnlineRegister) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *plgOnlineRegisterDo) withDO(do gen.Dao) *plgOnlineRegisterDo {
	p.DO = *do.(*gen.DO)
	return p
}
