// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/dal/model"
)

func newWeixinRequestRule(db *gorm.DB, opts ...gen.DOOption) weixinRequestRule {
	_weixinRequestRule := weixinRequestRule{}

	_weixinRequestRule.weixinRequestRuleDo.UseDB(db, opts...)
	_weixinRequestRule.weixinRequestRuleDo.UseModel(&model.WeixinRequestRule{})

	tableName := _weixinRequestRule.weixinRequestRuleDo.TableName()
	_weixinRequestRule.ALL = field.NewAsterisk(tableName)
	_weixinRequestRule.RuleID = field.NewInt64(tableName, "rule_id")
	_weixinRequestRule.AccountID = field.NewInt64(tableName, "account_id")
	_weixinRequestRule.Name = field.NewString(tableName, "name")
	_weixinRequestRule.Keywords = field.NewString(tableName, "keywords")
	_weixinRequestRule.RequestType = field.NewInt32(tableName, "request_type")
	_weixinRequestRule.ResponseType = field.NewInt32(tableName, "response_type")
	_weixinRequestRule.IsLikeQuery = field.NewInt32(tableName, "is_like_query")
	_weixinRequestRule.IsDefault = field.NewInt32(tableName, "is_default")
	_weixinRequestRule.SortID = field.NewInt32(tableName, "sort_id")
	_weixinRequestRule.CreateID = field.NewInt32(tableName, "create_id")
	_weixinRequestRule.CreateName = field.NewString(tableName, "create_name")
	_weixinRequestRule.CreateTime = field.NewTime(tableName, "create_time")
	_weixinRequestRule.UpdateID = field.NewInt32(tableName, "update_id")
	_weixinRequestRule.UpdateName = field.NewString(tableName, "update_name")
	_weixinRequestRule.UpdateTime = field.NewTime(tableName, "update_time")

	_weixinRequestRule.fillFieldMap()

	return _weixinRequestRule
}

type weixinRequestRule struct {
	weixinRequestRuleDo weixinRequestRuleDo

	ALL          field.Asterisk
	RuleID       field.Int64  // 主键
	AccountID    field.Int64  // 归属公众号
	Name         field.String // 规则名称
	Keywords     field.String // 请求关键词,逗号分隔
	RequestType  field.Int32  // 请求类型(0默认回复1文字2图片3语音4链接5地理位置6关注7取消关注8扫描带参数二维码事件9上报地理位置事件10自定义菜单事件）
	ResponseType field.Int32  // 回复类型(1文本2图文3语音4视频5第三方接口)
	IsLikeQuery  field.Int32  // 是否模糊查询
	IsDefault    field.Int32  // 是否默认回复
	SortID       field.Int32  // 排序
	CreateID     field.Int32  // 创建人ID
	CreateName   field.String // 创建人姓名
	CreateTime   field.Time   // 创建时间
	UpdateID     field.Int32  // 更新人ID
	UpdateName   field.String // 更新人姓名
	UpdateTime   field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (w weixinRequestRule) Table(newTableName string) *weixinRequestRule {
	w.weixinRequestRuleDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w weixinRequestRule) As(alias string) *weixinRequestRule {
	w.weixinRequestRuleDo.DO = *(w.weixinRequestRuleDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *weixinRequestRule) updateTableName(table string) *weixinRequestRule {
	w.ALL = field.NewAsterisk(table)
	w.RuleID = field.NewInt64(table, "rule_id")
	w.AccountID = field.NewInt64(table, "account_id")
	w.Name = field.NewString(table, "name")
	w.Keywords = field.NewString(table, "keywords")
	w.RequestType = field.NewInt32(table, "request_type")
	w.ResponseType = field.NewInt32(table, "response_type")
	w.IsLikeQuery = field.NewInt32(table, "is_like_query")
	w.IsDefault = field.NewInt32(table, "is_default")
	w.SortID = field.NewInt32(table, "sort_id")
	w.CreateID = field.NewInt32(table, "create_id")
	w.CreateName = field.NewString(table, "create_name")
	w.CreateTime = field.NewTime(table, "create_time")
	w.UpdateID = field.NewInt32(table, "update_id")
	w.UpdateName = field.NewString(table, "update_name")
	w.UpdateTime = field.NewTime(table, "update_time")

	w.fillFieldMap()

	return w
}

func (w *weixinRequestRule) WithContext(ctx context.Context) *weixinRequestRuleDo {
	return w.weixinRequestRuleDo.WithContext(ctx)
}

func (w weixinRequestRule) TableName() string { return w.weixinRequestRuleDo.TableName() }

func (w weixinRequestRule) Alias() string { return w.weixinRequestRuleDo.Alias() }

func (w weixinRequestRule) Columns(cols ...field.Expr) gen.Columns {
	return w.weixinRequestRuleDo.Columns(cols...)
}

func (w *weixinRequestRule) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *weixinRequestRule) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 15)
	w.fieldMap["rule_id"] = w.RuleID
	w.fieldMap["account_id"] = w.AccountID
	w.fieldMap["name"] = w.Name
	w.fieldMap["keywords"] = w.Keywords
	w.fieldMap["request_type"] = w.RequestType
	w.fieldMap["response_type"] = w.ResponseType
	w.fieldMap["is_like_query"] = w.IsLikeQuery
	w.fieldMap["is_default"] = w.IsDefault
	w.fieldMap["sort_id"] = w.SortID
	w.fieldMap["create_id"] = w.CreateID
	w.fieldMap["create_name"] = w.CreateName
	w.fieldMap["create_time"] = w.CreateTime
	w.fieldMap["update_id"] = w.UpdateID
	w.fieldMap["update_name"] = w.UpdateName
	w.fieldMap["update_time"] = w.UpdateTime
}

func (w weixinRequestRule) clone(db *gorm.DB) weixinRequestRule {
	w.weixinRequestRuleDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w weixinRequestRule) replaceDB(db *gorm.DB) weixinRequestRule {
	w.weixinRequestRuleDo.ReplaceDB(db)
	return w
}

type weixinRequestRuleDo struct{ gen.DO }

func (w weixinRequestRuleDo) Debug() *weixinRequestRuleDo {
	return w.withDO(w.DO.Debug())
}

func (w weixinRequestRuleDo) WithContext(ctx context.Context) *weixinRequestRuleDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w weixinRequestRuleDo) ReadDB() *weixinRequestRuleDo {
	return w.Clauses(dbresolver.Read)
}

func (w weixinRequestRuleDo) WriteDB() *weixinRequestRuleDo {
	return w.Clauses(dbresolver.Write)
}

func (w weixinRequestRuleDo) Session(config *gorm.Session) *weixinRequestRuleDo {
	return w.withDO(w.DO.Session(config))
}

func (w weixinRequestRuleDo) Clauses(conds ...clause.Expression) *weixinRequestRuleDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w weixinRequestRuleDo) Returning(value interface{}, columns ...string) *weixinRequestRuleDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w weixinRequestRuleDo) Not(conds ...gen.Condition) *weixinRequestRuleDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w weixinRequestRuleDo) Or(conds ...gen.Condition) *weixinRequestRuleDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w weixinRequestRuleDo) Select(conds ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w weixinRequestRuleDo) Where(conds ...gen.Condition) *weixinRequestRuleDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w weixinRequestRuleDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *weixinRequestRuleDo {
	return w.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (w weixinRequestRuleDo) Order(conds ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w weixinRequestRuleDo) Distinct(cols ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w weixinRequestRuleDo) Omit(cols ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w weixinRequestRuleDo) Join(table schema.Tabler, on ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w weixinRequestRuleDo) LeftJoin(table schema.Tabler, on ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w weixinRequestRuleDo) RightJoin(table schema.Tabler, on ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w weixinRequestRuleDo) Group(cols ...field.Expr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w weixinRequestRuleDo) Having(conds ...gen.Condition) *weixinRequestRuleDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w weixinRequestRuleDo) Limit(limit int) *weixinRequestRuleDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w weixinRequestRuleDo) Offset(offset int) *weixinRequestRuleDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w weixinRequestRuleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *weixinRequestRuleDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w weixinRequestRuleDo) Unscoped() *weixinRequestRuleDo {
	return w.withDO(w.DO.Unscoped())
}

func (w weixinRequestRuleDo) Create(values ...*model.WeixinRequestRule) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w weixinRequestRuleDo) CreateInBatches(values []*model.WeixinRequestRule, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w weixinRequestRuleDo) Save(values ...*model.WeixinRequestRule) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w weixinRequestRuleDo) First() (*model.WeixinRequestRule, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WeixinRequestRule), nil
	}
}

func (w weixinRequestRuleDo) Take() (*model.WeixinRequestRule, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WeixinRequestRule), nil
	}
}

func (w weixinRequestRuleDo) Last() (*model.WeixinRequestRule, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WeixinRequestRule), nil
	}
}

func (w weixinRequestRuleDo) Find() ([]*model.WeixinRequestRule, error) {
	result, err := w.DO.Find()
	return result.([]*model.WeixinRequestRule), err
}

func (w weixinRequestRuleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WeixinRequestRule, err error) {
	buf := make([]*model.WeixinRequestRule, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w weixinRequestRuleDo) FindInBatches(result *[]*model.WeixinRequestRule, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w weixinRequestRuleDo) Attrs(attrs ...field.AssignExpr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w weixinRequestRuleDo) Assign(attrs ...field.AssignExpr) *weixinRequestRuleDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w weixinRequestRuleDo) Joins(fields ...field.RelationField) *weixinRequestRuleDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w weixinRequestRuleDo) Preload(fields ...field.RelationField) *weixinRequestRuleDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w weixinRequestRuleDo) FirstOrInit() (*model.WeixinRequestRule, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WeixinRequestRule), nil
	}
}

func (w weixinRequestRuleDo) FirstOrCreate() (*model.WeixinRequestRule, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WeixinRequestRule), nil
	}
}

func (w weixinRequestRuleDo) FindByPage(offset int, limit int) (result []*model.WeixinRequestRule, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w weixinRequestRuleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w weixinRequestRuleDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w weixinRequestRuleDo) Delete(models ...*model.WeixinRequestRule) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *weixinRequestRuleDo) withDO(do gen.Dao) *weixinRequestRuleDo {
	w.DO = *do.(*gen.DO)
	return w
}
