// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newCmsSiteDomain(db *gorm.DB, opts ...gen.DOOption) cmsSiteDomain {
	_cmsSiteDomain := cmsSiteDomain{}

	_cmsSiteDomain.cmsSiteDomainDo.UseDB(db, opts...)
	_cmsSiteDomain.cmsSiteDomainDo.UseModel(&domain.CmsSiteDomain{})

	tableName := _cmsSiteDomain.cmsSiteDomainDo.TableName()
	_cmsSiteDomain.ALL = field.NewAsterisk(tableName)
	_cmsSiteDomain.DomainID = field.NewInt64(tableName, "domain_id")
	_cmsSiteDomain.SiteID = field.NewInt64(tableName, "site_id")
	_cmsSiteDomain.Domain = field.NewString(tableName, "domain")
	_cmsSiteDomain.Remark = field.NewString(tableName, "remark")
	_cmsSiteDomain.TenantID = field.NewInt64(tableName, "tenant_id")
	_cmsSiteDomain.Deleted = field.NewBool(tableName, "deleted")

	_cmsSiteDomain.fillFieldMap()

	return _cmsSiteDomain
}

type cmsSiteDomain struct {
	cmsSiteDomainDo cmsSiteDomainDo

	ALL field.Asterisk
	DomainID field.Int64 // 主键
	SiteID field.Int64 // 所属站点
	Domain field.String // 站点域名
	Remark field.String // 备注说明
	TenantID field.Int64
	Deleted field.Bool

	fieldMap map[string]field.Expr
}

func (c cmsSiteDomain) Table(newTableName string) *cmsSiteDomain {
	c.cmsSiteDomainDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsSiteDomain) As(alias string) *cmsSiteDomain {
	c.cmsSiteDomainDo.DO = *(c.cmsSiteDomainDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsSiteDomain) updateTableName(table string) *cmsSiteDomain {
	c.ALL = field.NewAsterisk(table)
	c.DomainID = field.NewInt64(table, "domain_id")
	c.SiteID = field.NewInt64(table, "site_id")
	c.Domain = field.NewString(table, "domain")
	c.Remark = field.NewString(table, "remark")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *cmsSiteDomain) WithContext(ctx context.Context) *cmsSiteDomainDo {
	return c.cmsSiteDomainDo.WithContext(ctx)
}

func (c cmsSiteDomain) TableName() string { return c.cmsSiteDomainDo.TableName() }

func (c cmsSiteDomain) Alias() string { return c.cmsSiteDomainDo.Alias() }

func (c cmsSiteDomain) Columns(cols ...field.Expr) gen.Columns { return c.cmsSiteDomainDo.Columns(cols...) }

func (c *cmsSiteDomain) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsSiteDomain) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 6)
	c.fieldMap["domain_id"] = c.DomainID
	c.fieldMap["site_id"] = c.SiteID
	c.fieldMap["domain"] = c.Domain
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["deleted"] = c.Deleted
}

func (c cmsSiteDomain) clone(db *gorm.DB) cmsSiteDomain {
	c.cmsSiteDomainDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsSiteDomain) replaceDB(db *gorm.DB) cmsSiteDomain {
	c.cmsSiteDomainDo.ReplaceDB(db)
	return c
}

type cmsSiteDomainDo struct{ gen.DO }

func (c cmsSiteDomainDo) Debug() *cmsSiteDomainDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsSiteDomainDo) WithContext(ctx context.Context) *cmsSiteDomainDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsSiteDomainDo) Session(config *gorm.Session) *cmsSiteDomainDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsSiteDomainDo) clauses(conds ...clause.Expression) *cmsSiteDomainDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsSiteDomainDo) Returning(value interface{}, columns ...string) *cmsSiteDomainDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsSiteDomainDo) Not(conds ...gen.Condition) *cmsSiteDomainDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsSiteDomainDo) Or(conds ...gen.Condition) *cmsSiteDomainDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsSiteDomainDo) Select(conds ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsSiteDomainDo) Where(conds ...gen.Condition) *cmsSiteDomainDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsSiteDomainDo) Order(conds ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsSiteDomainDo) Distinct(cols ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsSiteDomainDo) Omit(cols ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsSiteDomainDo) Join(table schema.Tabler, on ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsSiteDomainDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsSiteDomainDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsSiteDomainDo) Group(cols ...field.Expr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsSiteDomainDo) Having(conds ...gen.Condition) *cmsSiteDomainDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsSiteDomainDo) Limit(limit int) *cmsSiteDomainDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsSiteDomainDo) Offset(offset int) *cmsSiteDomainDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsSiteDomainDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsSiteDomainDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsSiteDomainDo) Unscoped() *cmsSiteDomainDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsSiteDomainDo) Attrs(attrs ...field.AssignExpr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsSiteDomainDo) Assign(attrs ...field.AssignExpr) *cmsSiteDomainDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsSiteDomainDo) ReadDB() *cmsSiteDomainDo {
	return c.withDO(c.Clauses(dbresolver.Read))
}

func (c cmsSiteDomainDo) WriteDB() *cmsSiteDomainDo {
	return c.withDO(c.Clauses(dbresolver.Write))
}

func (c cmsSiteDomainDo) Create(values ...*domain.CmsSiteDomain) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsSiteDomainDo) CreateInBatches(values []*domain.CmsSiteDomain, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsSiteDomainDo) Save(values ...*domain.CmsSiteDomain) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsSiteDomainDo) First() (*domain.CmsSiteDomain, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsSiteDomain), nil
	}
}

func (c cmsSiteDomainDo) Take() (*domain.CmsSiteDomain, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsSiteDomain), nil
	}
}

func (c cmsSiteDomainDo) Last() (*domain.CmsSiteDomain, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsSiteDomain), nil
	}
}

func (c cmsSiteDomainDo) Find() ([]*domain.CmsSiteDomain, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CmsSiteDomain), err
}

func (c cmsSiteDomainDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CmsSiteDomain, err error) {
	buf := make([]*domain.CmsSiteDomain, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsSiteDomainDo) FindInBatches(result *[]*domain.CmsSiteDomain, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsSiteDomainDo) Joins(fields ...field.RelationField) *cmsSiteDomainDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsSiteDomainDo) Preload(fields ...field.RelationField) *cmsSiteDomainDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsSiteDomainDo) FirstOrInit() (*domain.CmsSiteDomain, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsSiteDomain), nil
	}
}

func (c cmsSiteDomainDo) FirstOrCreate() (*domain.CmsSiteDomain, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsSiteDomain), nil
	}
}

func (c cmsSiteDomainDo) FindByPage(offset int, limit int) (result []*domain.CmsSiteDomain, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsSiteDomainDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}
	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsSiteDomainDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsSiteDomainDo) Delete(models ...*domain.CmsSiteDomain) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsSiteDomainDo) withDO(do gen.Dao) *cmsSiteDomainDo {
	c.DO = *do.(*gen.DO)
	return c
}
