// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newCmsAdminNotice(db *gorm.DB, opts ...gen.DOOption) cmsAdminNotice {
	_cmsAdminNotice := cmsAdminNotice{}

	_cmsAdminNotice.cmsAdminNoticeDo.UseDB(db, opts...)
	_cmsAdminNotice.cmsAdminNoticeDo.UseModel(&domain.CmsAdminNotice{})

	tableName := _cmsAdminNotice.cmsAdminNoticeDo.TableName()
	_cmsAdminNotice.ALL = field.NewAsterisk(tableName)
	_cmsAdminNotice.NoticeID = field.NewInt64(tableName, "notice_id")
	_cmsAdminNotice.Title = field.NewString(tableName, "title")
	_cmsAdminNotice.SubTitle = field.NewString(tableName, "sub_title")
	_cmsAdminNotice.Content = field.NewString(tableName, "content")
	_cmsAdminNotice.SortID = field.NewInt32(tableName, "sort_id")
	_cmsAdminNotice.IsTop = field.NewInt32(tableName, "is_top")
	_cmsAdminNotice.Status = field.NewInt32(tableName, "status")
	_cmsAdminNotice.PublishTime = field.NewTime(tableName, "publish_time")
	_cmsAdminNotice.CreateID = field.NewInt32(tableName, "create_id")
	_cmsAdminNotice.CreateName = field.NewString(tableName, "create_name")
	_cmsAdminNotice.CreateTime = field.NewTime(tableName, "create_time")
	_cmsAdminNotice.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsAdminNotice.UpdateName = field.NewString(tableName, "update_name")
	_cmsAdminNotice.UpdateTime = field.NewTime(tableName, "update_time")
	_cmsAdminNotice.TenantID = field.NewInt64(tableName, "tenant_id")
	_cmsAdminNotice.Deleted = field.NewBool(tableName, "deleted")

	_cmsAdminNotice.fillFieldMap()

	return _cmsAdminNotice
}

type cmsAdminNotice struct {
	cmsAdminNoticeDo cmsAdminNoticeDo

	ALL field.Asterisk
	NoticeID field.Int64
	Title field.String
	SubTitle field.String
	Content field.String
	SortID field.Int32
	IsTop field.Int32
	Status field.Int32
	PublishTime field.Time
	CreateID field.Int32
	CreateName field.String
	CreateTime field.Time
	UpdateID field.Int32
	UpdateName field.String
	UpdateTime field.Time
	TenantID field.Int64
	Deleted field.Bool

	fieldMap map[string]field.Expr
}

func (c cmsAdminNotice) Table(newTableName string) *cmsAdminNotice {
	c.cmsAdminNoticeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAdminNotice) As(alias string) *cmsAdminNotice {
	c.cmsAdminNoticeDo.DO = *(c.cmsAdminNoticeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAdminNotice) updateTableName(table string) *cmsAdminNotice {
	c.ALL = field.NewAsterisk(table)
	c.NoticeID = field.NewInt64(table, "notice_id")
	c.Title = field.NewString(table, "title")
	c.SubTitle = field.NewString(table, "sub_title")
	c.Content = field.NewString(table, "content")
	c.SortID = field.NewInt32(table, "sort_id")
	c.IsTop = field.NewInt32(table, "is_top")
	c.Status = field.NewInt32(table, "status")
	c.PublishTime = field.NewTime(table, "publish_time")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *cmsAdminNotice) WithContext(ctx context.Context) *cmsAdminNoticeDo {
	return c.cmsAdminNoticeDo.WithContext(ctx)
}

func (c cmsAdminNotice) TableName() string { return c.cmsAdminNoticeDo.TableName() }

func (c cmsAdminNotice) Alias() string { return c.cmsAdminNoticeDo.Alias() }

func (c cmsAdminNotice) Columns(cols ...field.Expr) gen.Columns { return c.cmsAdminNoticeDo.Columns(cols...) }

func (c *cmsAdminNotice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAdminNotice) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 16)
	c.fieldMap["notice_id"] = c.NoticeID
	c.fieldMap["title"] = c.Title
	c.fieldMap["sub_title"] = c.SubTitle
	c.fieldMap["content"] = c.Content
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["is_top"] = c.IsTop
	c.fieldMap["status"] = c.Status
	c.fieldMap["publish_time"] = c.PublishTime
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["deleted"] = c.Deleted
}

func (c cmsAdminNotice) clone(db *gorm.DB) cmsAdminNotice {
	c.cmsAdminNoticeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAdminNotice) replaceDB(db *gorm.DB) cmsAdminNotice {
	c.cmsAdminNoticeDo.ReplaceDB(db)
	return c
}

type cmsAdminNoticeDo struct{ gen.DO }

func (c cmsAdminNoticeDo) Debug() *cmsAdminNoticeDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAdminNoticeDo) WithContext(ctx context.Context) *cmsAdminNoticeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAdminNoticeDo) Session(config *gorm.Session) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAdminNoticeDo) clauses(conds ...clause.Expression) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAdminNoticeDo) Returning(value interface{}, columns ...string) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAdminNoticeDo) Not(conds ...gen.Condition) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAdminNoticeDo) Or(conds ...gen.Condition) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAdminNoticeDo) Select(conds ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAdminNoticeDo) Where(conds ...gen.Condition) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAdminNoticeDo) Order(conds ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAdminNoticeDo) Distinct(cols ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAdminNoticeDo) Omit(cols ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAdminNoticeDo) Join(table schema.Tabler, on ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAdminNoticeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAdminNoticeDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAdminNoticeDo) Group(cols ...field.Expr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAdminNoticeDo) Having(conds ...gen.Condition) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAdminNoticeDo) Limit(limit int) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAdminNoticeDo) Offset(offset int) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAdminNoticeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAdminNoticeDo) Unscoped() *cmsAdminNoticeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAdminNoticeDo) Attrs(attrs ...field.AssignExpr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAdminNoticeDo) Assign(attrs ...field.AssignExpr) *cmsAdminNoticeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAdminNoticeDo) ReadDB() *cmsAdminNoticeDo {
	return c.withDO(c.Clauses(dbresolver.Read))
}

func (c cmsAdminNoticeDo) WriteDB() *cmsAdminNoticeDo {
	return c.withDO(c.Clauses(dbresolver.Write))
}

func (c cmsAdminNoticeDo) Create(values ...*domain.CmsAdminNotice) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAdminNoticeDo) CreateInBatches(values []*domain.CmsAdminNotice, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAdminNoticeDo) Save(values ...*domain.CmsAdminNotice) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAdminNoticeDo) First() (*domain.CmsAdminNotice, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAdminNotice), nil
	}
}

func (c cmsAdminNoticeDo) Take() (*domain.CmsAdminNotice, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAdminNotice), nil
	}
}

func (c cmsAdminNoticeDo) Last() (*domain.CmsAdminNotice, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAdminNotice), nil
	}
}

func (c cmsAdminNoticeDo) Find() ([]*domain.CmsAdminNotice, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CmsAdminNotice), err
}

func (c cmsAdminNoticeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CmsAdminNotice, err error) {
	buf := make([]*domain.CmsAdminNotice, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAdminNoticeDo) FindInBatches(result *[]*domain.CmsAdminNotice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAdminNoticeDo) Joins(fields ...field.RelationField) *cmsAdminNoticeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAdminNoticeDo) Preload(fields ...field.RelationField) *cmsAdminNoticeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAdminNoticeDo) FirstOrInit() (*domain.CmsAdminNotice, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAdminNotice), nil
	}
}

func (c cmsAdminNoticeDo) FirstOrCreate() (*domain.CmsAdminNotice, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAdminNotice), nil
	}
}

func (c cmsAdminNoticeDo) FindByPage(offset int, limit int) (result []*domain.CmsAdminNotice, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAdminNoticeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}
	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAdminNoticeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAdminNoticeDo) Delete(models ...*domain.CmsAdminNotice) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAdminNoticeDo) withDO(do gen.Dao) *cmsAdminNoticeDo {
	c.DO = *do.(*gen.DO)
	return c
}
