// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newCmsTheme(db *gorm.DB, opts ...gen.DOOption) cmsTheme {
	_cmsTheme := cmsTheme{}

	_cmsTheme.cmsThemeDo.UseDB(db, opts...)
	_cmsTheme.cmsThemeDo.UseModel(&domain.CmsTheme{})

	tableName := _cmsTheme.cmsThemeDo.TableName()
	_cmsTheme.ALL = field.NewAsterisk(tableName)
	_cmsTheme.ThemeID = field.NewInt64(tableName, "theme_id")
	_cmsTheme.Name = field.NewString(tableName, "name")
	_cmsTheme.Type = field.NewInt32(tableName, "type")
	_cmsTheme.Title = field.NewString(tableName, "title")
	_cmsTheme.IsDefault = field.NewBool(tableName, "is_default")
	_cmsTheme.IsSystem = field.NewBool(tableName, "is_system")
	_cmsTheme.Thumb = field.NewString(tableName, "thumb")
	_cmsTheme.Version = field.NewString(tableName, "version")
	_cmsTheme.Author = field.NewString(tableName, "author")
	_cmsTheme.Remark = field.NewString(tableName, "remark")
	_cmsTheme.SortID = field.NewInt32(tableName, "sort_id")
	_cmsTheme.BelongTo = field.NewString(tableName, "belong_to")
	_cmsTheme.CreateID = field.NewInt32(tableName, "create_id")
	_cmsTheme.CreateName = field.NewString(tableName, "create_name")
	_cmsTheme.CreateTime = field.NewTime(tableName, "create_time")
	_cmsTheme.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsTheme.UpdateName = field.NewString(tableName, "update_name")
	_cmsTheme.UpdateTime = field.NewTime(tableName, "update_time")

	_cmsTheme.fillFieldMap()

	return _cmsTheme
}

type cmsTheme struct {
	cmsThemeDo cmsThemeDo

	ALL        field.Asterisk
	ThemeID    field.Int64  // 模板ID
	Name       field.String // 主题名称
	Type       field.Int32  // 类别(0系统；1高校)，根据业务需求添加
	Title      field.String // 主题标题
	IsDefault  field.Bool   // 是否默认主题
	IsSystem   field.Bool   // 是否系统主题
	Thumb      field.String // 主题预览图
	Version    field.String // 版本
	Author     field.String // 作者
	Remark     field.String // 主题描述
	SortID     field.Int32  // 排序
	BelongTo   field.String // 归属
	CreateID   field.Int32  // 创建人ID
	CreateName field.String // 创建人姓名
	CreateTime field.Time   // 创建时间
	UpdateID   field.Int32  // 更新人ID
	UpdateName field.String // 更新人姓名
	UpdateTime field.Time   // 修改时间

	fieldMap map[string]field.Expr
}

func (c cmsTheme) Table(newTableName string) *cmsTheme {
	c.cmsThemeDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsTheme) As(alias string) *cmsTheme {
	c.cmsThemeDo.DO = *(c.cmsThemeDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsTheme) updateTableName(table string) *cmsTheme {
	c.ALL = field.NewAsterisk(table)
	c.ThemeID = field.NewInt64(table, "theme_id")
	c.Name = field.NewString(table, "name")
	c.Type = field.NewInt32(table, "type")
	c.Title = field.NewString(table, "title")
	c.IsDefault = field.NewBool(table, "is_default")
	c.IsSystem = field.NewBool(table, "is_system")
	c.Thumb = field.NewString(table, "thumb")
	c.Version = field.NewString(table, "version")
	c.Author = field.NewString(table, "author")
	c.Remark = field.NewString(table, "remark")
	c.SortID = field.NewInt32(table, "sort_id")
	c.BelongTo = field.NewString(table, "belong_to")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")

	c.fillFieldMap()

	return c
}

func (c *cmsTheme) WithContext(ctx context.Context) *cmsThemeDo { return c.cmsThemeDo.WithContext(ctx) }

func (c cmsTheme) TableName() string { return c.cmsThemeDo.TableName() }

func (c cmsTheme) Alias() string { return c.cmsThemeDo.Alias() }

func (c cmsTheme) Columns(cols ...field.Expr) gen.Columns { return c.cmsThemeDo.Columns(cols...) }

func (c *cmsTheme) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsTheme) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 18)
	c.fieldMap["theme_id"] = c.ThemeID
	c.fieldMap["name"] = c.Name
	c.fieldMap["type"] = c.Type
	c.fieldMap["title"] = c.Title
	c.fieldMap["is_default"] = c.IsDefault
	c.fieldMap["is_system"] = c.IsSystem
	c.fieldMap["thumb"] = c.Thumb
	c.fieldMap["version"] = c.Version
	c.fieldMap["author"] = c.Author
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["belong_to"] = c.BelongTo
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
}

func (c cmsTheme) clone(db *gorm.DB) cmsTheme {
	c.cmsThemeDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsTheme) replaceDB(db *gorm.DB) cmsTheme {
	c.cmsThemeDo.ReplaceDB(db)
	return c
}

type cmsThemeDo struct{ gen.DO }

func (c cmsThemeDo) Debug() *cmsThemeDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsThemeDo) WithContext(ctx context.Context) *cmsThemeDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsThemeDo) ReadDB() *cmsThemeDo {
	return c.Clauses(dbresolver.Read)
}

func (c cmsThemeDo) WriteDB() *cmsThemeDo {
	return c.Clauses(dbresolver.Write)
}

func (c cmsThemeDo) Session(config *gorm.Session) *cmsThemeDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsThemeDo) Clauses(conds ...clause.Expression) *cmsThemeDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsThemeDo) Returning(value interface{}, columns ...string) *cmsThemeDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsThemeDo) Not(conds ...gen.Condition) *cmsThemeDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsThemeDo) Or(conds ...gen.Condition) *cmsThemeDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsThemeDo) Select(conds ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsThemeDo) Where(conds ...gen.Condition) *cmsThemeDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsThemeDo) Order(conds ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsThemeDo) Distinct(cols ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsThemeDo) Omit(cols ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsThemeDo) Join(table schema.Tabler, on ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsThemeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsThemeDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsThemeDo) Group(cols ...field.Expr) *cmsThemeDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsThemeDo) Having(conds ...gen.Condition) *cmsThemeDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsThemeDo) Limit(limit int) *cmsThemeDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsThemeDo) Offset(offset int) *cmsThemeDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsThemeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsThemeDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsThemeDo) Unscoped() *cmsThemeDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsThemeDo) Create(values ...*domain.CmsTheme) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsThemeDo) CreateInBatches(values []*domain.CmsTheme, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsThemeDo) Save(values ...*domain.CmsTheme) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsThemeDo) First() (*domain.CmsTheme, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsTheme), nil
	}
}

func (c cmsThemeDo) Take() (*domain.CmsTheme, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsTheme), nil
	}
}

func (c cmsThemeDo) Last() (*domain.CmsTheme, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsTheme), nil
	}
}

func (c cmsThemeDo) Find() ([]*domain.CmsTheme, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CmsTheme), err
}

func (c cmsThemeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CmsTheme, err error) {
	buf := make([]*domain.CmsTheme, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsThemeDo) FindInBatches(result *[]*domain.CmsTheme, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsThemeDo) Attrs(attrs ...field.AssignExpr) *cmsThemeDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsThemeDo) Assign(attrs ...field.AssignExpr) *cmsThemeDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsThemeDo) Joins(fields ...field.RelationField) *cmsThemeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsThemeDo) Preload(fields ...field.RelationField) *cmsThemeDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsThemeDo) FirstOrInit() (*domain.CmsTheme, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsTheme), nil
	}
}

func (c cmsThemeDo) FirstOrCreate() (*domain.CmsTheme, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsTheme), nil
	}
}

func (c cmsThemeDo) FindByPage(offset int, limit int) (result []*domain.CmsTheme, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsThemeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsThemeDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsThemeDo) Delete(models ...*domain.CmsTheme) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsThemeDo) withDO(do gen.Dao) *cmsThemeDo {
	c.DO = *do.(*gen.DO)
	return c
}
