// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newCmsAttach(db *gorm.DB, opts ...gen.DOOption) cmsAttach {
	_cmsAttach := cmsAttach{}

	_cmsAttach.cmsAttachDo.UseDB(db, opts...)
	_cmsAttach.cmsAttachDo.UseModel(&domain.CmsAttach{})

	tableName := _cmsAttach.cmsAttachDo.TableName()
	_cmsAttach.ALL = field.NewAsterisk(tableName)
	_cmsAttach.AttachID = field.NewInt64(tableName, "attach_id")
	_cmsAttach.TableName_ = field.NewString(tableName, "table_name")
	_cmsAttach.RecordID = field.NewInt64(tableName, "record_id")
	_cmsAttach.TypeID = field.NewInt32(tableName, "type_id")
	_cmsAttach.Title = field.NewString(tableName, "title")
	_cmsAttach.OriginalPath = field.NewString(tableName, "original_path")
	_cmsAttach.FilePath = field.NewString(tableName, "file_path")
	_cmsAttach.FileSize = field.NewInt64(tableName, "file_size")
	_cmsAttach.FileMime = field.NewString(tableName, "file_mime")
	_cmsAttach.FileExt = field.NewString(tableName, "file_ext")
	_cmsAttach.Point = field.NewInt32(tableName, "point")
	_cmsAttach.Click = field.NewInt32(tableName, "click")
	_cmsAttach.SortID = field.NewInt32(tableName, "sort_id")
	_cmsAttach.IsShow = field.NewInt32(tableName, "is_show")
	_cmsAttach.Remark = field.NewString(tableName, "remark")
	_cmsAttach.CreateID = field.NewInt32(tableName, "create_id")
	_cmsAttach.CreateName = field.NewString(tableName, "create_name")
	_cmsAttach.CreateTime = field.NewTime(tableName, "create_time")
	_cmsAttach.UpdateID = field.NewInt32(tableName, "update_id")
	_cmsAttach.UpdateName = field.NewString(tableName, "update_name")
	_cmsAttach.UpdateTime = field.NewTime(tableName, "update_time")
	_cmsAttach.TenantID = field.NewInt64(tableName, "tenant_id")
	_cmsAttach.Deleted = field.NewBool(tableName, "deleted")

	_cmsAttach.fillFieldMap()

	return _cmsAttach
}

type cmsAttach struct {
	cmsAttachDo cmsAttachDo

	ALL field.Asterisk
	AttachID field.Int64
	TableName_ field.String
	RecordID field.Int64
	TypeID field.Int32
	Title field.String
	OriginalPath field.String
	FilePath field.String
	FileSize field.Int64
	FileMime field.String
	FileExt field.String
	Point field.Int32
	Click field.Int32
	SortID field.Int32
	IsShow field.Int32
	Remark field.String
	CreateID field.Int32
	CreateName field.String
	CreateTime field.Time
	UpdateID field.Int32
	UpdateName field.String
	UpdateTime field.Time
	TenantID field.Int64
	Deleted field.Bool

	fieldMap map[string]field.Expr
}

func (c cmsAttach) Table(newTableName string) *cmsAttach {
	c.cmsAttachDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c cmsAttach) As(alias string) *cmsAttach {
	c.cmsAttachDo.DO = *(c.cmsAttachDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *cmsAttach) updateTableName(table string) *cmsAttach {
	c.ALL = field.NewAsterisk(table)
	c.AttachID = field.NewInt64(table, "attach_id")
	c.TableName_ = field.NewString(table, "table_name")
	c.RecordID = field.NewInt64(table, "record_id")
	c.TypeID = field.NewInt32(table, "type_id")
	c.Title = field.NewString(table, "title")
	c.OriginalPath = field.NewString(table, "original_path")
	c.FilePath = field.NewString(table, "file_path")
	c.FileSize = field.NewInt64(table, "file_size")
	c.FileMime = field.NewString(table, "file_mime")
	c.FileExt = field.NewString(table, "file_ext")
	c.Point = field.NewInt32(table, "point")
	c.Click = field.NewInt32(table, "click")
	c.SortID = field.NewInt32(table, "sort_id")
	c.IsShow = field.NewInt32(table, "is_show")
	c.Remark = field.NewString(table, "remark")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *cmsAttach) WithContext(ctx context.Context) *cmsAttachDo {
	return c.cmsAttachDo.WithContext(ctx)
}

func (c cmsAttach) TableName() string { return c.cmsAttachDo.TableName() }

func (c cmsAttach) Alias() string { return c.cmsAttachDo.Alias() }

func (c cmsAttach) Columns(cols ...field.Expr) gen.Columns { return c.cmsAttachDo.Columns(cols...) }

func (c *cmsAttach) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *cmsAttach) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 23)
	c.fieldMap["attach_id"] = c.AttachID
	c.fieldMap["table_name"] = c.TableName_
	c.fieldMap["record_id"] = c.RecordID
	c.fieldMap["type_id"] = c.TypeID
	c.fieldMap["title"] = c.Title
	c.fieldMap["original_path"] = c.OriginalPath
	c.fieldMap["file_path"] = c.FilePath
	c.fieldMap["file_size"] = c.FileSize
	c.fieldMap["file_mime"] = c.FileMime
	c.fieldMap["file_ext"] = c.FileExt
	c.fieldMap["point"] = c.Point
	c.fieldMap["click"] = c.Click
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["is_show"] = c.IsShow
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["deleted"] = c.Deleted
}

func (c cmsAttach) clone(db *gorm.DB) cmsAttach {
	c.cmsAttachDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c cmsAttach) replaceDB(db *gorm.DB) cmsAttach {
	c.cmsAttachDo.ReplaceDB(db)
	return c
}

type cmsAttachDo struct{ gen.DO }

func (c cmsAttachDo) Debug() *cmsAttachDo {
	return c.withDO(c.DO.Debug())
}

func (c cmsAttachDo) WithContext(ctx context.Context) *cmsAttachDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c cmsAttachDo) Session(config *gorm.Session) *cmsAttachDo {
	return c.withDO(c.DO.Session(config))
}

func (c cmsAttachDo) clauses(conds ...clause.Expression) *cmsAttachDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c cmsAttachDo) Returning(value interface{}, columns ...string) *cmsAttachDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c cmsAttachDo) Not(conds ...gen.Condition) *cmsAttachDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c cmsAttachDo) Or(conds ...gen.Condition) *cmsAttachDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c cmsAttachDo) Select(conds ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c cmsAttachDo) Where(conds ...gen.Condition) *cmsAttachDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c cmsAttachDo) Order(conds ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c cmsAttachDo) Distinct(cols ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c cmsAttachDo) Omit(cols ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c cmsAttachDo) Join(table schema.Tabler, on ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c cmsAttachDo) LeftJoin(table schema.Tabler, on ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c cmsAttachDo) RightJoin(table schema.Tabler, on ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c cmsAttachDo) Group(cols ...field.Expr) *cmsAttachDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c cmsAttachDo) Having(conds ...gen.Condition) *cmsAttachDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c cmsAttachDo) Limit(limit int) *cmsAttachDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c cmsAttachDo) Offset(offset int) *cmsAttachDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c cmsAttachDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *cmsAttachDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c cmsAttachDo) Unscoped() *cmsAttachDo {
	return c.withDO(c.DO.Unscoped())
}

func (c cmsAttachDo) Attrs(attrs ...field.AssignExpr) *cmsAttachDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c cmsAttachDo) Assign(attrs ...field.AssignExpr) *cmsAttachDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c cmsAttachDo) ReadDB() *cmsAttachDo {
	return c.withDO(c.Clauses(dbresolver.Read))
}

func (c cmsAttachDo) WriteDB() *cmsAttachDo {
	return c.withDO(c.Clauses(dbresolver.Write))
}

func (c cmsAttachDo) Create(values ...*domain.CmsAttach) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c cmsAttachDo) CreateInBatches(values []*domain.CmsAttach, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c cmsAttachDo) Save(values ...*domain.CmsAttach) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c cmsAttachDo) First() (*domain.CmsAttach, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAttach), nil
	}
}

func (c cmsAttachDo) Take() (*domain.CmsAttach, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAttach), nil
	}
}

func (c cmsAttachDo) Last() (*domain.CmsAttach, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAttach), nil
	}
}

func (c cmsAttachDo) Find() ([]*domain.CmsAttach, error) {
	result, err := c.DO.Find()
	return result.([]*domain.CmsAttach), err
}

func (c cmsAttachDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.CmsAttach, err error) {
	buf := make([]*domain.CmsAttach, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c cmsAttachDo) FindInBatches(result *[]*domain.CmsAttach, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c cmsAttachDo) Joins(fields ...field.RelationField) *cmsAttachDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c cmsAttachDo) Preload(fields ...field.RelationField) *cmsAttachDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c cmsAttachDo) FirstOrInit() (*domain.CmsAttach, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAttach), nil
	}
}

func (c cmsAttachDo) FirstOrCreate() (*domain.CmsAttach, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.CmsAttach), nil
	}
}

func (c cmsAttachDo) FindByPage(offset int, limit int) (result []*domain.CmsAttach, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c cmsAttachDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}
	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c cmsAttachDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c cmsAttachDo) Delete(models ...*domain.CmsAttach) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *cmsAttachDo) withDO(do gen.Dao) *cmsAttachDo {
	c.DO = *do.(*gen.DO)
	return c
}
