// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newPlgOnlineRegister(db *gorm.DB, opts ...gen.DOOption) plgOnlineRegister {
	_plgOnlineRegister := plgOnlineRegister{}

	_plgOnlineRegister.plgOnlineRegisterDo.UseDB(db, opts...)
	_plgOnlineRegister.plgOnlineRegisterDo.UseModel(&domain.PlgOnlineRegister{})

	tableName := _plgOnlineRegister.plgOnlineRegisterDo.TableName()
	_plgOnlineRegister.ALL = field.NewAsterisk(tableName)
	_plgOnlineRegister.RegisterID = field.NewInt64(tableName, "register_id")
	_plgOnlineRegister.RealName = field.NewString(tableName, "real_name")
	_plgOnlineRegister.Sex = field.NewString(tableName, "sex")
	_plgOnlineRegister.Year = field.NewString(tableName, "year")
	_plgOnlineRegister.Special = field.NewString(tableName, "special")
	_plgOnlineRegister.Degree = field.NewString(tableName, "degree")
	_plgOnlineRegister.Mobile = field.NewString(tableName, "mobile")
	_plgOnlineRegister.Email = field.NewString(tableName, "email")
	_plgOnlineRegister.Wechat = field.NewString(tableName, "wechat")
	_plgOnlineRegister.Address = field.NewString(tableName, "address")
	_plgOnlineRegister.Content = field.NewString(tableName, "content")
	_plgOnlineRegister.IP = field.NewString(tableName, "ip")
	_plgOnlineRegister.IsRead = field.NewInt32(tableName, "is_read")
	_plgOnlineRegister.Tags = field.NewString(tableName, "tags")
	_plgOnlineRegister.Remark = field.NewString(tableName, "remark")
	_plgOnlineRegister.CreateID = field.NewInt32(tableName, "create_id")
	_plgOnlineRegister.CreateName = field.NewString(tableName, "create_name")
	_plgOnlineRegister.CreateTime = field.NewTime(tableName, "create_time")
	_plgOnlineRegister.UpdateID = field.NewInt32(tableName, "update_id")
	_plgOnlineRegister.UpdateName = field.NewString(tableName, "update_name")
	_plgOnlineRegister.UpdateTime = field.NewTime(tableName, "update_time")
	_plgOnlineRegister.TenantID = field.NewInt64(tableName, "tenant_id")
	_plgOnlineRegister.Deleted = field.NewBool(tableName, "deleted")

	_plgOnlineRegister.fillFieldMap()

	return _plgOnlineRegister
}

type plgOnlineRegister struct {
	plgOnlineRegisterDo plgOnlineRegisterDo

	ALL field.Asterisk
	RegisterID field.Int64
	RealName field.String
	Sex field.String
	Year field.String
	Special field.String
	Degree field.String
	Mobile field.String
	Email field.String
	Wechat field.String
	Address field.String
	Content field.String
	IP field.String
	IsRead field.Int32
	Tags field.String
	Remark field.String
	CreateID field.Int32
	CreateName field.String
	CreateTime field.Time
	UpdateID field.Int32
	UpdateName field.String
	UpdateTime field.Time
	TenantID field.Int64
	Deleted field.Bool

	fieldMap map[string]field.Expr
}

func (c plgOnlineRegister) Table(newTableName string) *plgOnlineRegister {
	c.plgOnlineRegisterDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c plgOnlineRegister) As(alias string) *plgOnlineRegister {
	c.plgOnlineRegisterDo.DO = *(c.plgOnlineRegisterDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *plgOnlineRegister) updateTableName(table string) *plgOnlineRegister {
	c.ALL = field.NewAsterisk(table)
	c.RegisterID = field.NewInt64(table, "register_id")
	c.RealName = field.NewString(table, "real_name")
	c.Sex = field.NewString(table, "sex")
	c.Year = field.NewString(table, "year")
	c.Special = field.NewString(table, "special")
	c.Degree = field.NewString(table, "degree")
	c.Mobile = field.NewString(table, "mobile")
	c.Email = field.NewString(table, "email")
	c.Wechat = field.NewString(table, "wechat")
	c.Address = field.NewString(table, "address")
	c.Content = field.NewString(table, "content")
	c.IP = field.NewString(table, "ip")
	c.IsRead = field.NewInt32(table, "is_read")
	c.Tags = field.NewString(table, "tags")
	c.Remark = field.NewString(table, "remark")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *plgOnlineRegister) WithContext(ctx context.Context) *plgOnlineRegisterDo {
	return c.plgOnlineRegisterDo.WithContext(ctx)
}

func (c plgOnlineRegister) TableName() string { return c.plgOnlineRegisterDo.TableName() }

func (c plgOnlineRegister) Alias() string { return c.plgOnlineRegisterDo.Alias() }

func (c plgOnlineRegister) Columns(cols ...field.Expr) gen.Columns { return c.plgOnlineRegisterDo.Columns(cols...) }

func (c *plgOnlineRegister) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *plgOnlineRegister) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 23)
	c.fieldMap["register_id"] = c.RegisterID
	c.fieldMap["real_name"] = c.RealName
	c.fieldMap["sex"] = c.Sex
	c.fieldMap["year"] = c.Year
	c.fieldMap["special"] = c.Special
	c.fieldMap["degree"] = c.Degree
	c.fieldMap["mobile"] = c.Mobile
	c.fieldMap["email"] = c.Email
	c.fieldMap["wechat"] = c.Wechat
	c.fieldMap["address"] = c.Address
	c.fieldMap["content"] = c.Content
	c.fieldMap["ip"] = c.IP
	c.fieldMap["is_read"] = c.IsRead
	c.fieldMap["tags"] = c.Tags
	c.fieldMap["remark"] = c.Remark
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["deleted"] = c.Deleted
}

func (c plgOnlineRegister) clone(db *gorm.DB) plgOnlineRegister {
	c.plgOnlineRegisterDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c plgOnlineRegister) replaceDB(db *gorm.DB) plgOnlineRegister {
	c.plgOnlineRegisterDo.ReplaceDB(db)
	return c
}

type plgOnlineRegisterDo struct{ gen.DO }

func (c plgOnlineRegisterDo) Debug() *plgOnlineRegisterDo {
	return c.withDO(c.DO.Debug())
}

func (c plgOnlineRegisterDo) WithContext(ctx context.Context) *plgOnlineRegisterDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c plgOnlineRegisterDo) Session(config *gorm.Session) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Session(config))
}

func (c plgOnlineRegisterDo) clauses(conds ...clause.Expression) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c plgOnlineRegisterDo) Returning(value interface{}, columns ...string) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c plgOnlineRegisterDo) Not(conds ...gen.Condition) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c plgOnlineRegisterDo) Or(conds ...gen.Condition) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c plgOnlineRegisterDo) Select(conds ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c plgOnlineRegisterDo) Where(conds ...gen.Condition) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c plgOnlineRegisterDo) Order(conds ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c plgOnlineRegisterDo) Distinct(cols ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c plgOnlineRegisterDo) Omit(cols ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c plgOnlineRegisterDo) Join(table schema.Tabler, on ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c plgOnlineRegisterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c plgOnlineRegisterDo) RightJoin(table schema.Tabler, on ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c plgOnlineRegisterDo) Group(cols ...field.Expr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c plgOnlineRegisterDo) Having(conds ...gen.Condition) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c plgOnlineRegisterDo) Limit(limit int) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c plgOnlineRegisterDo) Offset(offset int) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c plgOnlineRegisterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c plgOnlineRegisterDo) Unscoped() *plgOnlineRegisterDo {
	return c.withDO(c.DO.Unscoped())
}

func (c plgOnlineRegisterDo) Attrs(attrs ...field.AssignExpr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c plgOnlineRegisterDo) Assign(attrs ...field.AssignExpr) *plgOnlineRegisterDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c plgOnlineRegisterDo) ReadDB() *plgOnlineRegisterDo {
	return c.withDO(c.Clauses(dbresolver.Read))
}

func (c plgOnlineRegisterDo) WriteDB() *plgOnlineRegisterDo {
	return c.withDO(c.Clauses(dbresolver.Write))
}

func (c plgOnlineRegisterDo) Create(values ...*domain.PlgOnlineRegister) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c plgOnlineRegisterDo) CreateInBatches(values []*domain.PlgOnlineRegister, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c plgOnlineRegisterDo) Save(values ...*domain.PlgOnlineRegister) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c plgOnlineRegisterDo) First() (*domain.PlgOnlineRegister, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PlgOnlineRegister), nil
	}
}

func (c plgOnlineRegisterDo) Take() (*domain.PlgOnlineRegister, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PlgOnlineRegister), nil
	}
}

func (c plgOnlineRegisterDo) Last() (*domain.PlgOnlineRegister, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PlgOnlineRegister), nil
	}
}

func (c plgOnlineRegisterDo) Find() ([]*domain.PlgOnlineRegister, error) {
	result, err := c.DO.Find()
	return result.([]*domain.PlgOnlineRegister), err
}

func (c plgOnlineRegisterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.PlgOnlineRegister, err error) {
	buf := make([]*domain.PlgOnlineRegister, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c plgOnlineRegisterDo) FindInBatches(result *[]*domain.PlgOnlineRegister, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c plgOnlineRegisterDo) Joins(fields ...field.RelationField) *plgOnlineRegisterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c plgOnlineRegisterDo) Preload(fields ...field.RelationField) *plgOnlineRegisterDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c plgOnlineRegisterDo) FirstOrInit() (*domain.PlgOnlineRegister, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PlgOnlineRegister), nil
	}
}

func (c plgOnlineRegisterDo) FirstOrCreate() (*domain.PlgOnlineRegister, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.PlgOnlineRegister), nil
	}
}

func (c plgOnlineRegisterDo) FindByPage(offset int, limit int) (result []*domain.PlgOnlineRegister, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c plgOnlineRegisterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}
	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c plgOnlineRegisterDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c plgOnlineRegisterDo) Delete(models ...*domain.PlgOnlineRegister) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *plgOnlineRegisterDo) withDO(do gen.Dao) *plgOnlineRegisterDo {
	c.DO = *do.(*gen.DO)
	return c
}
