// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newWeixinAccount(db *gorm.DB, opts ...gen.DOOption) weixinAccount {
	_weixinAccount := weixinAccount{}

	_weixinAccount.weixinAccountDo.UseDB(db, opts...)
	_weixinAccount.weixinAccountDo.UseModel(&domain.WeixinAccount{})

	tableName := _weixinAccount.weixinAccountDo.TableName()
	_weixinAccount.ALL = field.NewAsterisk(tableName)
	_weixinAccount.AccountID = field.NewInt64(tableName, "account_id")
	_weixinAccount.Name = field.NewString(tableName, "name")
	_weixinAccount.OriginalID = field.NewString(tableName, "original_id")
	_weixinAccount.WxCode = field.NewString(tableName, "wx_code")
	_weixinAccount.Token = field.NewString(tableName, "token")
	_weixinAccount.AppID = field.NewString(tableName, "app_id")
	_weixinAccount.AppSecret = field.NewString(tableName, "app_secret")
	_weixinAccount.AppAesKey = field.NewString(tableName, "app_aes_key")
	_weixinAccount.IsPush = field.NewBool(tableName, "is_push")
	_weixinAccount.SortID = field.NewInt32(tableName, "sort_id")
	_weixinAccount.Status = field.NewInt32(tableName, "status")
	_weixinAccount.BelongTo = field.NewString(tableName, "belong_to")
	_weixinAccount.CreateID = field.NewInt32(tableName, "create_id")
	_weixinAccount.CreateName = field.NewString(tableName, "create_name")
	_weixinAccount.CreateTime = field.NewTime(tableName, "create_time")
	_weixinAccount.UpdateID = field.NewInt32(tableName, "update_id")
	_weixinAccount.UpdateName = field.NewString(tableName, "update_name")
	_weixinAccount.UpdateTime = field.NewTime(tableName, "update_time")
	_weixinAccount.TenantID = field.NewInt64(tableName, "tenant_id")
	_weixinAccount.Deleted = field.NewBool(tableName, "deleted")

	_weixinAccount.fillFieldMap()

	return _weixinAccount
}

type weixinAccount struct {
	weixinAccountDo weixinAccountDo

	ALL field.Asterisk
	AccountID field.Int64
	Name field.String
	OriginalID field.String
	WxCode field.String
	Token field.String
	AppID field.String
	AppSecret field.String
	AppAesKey field.String
	IsPush field.Bool
	SortID field.Int32
	Status field.Int32
	BelongTo field.String
	CreateID field.Int32
	CreateName field.String
	CreateTime field.Time
	UpdateID field.Int32
	UpdateName field.String
	UpdateTime field.Time
	TenantID field.Int64
	Deleted field.Bool

	fieldMap map[string]field.Expr
}

func (c weixinAccount) Table(newTableName string) *weixinAccount {
	c.weixinAccountDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c weixinAccount) As(alias string) *weixinAccount {
	c.weixinAccountDo.DO = *(c.weixinAccountDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *weixinAccount) updateTableName(table string) *weixinAccount {
	c.ALL = field.NewAsterisk(table)
	c.AccountID = field.NewInt64(table, "account_id")
	c.Name = field.NewString(table, "name")
	c.OriginalID = field.NewString(table, "original_id")
	c.WxCode = field.NewString(table, "wx_code")
	c.Token = field.NewString(table, "token")
	c.AppID = field.NewString(table, "app_id")
	c.AppSecret = field.NewString(table, "app_secret")
	c.AppAesKey = field.NewString(table, "app_aes_key")
	c.IsPush = field.NewBool(table, "is_push")
	c.SortID = field.NewInt32(table, "sort_id")
	c.Status = field.NewInt32(table, "status")
	c.BelongTo = field.NewString(table, "belong_to")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *weixinAccount) WithContext(ctx context.Context) *weixinAccountDo {
	return c.weixinAccountDo.WithContext(ctx)
}

func (c weixinAccount) TableName() string { return c.weixinAccountDo.TableName() }

func (c weixinAccount) Alias() string { return c.weixinAccountDo.Alias() }

func (c weixinAccount) Columns(cols ...field.Expr) gen.Columns { return c.weixinAccountDo.Columns(cols...) }

func (c *weixinAccount) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *weixinAccount) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 20)
	c.fieldMap["account_id"] = c.AccountID
	c.fieldMap["name"] = c.Name
	c.fieldMap["original_id"] = c.OriginalID
	c.fieldMap["wx_code"] = c.WxCode
	c.fieldMap["token"] = c.Token
	c.fieldMap["app_id"] = c.AppID
	c.fieldMap["app_secret"] = c.AppSecret
	c.fieldMap["app_aes_key"] = c.AppAesKey
	c.fieldMap["is_push"] = c.IsPush
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["status"] = c.Status
	c.fieldMap["belong_to"] = c.BelongTo
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["deleted"] = c.Deleted
}

func (c weixinAccount) clone(db *gorm.DB) weixinAccount {
	c.weixinAccountDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c weixinAccount) replaceDB(db *gorm.DB) weixinAccount {
	c.weixinAccountDo.ReplaceDB(db)
	return c
}

type weixinAccountDo struct{ gen.DO }

func (c weixinAccountDo) Debug() *weixinAccountDo {
	return c.withDO(c.DO.Debug())
}

func (c weixinAccountDo) WithContext(ctx context.Context) *weixinAccountDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c weixinAccountDo) Session(config *gorm.Session) *weixinAccountDo {
	return c.withDO(c.DO.Session(config))
}

func (c weixinAccountDo) clauses(conds ...clause.Expression) *weixinAccountDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c weixinAccountDo) Returning(value interface{}, columns ...string) *weixinAccountDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c weixinAccountDo) Not(conds ...gen.Condition) *weixinAccountDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c weixinAccountDo) Or(conds ...gen.Condition) *weixinAccountDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c weixinAccountDo) Select(conds ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c weixinAccountDo) Where(conds ...gen.Condition) *weixinAccountDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c weixinAccountDo) Order(conds ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c weixinAccountDo) Distinct(cols ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c weixinAccountDo) Omit(cols ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c weixinAccountDo) Join(table schema.Tabler, on ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c weixinAccountDo) LeftJoin(table schema.Tabler, on ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c weixinAccountDo) RightJoin(table schema.Tabler, on ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c weixinAccountDo) Group(cols ...field.Expr) *weixinAccountDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c weixinAccountDo) Having(conds ...gen.Condition) *weixinAccountDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c weixinAccountDo) Limit(limit int) *weixinAccountDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c weixinAccountDo) Offset(offset int) *weixinAccountDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c weixinAccountDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *weixinAccountDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c weixinAccountDo) Unscoped() *weixinAccountDo {
	return c.withDO(c.DO.Unscoped())
}

func (c weixinAccountDo) Attrs(attrs ...field.AssignExpr) *weixinAccountDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c weixinAccountDo) Assign(attrs ...field.AssignExpr) *weixinAccountDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c weixinAccountDo) ReadDB() *weixinAccountDo {
	return c.withDO(c.Clauses(dbresolver.Read))
}

func (c weixinAccountDo) WriteDB() *weixinAccountDo {
	return c.withDO(c.Clauses(dbresolver.Write))
}

func (c weixinAccountDo) Create(values ...*domain.WeixinAccount) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c weixinAccountDo) CreateInBatches(values []*domain.WeixinAccount, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c weixinAccountDo) Save(values ...*domain.WeixinAccount) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c weixinAccountDo) First() (*domain.WeixinAccount, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinAccount), nil
	}
}

func (c weixinAccountDo) Take() (*domain.WeixinAccount, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinAccount), nil
	}
}

func (c weixinAccountDo) Last() (*domain.WeixinAccount, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinAccount), nil
	}
}

func (c weixinAccountDo) Find() ([]*domain.WeixinAccount, error) {
	result, err := c.DO.Find()
	return result.([]*domain.WeixinAccount), err
}

func (c weixinAccountDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.WeixinAccount, err error) {
	buf := make([]*domain.WeixinAccount, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c weixinAccountDo) FindInBatches(result *[]*domain.WeixinAccount, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c weixinAccountDo) Joins(fields ...field.RelationField) *weixinAccountDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c weixinAccountDo) Preload(fields ...field.RelationField) *weixinAccountDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c weixinAccountDo) FirstOrInit() (*domain.WeixinAccount, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinAccount), nil
	}
}

func (c weixinAccountDo) FirstOrCreate() (*domain.WeixinAccount, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinAccount), nil
	}
}

func (c weixinAccountDo) FindByPage(offset int, limit int) (result []*domain.WeixinAccount, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c weixinAccountDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}
	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c weixinAccountDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c weixinAccountDo) Delete(models ...*domain.WeixinAccount) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *weixinAccountDo) withDO(do gen.Dao) *weixinAccountDo {
	c.DO = *do.(*gen.DO)
	return c
}
