// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package mapper

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/plugin/dbresolver"

	"haedu.gov.cn/cms/app/cms/domain"
)

func newWeixinMpVerify(db *gorm.DB, opts ...gen.DOOption) weixinMpVerify {
	_weixinMpVerify := weixinMpVerify{}

	_weixinMpVerify.weixinMpVerifyDo.UseDB(db, opts...)
	_weixinMpVerify.weixinMpVerifyDo.UseModel(&domain.WeixinMpVerify{})

	tableName := _weixinMpVerify.weixinMpVerifyDo.TableName()
	_weixinMpVerify.ALL = field.NewAsterisk(tableName)
	_weixinMpVerify.VerifyID = field.NewInt64(tableName, "verify_id")
	_weixinMpVerify.AccountID = field.NewInt64(tableName, "account_id")
	_weixinMpVerify.Path = field.NewString(tableName, "path")
	_weixinMpVerify.FilePath = field.NewString(tableName, "file_path")
	_weixinMpVerify.FileName = field.NewString(tableName, "file_name")
	_weixinMpVerify.SortID = field.NewInt32(tableName, "sort_id")
	_weixinMpVerify.Status = field.NewInt32(tableName, "status")
	_weixinMpVerify.CreateID = field.NewInt32(tableName, "create_id")
	_weixinMpVerify.CreateName = field.NewString(tableName, "create_name")
	_weixinMpVerify.CreateTime = field.NewTime(tableName, "create_time")
	_weixinMpVerify.UpdateID = field.NewInt32(tableName, "update_id")
	_weixinMpVerify.UpdateName = field.NewString(tableName, "update_name")
	_weixinMpVerify.UpdateTime = field.NewTime(tableName, "update_time")
	_weixinMpVerify.TenantID = field.NewInt64(tableName, "tenant_id")
	_weixinMpVerify.Deleted = field.NewBool(tableName, "deleted")

	_weixinMpVerify.fillFieldMap()

	return _weixinMpVerify
}

type weixinMpVerify struct {
	weixinMpVerifyDo weixinMpVerifyDo

	ALL field.Asterisk
	VerifyID field.Int64
	AccountID field.Int64
	Path field.String
	FilePath field.String
	FileName field.String
	SortID field.Int32
	Status field.Int32
	CreateID field.Int32
	CreateName field.String
	CreateTime field.Time
	UpdateID field.Int32
	UpdateName field.String
	UpdateTime field.Time
	TenantID field.Int64
	Deleted field.Bool

	fieldMap map[string]field.Expr
}

func (c weixinMpVerify) Table(newTableName string) *weixinMpVerify {
	c.weixinMpVerifyDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c weixinMpVerify) As(alias string) *weixinMpVerify {
	c.weixinMpVerifyDo.DO = *(c.weixinMpVerifyDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *weixinMpVerify) updateTableName(table string) *weixinMpVerify {
	c.ALL = field.NewAsterisk(table)
	c.VerifyID = field.NewInt64(table, "verify_id")
	c.AccountID = field.NewInt64(table, "account_id")
	c.Path = field.NewString(table, "path")
	c.FilePath = field.NewString(table, "file_path")
	c.FileName = field.NewString(table, "file_name")
	c.SortID = field.NewInt32(table, "sort_id")
	c.Status = field.NewInt32(table, "status")
	c.CreateID = field.NewInt32(table, "create_id")
	c.CreateName = field.NewString(table, "create_name")
	c.CreateTime = field.NewTime(table, "create_time")
	c.UpdateID = field.NewInt32(table, "update_id")
	c.UpdateName = field.NewString(table, "update_name")
	c.UpdateTime = field.NewTime(table, "update_time")
	c.TenantID = field.NewInt64(table, "tenant_id")
	c.Deleted = field.NewBool(table, "deleted")

	c.fillFieldMap()

	return c
}

func (c *weixinMpVerify) WithContext(ctx context.Context) *weixinMpVerifyDo {
	return c.weixinMpVerifyDo.WithContext(ctx)
}

func (c weixinMpVerify) TableName() string { return c.weixinMpVerifyDo.TableName() }

func (c weixinMpVerify) Alias() string { return c.weixinMpVerifyDo.Alias() }

func (c weixinMpVerify) Columns(cols ...field.Expr) gen.Columns { return c.weixinMpVerifyDo.Columns(cols...) }

func (c *weixinMpVerify) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *weixinMpVerify) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 15)
	c.fieldMap["verify_id"] = c.VerifyID
	c.fieldMap["account_id"] = c.AccountID
	c.fieldMap["path"] = c.Path
	c.fieldMap["file_path"] = c.FilePath
	c.fieldMap["file_name"] = c.FileName
	c.fieldMap["sort_id"] = c.SortID
	c.fieldMap["status"] = c.Status
	c.fieldMap["create_id"] = c.CreateID
	c.fieldMap["create_name"] = c.CreateName
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_id"] = c.UpdateID
	c.fieldMap["update_name"] = c.UpdateName
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["tenant_id"] = c.TenantID
	c.fieldMap["deleted"] = c.Deleted
}

func (c weixinMpVerify) clone(db *gorm.DB) weixinMpVerify {
	c.weixinMpVerifyDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c weixinMpVerify) replaceDB(db *gorm.DB) weixinMpVerify {
	c.weixinMpVerifyDo.ReplaceDB(db)
	return c
}

type weixinMpVerifyDo struct{ gen.DO }

func (c weixinMpVerifyDo) Debug() *weixinMpVerifyDo {
	return c.withDO(c.DO.Debug())
}

func (c weixinMpVerifyDo) WithContext(ctx context.Context) *weixinMpVerifyDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c weixinMpVerifyDo) Session(config *gorm.Session) *weixinMpVerifyDo {
	return c.withDO(c.DO.Session(config))
}

func (c weixinMpVerifyDo) clauses(conds ...clause.Expression) *weixinMpVerifyDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c weixinMpVerifyDo) Returning(value interface{}, columns ...string) *weixinMpVerifyDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c weixinMpVerifyDo) Not(conds ...gen.Condition) *weixinMpVerifyDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c weixinMpVerifyDo) Or(conds ...gen.Condition) *weixinMpVerifyDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c weixinMpVerifyDo) Select(conds ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c weixinMpVerifyDo) Where(conds ...gen.Condition) *weixinMpVerifyDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c weixinMpVerifyDo) Order(conds ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c weixinMpVerifyDo) Distinct(cols ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c weixinMpVerifyDo) Omit(cols ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c weixinMpVerifyDo) Join(table schema.Tabler, on ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c weixinMpVerifyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c weixinMpVerifyDo) RightJoin(table schema.Tabler, on ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c weixinMpVerifyDo) Group(cols ...field.Expr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c weixinMpVerifyDo) Having(conds ...gen.Condition) *weixinMpVerifyDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c weixinMpVerifyDo) Limit(limit int) *weixinMpVerifyDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c weixinMpVerifyDo) Offset(offset int) *weixinMpVerifyDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c weixinMpVerifyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *weixinMpVerifyDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c weixinMpVerifyDo) Unscoped() *weixinMpVerifyDo {
	return c.withDO(c.DO.Unscoped())
}

func (c weixinMpVerifyDo) Attrs(attrs ...field.AssignExpr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c weixinMpVerifyDo) Assign(attrs ...field.AssignExpr) *weixinMpVerifyDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c weixinMpVerifyDo) ReadDB() *weixinMpVerifyDo {
	return c.withDO(c.Clauses(dbresolver.Read))
}

func (c weixinMpVerifyDo) WriteDB() *weixinMpVerifyDo {
	return c.withDO(c.Clauses(dbresolver.Write))
}

func (c weixinMpVerifyDo) Create(values ...*domain.WeixinMpVerify) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c weixinMpVerifyDo) CreateInBatches(values []*domain.WeixinMpVerify, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c weixinMpVerifyDo) Save(values ...*domain.WeixinMpVerify) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c weixinMpVerifyDo) First() (*domain.WeixinMpVerify, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinMpVerify), nil
	}
}

func (c weixinMpVerifyDo) Take() (*domain.WeixinMpVerify, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinMpVerify), nil
	}
}

func (c weixinMpVerifyDo) Last() (*domain.WeixinMpVerify, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinMpVerify), nil
	}
}

func (c weixinMpVerifyDo) Find() ([]*domain.WeixinMpVerify, error) {
	result, err := c.DO.Find()
	return result.([]*domain.WeixinMpVerify), err
}

func (c weixinMpVerifyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*domain.WeixinMpVerify, err error) {
	buf := make([]*domain.WeixinMpVerify, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c weixinMpVerifyDo) FindInBatches(result *[]*domain.WeixinMpVerify, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c weixinMpVerifyDo) Joins(fields ...field.RelationField) *weixinMpVerifyDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c weixinMpVerifyDo) Preload(fields ...field.RelationField) *weixinMpVerifyDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c weixinMpVerifyDo) FirstOrInit() (*domain.WeixinMpVerify, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinMpVerify), nil
	}
}

func (c weixinMpVerifyDo) FirstOrCreate() (*domain.WeixinMpVerify, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*domain.WeixinMpVerify), nil
	}
}

func (c weixinMpVerifyDo) FindByPage(offset int, limit int) (result []*domain.WeixinMpVerify, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c weixinMpVerifyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}
	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c weixinMpVerifyDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c weixinMpVerifyDo) Delete(models ...*domain.WeixinMpVerify) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *weixinMpVerifyDo) withDO(do gen.Dao) *weixinMpVerifyDo {
	c.DO = *do.(*gen.DO)
	return c
}
